/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import "DOMHTMLElement.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface DOMHTMLScriptElement : DOMHTMLElement {
}
@property(assign) BOOL async;	// G=0x35be4751; S=0x35be480d; converted property
@property(copy) NSString *charset;	// G=0x35be3f3d; S=0x35be4385; 
@property(assign) BOOL defer;	// G=0x35be48d9; S=0x35be49a1; 
@property(copy) NSString *event;	// G=0x35be3e5d; S=0x35be4241; 
@property(copy) NSString *htmlFor;	// G=0x35be3d7d; S=0x35be40fd; 
@property(copy) NSString *src;	// G=0x35be4a79; S=0x35be44c9; 
@property(copy) NSString *text;	// G=0x35be3af1; S=0x35be3c45; 
@property(copy) NSString *type;	// G=0x35be401d; S=0x35be460d; 
// converted property getter: - (BOOL)async;	// 0x35be4751
// declared property getter: - (id)charset;	// 0x35be3f3d
// declared property getter: - (BOOL)defer;	// 0x35be48d9
// declared property getter: - (id)event;	// 0x35be3e5d
// declared property getter: - (id)htmlFor;	// 0x35be3d7d
// converted property setter: - (void)setAsync:(BOOL)async;	// 0x35be480d
// declared property setter: - (void)setCharset:(id)charset;	// 0x35be4385
// declared property setter: - (void)setDefer:(BOOL)defer;	// 0x35be49a1
// declared property setter: - (void)setEvent:(id)event;	// 0x35be4241
// declared property setter: - (void)setHtmlFor:(id)aFor;	// 0x35be40fd
// declared property setter: - (void)setSrc:(id)src;	// 0x35be44c9
// declared property setter: - (void)setText:(id)text;	// 0x35be3c45
// declared property setter: - (void)setType:(id)type;	// 0x35be460d
// declared property getter: - (id)src;	// 0x35be4a79
// declared property getter: - (id)text;	// 0x35be3af1
// declared property getter: - (id)type;	// 0x35be401d
@end

