/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

#import </libobjc.A.h>

@class NSString;

@interface MLEQPreset : NSObject {
	NSString *_name;	// 4 = 0x4
	NSString *_localizedName;	// 8 = 0x8
	int _builtInPresetType;	// 12 = 0xc
}
@property(readonly, assign) int builtInPresetType;	// G=0x31519881; converted property
@property(readonly, retain) NSString *localizedName;	// G=0x3151986d; converted property
@property(readonly, retain) NSString *name;	// G=0x31519859; converted property
+ (id)eqPresetForBuiltInPresetType:(int)presetType;	// 0x31519761
+ (id)eqPresetForName:(id)name;	// 0x31505495
- (id)initWithBuiltInPresetType:(int)presetType;	// 0x315196d5
- (void).cxx_destruct;	// 0x315198ad
// converted property getter: - (int)builtInPresetType;	// 0x31519881
// converted property getter: - (id)localizedName;	// 0x3151986d
// converted property getter: - (id)name;	// 0x31519859
- (int)typeForAVController;	// 0x31519891
@end

