/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CoreMediaStream.framework/CoreMediaStream
 */

#import <NSObject.h> // Unknown library
#import "NSCoding.h"

@class NSDictionary, NSString;

@interface MSASEnqueuedCommand : NSObject <NSCoding> {
	NSString *_command;	// 4 = 0x4
	NSDictionary *_variantParam;	// 8 = 0x8
	NSDictionary *_invariantParam;	// 12 = 0xc
}
@property(copy, nonatomic) NSString *command;	// G=0x337f9e71; S=0x337f9e85; @synthesize=_command
@property(retain, nonatomic) NSDictionary *invariantParam;	// G=0x337f9ecd; S=0x337f9edd; @synthesize=_invariantParam
@property(retain, nonatomic) NSDictionary *variantParam;	// G=0x337f9e95; S=0x337f9ea5; @synthesize=_variantParam
+ (id)command;	// 0x337f9a8d
+ (id)commandwithCommand:(id)command variantParam:(id)param invariantParam:(id)param3;	// 0x337f9ac5
- (id)init;	// 0x337f9b45
- (id)initWithCoder:(id)coder;	// 0x337f9d8d
- (id)initWithCommand:(id)command variantParam:(id)param invariantParam:(id)param3;	// 0x337f9b75
- (void).cxx_destruct;	// 0x337f9f05
- (BOOL)canBeGroupedWithCommand:(id)command;	// 0x337f9c3d
// declared property getter: - (id)command;	// 0x337f9e71
- (void)encodeWithCoder:(id)coder;	// 0x337f9cf1
// declared property getter: - (id)invariantParam;	// 0x337f9ecd
// declared property setter: - (void)setCommand:(id)command;	// 0x337f9e85
// declared property setter: - (void)setInvariantParam:(id)param;	// 0x337f9edd
// declared property setter: - (void)setVariantParam:(id)param;	// 0x337f9ea5
// declared property getter: - (id)variantParam;	// 0x337f9e95
@end

