/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "CHDChartTypeWithGrouping.h"


@interface CHDBar2DType : CHDChartTypeWithGrouping {
	int mGapWidth;	// 28 = 0x1c
	bool mColumn;	// 32 = 0x20
	int mOverlap;	// 36 = 0x24
}
@property(assign, getter=isColumn) bool column;	// G=0x36b42909; S=0x36b3dab1; converted property
@property(assign) int gapWidth;	// G=0x36bbbae1; S=0x36b3da99; converted property
@property(assign) int overlap;	// G=0x36bbbaf1; S=0x36b3da89; converted property
- (id)initWithChart:(id)chart;	// 0x36b3d82d
- (int)defaultLabelPosition;	// 0x36bbbb01
// converted property getter: - (int)gapWidth;	// 0x36bbbae1
// converted property getter: - (bool)isColumn;	// 0x36b42909
- (bool)isHorizontal;	// 0x36b40c0d
// converted property getter: - (int)overlap;	// 0x36bbbaf1
// converted property setter: - (void)setColumn:(bool)column;	// 0x36b3dab1
// converted property setter: - (void)setGapWidth:(int)width;	// 0x36b3da99
// converted property setter: - (void)setOverlap:(int)overlap;	// 0x36b3da89
@end

