/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OADProperties.h"

@class OADOrientedBounds, OADHyperlink;

@interface OADDrawableProperties : OADProperties {
	OADOrientedBounds *mOrientedBounds;	// 12 = 0xc
	OADHyperlink *mClickHyperlink;	// 16 = 0x10
	OADHyperlink *mHoverHyperlink;	// 20 = 0x14
	unsigned mHasAspectRatioLocked : 1;	// 24 = 0x18
	unsigned mAspectRatioLocked : 1;	// 24 = 0x18
	unsigned mHasWrdInline : 1;	// 24 = 0x18
	unsigned mWrdInline : 1;	// 24 = 0x18
}
@property(assign, getter=isAspectRatioLocked) BOOL aspectRatioLocked;	// G=0x36a35875; S=0x369eaaf1; converted property
@property(retain) id clickHyperlink;	// G=0x36ac714d; S=0x36a4d93d; converted property
@property(retain) id hoverHyperlink;	// G=0x36c132ad; S=0x36b899ad; converted property
@property(retain) id orientedBounds;	// G=0x36a30759; S=0x369e1da1; converted property
@property(assign, getter=isWrdInline) BOOL wrdInline;	// G=0x36b8eb91; S=0x36b8eb59; converted property
- (id)initWithDefaults;	// 0x369e1bfd
// converted property getter: - (id)clickHyperlink;	// 0x36ac714d
- (void)dealloc;	// 0x369e6751
- (BOOL)hasAspectRatioLocked;	// 0x36a35861
- (BOOL)hasClickHyperlink;	// 0x36a35a2d
- (BOOL)hasHoverHyperlink;	// 0x36a35a61
- (BOOL)hasOrientedBounds;	// 0x36a30725
- (BOOL)hasWrdInline;	// 0x36a35a95
- (unsigned)hash;	// 0x36c132bd
// converted property getter: - (id)hoverHyperlink;	// 0x36c132ad
// converted property getter: - (BOOL)isAspectRatioLocked;	// 0x36a35875
- (BOOL)isEqual:(id)equal;	// 0x36c13369
// converted property getter: - (BOOL)isWrdInline;	// 0x36b8eb91
// converted property getter: - (id)orientedBounds;	// 0x36a30759
- (void)removeUnnecessaryOverrides;	// 0x36a35565
// converted property setter: - (void)setAspectRatioLocked:(BOOL)locked;	// 0x369eaaf1
// converted property setter: - (void)setClickHyperlink:(id)hyperlink;	// 0x36a4d93d
// converted property setter: - (void)setHoverHyperlink:(id)hyperlink;	// 0x36b899ad
// converted property setter: - (void)setOrientedBounds:(id)bounds;	// 0x369e1da1
// converted property setter: - (void)setWrdInline:(BOOL)anInline;	// 0x36b8eb59
@end

