/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UIView.h"
#import "UIDimmingViewDelegate.h"

@class NSTimer, UIInputSwitcherShadowView, UIDimmingView, UITableView;

__attribute__((visibility("hidden")))
@interface UIKeyboardMenuView : UIView <UITableViewDataSource, UITableViewDelegate, UIDimmingViewDelegate> {
	UITableView *m_table;	// 88 = 0x58
	UIInputSwitcherShadowView *m_shadowView;	// 92 = 0x5c
	UIView *m_selExtraView;	// 96 = 0x60
	CGRect m_referenceRect;	// 100 = 0x64
	float m_pointerOffset;	// 116 = 0x74
	BOOL m_scrollable;	// 120 = 0x78
	BOOL m_scrolling;	// 121 = 0x79
	BOOL m_shouldFade;	// 122 = 0x7a
	CGPoint m_point;	// 124 = 0x7c
	double m_scrollStartTime;	// 132 = 0x84
	int m_scrollDirection;	// 140 = 0x8c
	NSTimer *m_scrollTimer;	// 144 = 0x90
	int m_visibleRows;	// 148 = 0x94
	int m_firstVisibleRow;	// 152 = 0x98
	int m_mode;	// 156 = 0x9c
	double dismissDelay;	// 160 = 0xa0
	UIDimmingView *m_dimmingView;	// 168 = 0xa8
	double _dismissDelay;	// 172 = 0xac
}
@property(readonly, retain) UIDimmingView *dimmingView;	// G=0x30c8a265; converted property
@property(assign) double dismissDelay;	// G=0x30c8bd9d; S=0x30a12431; @synthesize=_dismissDelay
@property(assign, nonatomic) int mode;	// G=0x30c8bd7d; S=0x30c8bd8d; @synthesize=m_mode
@property(readonly, assign) BOOL usesTable;	// G=0x30a12379; 
- (id)initWithFrame:(CGRect)frame;	// 0x30a11d71
- (void)_delayedFade;	// 0x30c8aa15
- (void)applicationWillSuspend:(id)application;	// 0x30c8a169
- (void)autoscrollTimerFired:(id)fired;	// 0x30c8aec1
- (BOOL)centerPopUpOverKey;	// 0x30c8a165
- (void)dealloc;	// 0x30c8a0a9
- (int)defaultSelectedIndex;	// 0x30c8bd45
- (void)didSelectItemAtIndex:(int)index;	// 0x30c8bd79
// converted property getter: - (id)dimmingView;	// 0x30c8a265
- (void)dimmingViewWasTapped:(id)tapped;	// 0x30c8a399
// declared property getter: - (double)dismissDelay;	// 0x30c8bd9d
- (void)endScrolling:(id)scrolling;	// 0x30c8ad11
- (void)fade;	// 0x30c8ab19
- (void)fadeAnimationDidStop:(id)fadeAnimation finished:(id)finished context:(void *)context;	// 0x30c8ac0d
- (void)fadeWithDelay:(double)delay;	// 0x30c8ab71
- (id)font;	// 0x30c8a19d
- (void)hide;	// 0x30a12791
- (void)highlightRow:(int)row;	// 0x30c8b5ad
- (int)indexForIndexPath:(id)indexPath;	// 0x30c8b70d
- (BOOL)isVisible;	// 0x30a126c5
// declared property getter: - (int)mode;	// 0x30c8bd7d
- (int)numberOfItems;	// 0x30c8bd41
- (void)performShowAnimation;	// 0x30c8a1c1
- (CGSize)preferredSize;	// 0x30c8bd49
- (void)removeFromSuperview;	// 0x30c8abb1
- (void)selectItemAtPoint:(CGPoint)point;	// 0x30c8b699
// declared property setter: - (void)setDismissDelay:(double)delay;	// 0x30a12431
- (void)setFrame:(CGRect)frame;	// 0x30a11fd1
// declared property setter: - (void)setMode:(int)mode;	// 0x30c8bd8d
- (void)setNeedsDisplayForCell:(id)cell;	// 0x30c8ac41
- (void)setNeedsDisplayForTopBottomCells;	// 0x30c8ac89
- (void)show;	// 0x30c8a3b9
- (void)showAsHUD;	// 0x30c8a911
- (void)showAsPopupFromRect:(CGRect)rect inView:(id)view;	// 0x30c8a969
- (void)stopAnyAutoscrolling;	// 0x30c8ae19
- (id)subtitleFont;	// 0x30c8a179
- (id)subtitleForItemAtIndex:(int)index;	// 0x30c8bd6d
- (id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;	// 0x30c8b731
- (void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;	// 0x30c8bb59
- (float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;	// 0x30c8bb51
- (int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0x30c8b721
- (id)titleForItemAtIndex:(int)index;	// 0x30c8bd61
- (void)touchesBegan:(id)began withEvent:(id)event;	// 0x30c8bb8d
- (void)touchesCancelled:(id)cancelled withEvent:(id)event;	// 0x30c8bd31
- (void)touchesEnded:(id)ended withEvent:(id)event;	// 0x30c8bc59
- (void)touchesMoved:(id)moved withEvent:(id)event;	// 0x30c8bbf1
- (void)updateSelectionWithPoint:(CGPoint)point;	// 0x30c8b1e9
// declared property getter: - (BOOL)usesTable;	// 0x30a12379
@end

