/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import "MediaPlayer-Structs.h"
#import "NSCopying.h"
#import <NSObject.h> // Unknown library

@class NSDate, NSString;

@interface MPMovieAccessLogEvent : NSObject <NSCopying> {
@private
	MPMovieAccessLogEventInternal _internal;	// 4 = 0x4
}
@property(readonly, assign, nonatomic) NSString *URI;	// G=0x33bafdc9; 
@property(assign, nonatomic) MPMovieAccessLogEventInternal _internal;	// G=0x33baff49; S=0x33baff5d; @synthesize
@property(readonly, assign, nonatomic) double durationWatched;	// G=0x33bafe89; 
@property(readonly, assign, nonatomic) double indicatedBitrate;	// G=0x33baff09; 
@property(readonly, assign, nonatomic) long long numberOfBytesTransferred;	// G=0x33bafec9; 
@property(readonly, assign, nonatomic) int numberOfDroppedVideoFrames;	// G=0x33baff29; 
@property(readonly, assign, nonatomic) unsigned numberOfSegmentsDownloaded;	// G=0x33bafd89; 
@property(readonly, assign, nonatomic) unsigned numberOfServerAddressChanges;	// G=0x33bafe09; 
@property(readonly, assign, nonatomic) int numberOfStalls;	// G=0x33bafea9; 
@property(readonly, assign, nonatomic) double observedBitrate;	// G=0x33bafee9; 
@property(readonly, assign, nonatomic) NSString *playbackSessionID;	// G=0x33bafe29; 
@property(readonly, assign, nonatomic) NSDate *playbackStartDate;	// G=0x33bafda9; 
@property(readonly, assign, nonatomic) double playbackStartOffset;	// G=0x33bafe49; 
@property(readonly, assign, nonatomic) double segmentsDownloadedDuration;	// G=0x33bafe69; 
@property(readonly, assign, nonatomic) NSString *serverAddress;	// G=0x33bafde9; 
// declared property getter: - (id)URI;	// 0x33bafdc9
- (id)_initWithAVItemAccessLogEvent:(id)avitemAccessLogEvent;	// 0x33bafcd9
// declared property getter: - (MPMovieAccessLogEventInternal)_internal;	// 0x33baff49
- (id)copyWithZone:(NSZone *)zone;	// 0x33bafd79
- (void)dealloc;	// 0x33bafd2d
// declared property getter: - (double)durationWatched;	// 0x33bafe89
// declared property getter: - (double)indicatedBitrate;	// 0x33baff09
// declared property getter: - (long long)numberOfBytesTransferred;	// 0x33bafec9
// declared property getter: - (int)numberOfDroppedVideoFrames;	// 0x33baff29
// declared property getter: - (unsigned)numberOfSegmentsDownloaded;	// 0x33bafd89
// declared property getter: - (unsigned)numberOfServerAddressChanges;	// 0x33bafe09
// declared property getter: - (int)numberOfStalls;	// 0x33bafea9
// declared property getter: - (double)observedBitrate;	// 0x33bafee9
// declared property getter: - (id)playbackSessionID;	// 0x33bafe29
// declared property getter: - (id)playbackStartDate;	// 0x33bafda9
// declared property getter: - (double)playbackStartOffset;	// 0x33bafe49
// declared property getter: - (double)segmentsDownloadedDuration;	// 0x33bafe69
// declared property getter: - (id)serverAddress;	// 0x33bafde9
// declared property setter: - (void)set_internal:(MPMovieAccessLogEventInternal)internal;	// 0x33baff5d
@end

