/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

#import "GeoServices-Structs.h"
#import <PBCodable.h> // Unknown library

@class NSMutableArray, NSString;

@interface GEOCategory : PBCodable {
	long long _geoOntologyId;	// 4 = 0x4
	NSString *_alias;	// 12 = 0xc
	int _level;	// 16 = 0x10
	NSMutableArray *_localizedNames;	// 20 = 0x14
	XXStruct_ec15KC _has;	// 24 = 0x18
}
@property(retain, nonatomic) NSString *alias;	// G=0x324ff34d; S=0x324ff35d; @synthesize=_alias
@property(assign, nonatomic) long long geoOntologyId;	// G=0x324ff38d; S=0x324fe75d; @synthesize=_geoOntologyId
@property(assign, nonatomic) BOOL hasGeoOntologyId;	// G=0x324fe7ad; S=0x324fe791; 
@property(assign, nonatomic) int level;	// G=0x324ff36d; S=0x324ff37d; @synthesize=_level
@property(retain, nonatomic) NSMutableArray *localizedNames;	// G=0x324ff3a5; S=0x324ff3b5; @synthesize=_localizedNames
- (void)addLocalizedNames:(id)names;	// 0x324fe7e1
// declared property getter: - (id)alias;	// 0x324ff34d
- (void)clearLocalizedNames;	// 0x324fe7c1
- (void)copyTo:(id)to;	// 0x324ff0a1
- (void)dealloc;	// 0x324fe705
- (id)description;	// 0x324fe88d
- (id)dictionaryRepresentation;	// 0x324fe8fd
// declared property getter: - (long long)geoOntologyId;	// 0x324ff38d
// declared property getter: - (BOOL)hasGeoOntologyId;	// 0x324fe7ad
- (unsigned)hash;	// 0x324ff2ad
- (BOOL)isEqual:(id)equal;	// 0x324ff1ad
// declared property getter: - (int)level;	// 0x324ff36d
// declared property getter: - (id)localizedNames;	// 0x324ff3a5
- (id)localizedNamesAtIndex:(unsigned)index;	// 0x324fe86d
- (unsigned)localizedNamesCount;	// 0x324fe84d
- (BOOL)readFrom:(id)from;	// 0x324feecd
// declared property setter: - (void)setAlias:(id)alias;	// 0x324ff35d
// declared property setter: - (void)setGeoOntologyId:(long long)anId;	// 0x324fe75d
// declared property setter: - (void)setHasGeoOntologyId:(BOOL)anId;	// 0x324fe791
// declared property setter: - (void)setLevel:(int)level;	// 0x324ff37d
// declared property setter: - (void)setLocalizedNames:(id)names;	// 0x324ff3b5
- (void)writeTo:(id)to;	// 0x324feed9
@end

