/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

#import "GeoServices-Structs.h"
#import <NSObject.h> // Unknown library

@class NSThread, GEOTileKeyList, NSString;
@protocol GEOTileRequesterDelegate;

@interface GEOTileRequester : NSObject {
	GEOTileKeyList *_keyList;	// 4 = 0x4
	id<GEOTileRequesterDelegate> _delegate;	// 8 = 0x8
	id _context;	// 12 = 0xc
	NSThread *_thread;	// 16 = 0x10
	NSString *_bundleIdentifier;	// 20 = 0x14
	NSString *_bundleVersion;	// 24 = 0x18
}
@property(retain, nonatomic) NSString *bundleIdentifier;	// G=0x32455b85; S=0x32455b95; @synthesize=_bundleIdentifier
@property(retain, nonatomic) NSString *bundleVersion;	// G=0x32455ba5; S=0x32455bb5; @synthesize=_bundleVersion
@property(retain, nonatomic) id context;	// G=0x32455b65; S=0x32455b75; @synthesize=_context
@property(retain, nonatomic) id<GEOTileRequesterDelegate> delegate;	// G=0x32455b15; S=0x32455b25; @synthesize=_delegate
@property(readonly, assign, nonatomic) GEOTileKeyList *keyList;	// G=0x32455b35; @synthesize=_keyList
@property(retain, nonatomic) NSThread *thread;	// G=0x32455b45; S=0x32455b55; @synthesize=_thread
+ (XXStruct_nbUehC *)expiringTilesets;	// 0x32455a5d
+ (unsigned)expiringTilesetsCount;	// 0x32455a59
+ (BOOL)skipNetworkForKeysWhenPreloading:(id)keysWhenPreloading;	// 0x32455a61
+ (unsigned char)tileProviderIdentifier;	// 0x324559f5
- (id)initWithKeyList:(id)keyList;	// 0x324559f9
// declared property getter: - (id)bundleIdentifier;	// 0x32455b85
// declared property getter: - (id)bundleVersion;	// 0x32455ba5
- (void)cancel;	// 0x32455a51
// declared property getter: - (id)context;	// 0x32455b65
- (void)dealloc;	// 0x32455a65
// declared property getter: - (id)delegate;	// 0x32455b15
// declared property getter: - (id)keyList;	// 0x32455b35
// declared property setter: - (void)setBundleIdentifier:(id)identifier;	// 0x32455b95
// declared property setter: - (void)setBundleVersion:(id)version;	// 0x32455bb5
// declared property setter: - (void)setContext:(id)context;	// 0x32455b75
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x32455b25
// declared property setter: - (void)setThread:(id)thread;	// 0x32455b55
- (void)start;	// 0x32455a4d
// declared property getter: - (id)thread;	// 0x32455b45
- (unsigned)tileSetForKey:(const GEOTileKey *)key;	// 0x32455a55
@end

