/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

#import <UINavigationController.h> // Unknown library
#import "UIViewControllerRestoration.h"


@interface ABAccountsAndGroupsNavigationController : UINavigationController <UIViewControllerRestoration> {
}
+ (id)viewControllerWithRestorationIdentifierPath:(id)restorationIdentifierPath coder:(id)coder;	// 0x34fafe31
- (void)decodeRestorableStateWithCoder:(id)coder;	// 0x34faff49
- (void)encodeRestorableStateWithCoder:(id)coder;	// 0x34fafe6d
@end

