/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ToneLibrary.framework/ToneLibrary
 */

#import <NSObject.h> // Unknown library


@interface TLVibrationManagerServiceClientXPCObjectWrapper : NSObject {
@private
	void *_xpcObject;	// 4 = 0x4
}
@property(assign, nonatomic, setter=setXPCObject:) void *xpcObject;	// G=0x3159df71; S=0x3159df81; 
- (void)dealloc;	// 0x3159df2d
// declared property setter: - (void)setXPCObject:(void *)object;	// 0x3159df81
// declared property getter: - (void *)xpcObject;	// 0x3159df71
@end

