/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import <UIColor.h> // Unknown library


@interface UIColor (TSUAdditions)
+ (id)checkerboardColorWithColor:(id)color andColor:(id)color2 squareSize:(CGSize)size;	// 0x34cbc919
+ (id)grayCheckerboardColor;	// 0x34cbc9d1
+ (id)tableViewCellDarkBlueTextColor;	// 0x34cbcae5
+ (id)tangierScrollViewTexturedBackgroundColor;	// 0x34cbcb4d
+ (id)transparentGrayCheckerboardColor;	// 0x34cbca59
@end

