/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import "CMDrawableMapper.h"


@interface EMDrawableMapper : CMDrawableMapper {
	double *mRowGrid;	// 80 = 0x50
	double *mColumnGrid;	// 84 = 0x54
}
+ (BOOL)isAnchorRelative:(id)relative;	// 0x318a9949
- (id)initWithChartDrawable:(id)chartDrawable box:(CGRect)box parent:(id)parent;	// 0x317ff251
- (id)initWithOADDrawable:(id)oaddrawable parent:(id)parent;	// 0x317be531
- (id)initWithOADDrawable:(id)oaddrawable rowGrid:(double *)grid columnGrid:(double *)grid3;	// 0x318a9899
- (CGPoint)anchorMarkerToPosition:(EDCellAnchorMarker)position rowGrid:(double *)grid columnGrid:(double *)grid3 start:(BOOL)start relative:(BOOL)relative;	// 0x317bedf1
- (CGRect)getImageRect;	// 0x317be9c9
- (CGRect)mapAnchorToRect:(id)rect rowGrid:(double *)grid columnGrid:(double *)grid3;	// 0x317beae9
- (void)mapAt:(id)at withState:(id)state;	// 0x317be64d
- (void)mapBounds;	// 0x317be941
- (void)mapChartAt:(id)at withState:(id)state;	// 0x317ff2fd
- (void)mapDiagramAt:(id)at withState:(id)state;	// 0x318a99c5
- (void)mapOfficeArtGroupAt:(id)at withState:(id)state;	// 0x31806d7d
- (void)mapOfficeArtShapeAt:(id)at withState:(id)state;	// 0x317bf8bd
- (void)mapTextBoxAt:(id)at withState:(id)state;	// 0x317e5eb9
- (void)setBoundingBox;	// 0x318a98ed
- (id)workbookMapper;	// 0x318a9939
- (id)worksheetMapper;	// 0x317be5b9
@end

