/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library


@interface BRUserPasswordAuthenticationResources : NSObject {
}
+ (id)resources;	// 0x3419dca5
- (id)accountNameFootnote;	// 0x3419dd7d
- (id)accountNameInstructions;	// 0x3419dd2d
- (id)accountNameLabel;	// 0x3419dd55
- (id)accountNameTitle;	// 0x3419dd05
- (id)accountPasswordInstructions;	// 0x3419dda9
- (id)accountPasswordLabel;	// 0x3419ddd1
- (id)accountPasswordTitle;	// 0x3419dd81
- (id)authenticationCancellationTitle;	// 0x3419deb5
- (id)authenticationFailureInstructions;	// 0x3419de8d
- (id)authenticationFailureTitle;	// 0x3419de65
- (double)authenticationTimeout;	// 0x3419dedd
- (id)authenticationTimeoutMessage;	// 0x3419dee9
- (id)behaviorIdentifierForTextHistoryStorage;	// 0x3419df15
- (id)behaviorsForTextHistoryDisplay;	// 0x3419df1d
- (id)clientIdentifierForTextHistoryStorage;	// 0x3419df11
- (id)clientsForTextHistoryDisplay;	// 0x3419df19
- (id)connectionString;	// 0x3419dcdd
- (id)defaultPasswordKey;	// 0x3419ddfd
- (id)defaultUserName;	// 0x3419de15
- (id)defaultUserNameKey;	// 0x3419de09
- (id)titleImage;	// 0x3419ddf9
@end

