/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import "MediaPlayer-Structs.h"
#import "NSCoding.h"
#import <NSObject.h> // Unknown library

@class NSArray, NSMutableArray, MPMediaPlaylist, MPMediaQuery, NSString;

@interface MPGeniusMix : NSObject <NSCoding> {
@private
	MPMediaPlaylist *_playlist;	// 4 = 0x4
	MPMediaQuery *_seedTracksQuery;	// 8 = 0x8
	NSArray *_representativeArtists;	// 12 = 0xc
	NSMutableArray *_representativeImageItems;	// 16 = 0x10
}
@property(readonly, assign, nonatomic) NSString *name;	// G=0x34e45e25; 
@property(readonly, assign, nonatomic) MPMediaPlaylist *playlist;	// G=0x34e46cc9; @synthesize=_playlist
@property(readonly, assign, nonatomic) NSArray *representativeArtists;	// G=0x34e45f09; 
@property(readonly, assign, nonatomic) MPMediaQuery *seedTracksQuery;	// G=0x34e45e51; 
+ (id)artworkCacheDirectoryPath;	// 0x34e463dd
+ (id)artworkImageForMediaItem:(id)mediaItem;	// 0x34e46379
- (id)initWithCoder:(id)coder;	// 0x34e45c75
- (id)initWithMPMediaPlaylist:(id)mpmediaPlaylist;	// 0x34e459d9
- (id)_cacheDirectoryPath;	// 0x34e46bd9
- (id)_cachedRepresentativeImagePath;	// 0x34e46c95
- (unsigned)countOfRepresentativeImagesWithMaxCount:(unsigned)maxCount;	// 0x34e45fc1
- (void)dealloc;	// 0x34e45a61
- (id)description;	// 0x34e45be5
- (void)encodeWithCoder:(id)coder;	// 0x34e45db9
- (unsigned)hash;	// 0x34e45ba1
- (BOOL)isEqual:(id)equal;	// 0x34e45ae9
// declared property getter: - (id)name;	// 0x34e45e25
// declared property getter: - (id)playlist;	// 0x34e46cc9
// declared property getter: - (id)representativeArtists;	// 0x34e45f09
- (CGImageRef)representativeImageWithSize:(CGSize)size count:(unsigned)count;	// 0x34e463e1
- (CGImageRef)representativeImageWithSize:(CGSize)size count:(unsigned)count cacheOnly:(BOOL)only;	// 0x34e46405
// declared property getter: - (id)seedTracksQuery;	// 0x34e45e51
@end

