/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ATVSlideshow.framework/ATVSlideshow
 */

#import "ATVSlideshow-Structs.h"
#import "MPAction.h"
#import "MPActionSupport.h"

@class NSString;

@interface MPConditionalAction : MPAction <MPActionSupport> {
	NSString *_predicate;	// 20 = 0x14
	MPAction *_actionIfTrue;	// 24 = 0x18
	MPAction *_actionIfFalse;	// 28 = 0x1c
}
@property(readonly, assign) MPAction *actionIfFalse;	// G=0x348f271d; @synthesize=_actionIfFalse
@property(readonly, assign) MPAction *actionIfTrue;	// G=0x348f270d; @synthesize=_actionIfTrue
@property(copy, nonatomic) NSString *predicate;	// G=0x348f26fd; S=0x348f20e1; @synthesize=_predicate
+ (id)conditionalAction;	// 0x348f1d49
- (id)init;	// 0x348f1d8d
- (id)initWithCoder:(id)coder;	// 0x348f1de9
// declared property getter: - (id)actionIfFalse;	// 0x348f271d
// declared property getter: - (id)actionIfTrue;	// 0x348f270d
- (void)configureActions;	// 0x348f239d
- (void)configureTarget;	// 0x348f26a5
- (id)copyWithZone:(NSZone *)zone;	// 0x348f2009
- (void)dealloc;	// 0x348f1edd
- (void)encodeWithCoder:(id)coder;	// 0x348f1f51
// declared property getter: - (id)predicate;	// 0x348f26fd
- (void)setAction:(id)action;	// 0x348f232d
- (void)setAction:(id)action forCondition:(BOOL)condition;	// 0x348f21ad
// declared property setter: - (void)setPredicate:(id)predicate;	// 0x348f20e1
@end

