/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ATVSlideshow.framework/ATVSlideshow
 */

#import <NSObject.h> // Unknown library
#import "ATVSlideshow-Structs.h"

@class NSAttributedString;

@interface MRTextRenderer : NSObject {
	NSAttributedString *_text;	// 4 = 0x4
	NSAttributedString *_cachedText;	// 8 = 0x8
	NSAttributedString *_placeholderText;	// 12 = 0xc
	CGSize _maxSize;	// 16 = 0x10
	CGSize _resolution;	// 24 = 0x18
	int _maxNumberOfLines;	// 32 = 0x20
	int _lastGlyphIndex;	// 36 = 0x24
	BOOL _truncate;	// 40 = 0x28
	BOOL _renderAtMaxSize;	// 41 = 0x29
	float _lineSpacingFactor;	// 44 = 0x2c
}
@property(assign, nonatomic) float lineSpacingFactor;	// G=0x34a2ebcd; S=0x34a2ebdd; @synthesize=_lineSpacingFactor
@property(assign, nonatomic) int maxNumberOfLines;	// G=0x34a2eb3d; S=0x34a2eb4d; @synthesize=_maxNumberOfLines
@property(assign, nonatomic) CGSize maxSize;	// G=0x34a2eb7d; S=0x34a2eb99; @synthesize=_maxSize
@property(assign, nonatomic) NSAttributedString *placeholderText;	// G=0x34a2eb11; S=0x34a2ba89; @synthesize=_placeholderText
@property(assign, nonatomic) BOOL renderAtMaxSize;	// G=0x34a2ebad; S=0x34a2ebbd; @synthesize=_renderAtMaxSize
@property(assign, nonatomic) CGSize resolution;	// G=0x34a2eb21; S=0x34a2bbc9; @synthesize=_resolution
@property(assign, nonatomic) NSAttributedString *text;	// G=0x34a2ba45; S=0x34a2bb29; @synthesize=_text
@property(assign, nonatomic) BOOL truncate;	// G=0x34a2eb5d; S=0x34a2eb6d; @synthesize=_truncate
- (id)init;	// 0x34a2b865
- (id)initWithText:(id)text resolution:(CGSize)resolution;	// 0x34a2b901
- (void)_drawInContext:(CGContextRef)context withAttributedString:(id)attributedString withSize:(CGSize)size;	// 0x34a2c211
- (int)_numberOfLinesInString:(id)string;	// 0x34a2e1b1
- (CGContextRef)_retainedContextFromAttributedString:(id)attributedString withSize:(CGSize)size;	// 0x34a2c15d
- (CGSize)_shadowSizeOffsetForString:(id)string;	// 0x34a2e511
- (CGSize)_sizeOfString:(id)string ignoreResolution:(BOOL)resolution;	// 0x34a2dcd9
- (CGSize)_sizeToRendererAt;	// 0x34a2bd45
- (CGRect)_textClipRectForString:(id)string;	// 0x34a2c50d
- (CGRect)_tightFrameOfLineAtIndex:(int)index inString:(id)string withSize:(CGSize)size;	// 0x34a2bf85
- (id)_truncateTextToFitInSize:(CGSize)size fromCenter:(BOOL)center outSize:(CGSize *)size3;	// 0x34a2e69d
- (void)cleanup;	// 0x34a2b9ed
- (int)countOfGlyphs;	// 0x34a2d065
- (int)countOfWords;	// 0x34a2c659
- (void)dealloc;	// 0x34a2b96d
- (void)finalize;	// 0x34a2b9ad
- (CGRect)frameOfLineWithGlyphAtIndex:(int)index range:(NSRange *)range;	// 0x34a2d86d
- (int)glyphIndexForStringIndex:(int)stringIndex;	// 0x34a2d485
// declared property getter: - (float)lineSpacingFactor;	// 0x34a2ebcd
// declared property getter: - (int)maxNumberOfLines;	// 0x34a2eb3d
// declared property getter: - (CGSize)maxSize;	// 0x34a2eb7d
- (int)numberOfLines;	// 0x34a2e135
- (int)numberOfLinesForTruncatedText;	// 0x34a2e165
- (CGPoint)originOfGlyphAtIndex:(int)index;	// 0x34a2d659
- (CGPoint)originOfWordAtIndex:(int)index;	// 0x34a2ce5d
// declared property getter: - (id)placeholderText;	// 0x34a2eb11
- (XXStruct_K5nmsA)rangeOfGlyphsOnLine:(int)glyphsOnLine;	// 0x34a2cab1
- (XXStruct_K5nmsA)rangeOfStringForGlyphIndex:(int)glyphIndex;	// 0x34a2d275
- (XXStruct_K5nmsA)rangeOfWordsOnLine:(int)wordsOnLine;	// 0x34a2c7c1
// declared property getter: - (BOOL)renderAtMaxSize;	// 0x34a2ebad
// declared property getter: - (CGSize)resolution;	// 0x34a2eb21
- (CGContextRef)retainedContext;	// 0x34a2bbfd
- (CGContextRef)retainedContextOfGlyphAtIndex:(int)index;	// 0x34a2d191
- (CGContextRef)retainedContextOfWordsInRange:(XXStruct_K5nmsA)range;	// 0x34a2cc11
// declared property setter: - (void)setLineSpacingFactor:(float)factor;	// 0x34a2ebdd
// declared property setter: - (void)setMaxNumberOfLines:(int)lines;	// 0x34a2eb4d
// declared property setter: - (void)setMaxSize:(CGSize)size;	// 0x34a2eb99
// declared property setter: - (void)setPlaceholderText:(id)text;	// 0x34a2ba89
// declared property setter: - (void)setRenderAtMaxSize:(BOOL)maxSize;	// 0x34a2ebbd
// declared property setter: - (void)setResolution:(CGSize)resolution;	// 0x34a2bbc9
// declared property setter: - (void)setText:(id)text;	// 0x34a2bb29
// declared property setter: - (void)setTruncate:(BOOL)truncate;	// 0x34a2eb6d
- (CGSize)shadowOffset;	// 0x34a2e329
- (CGSize)sizeOfText;	// 0x34a2bcbd
- (void)squeezeWidthForLineCount:(int)lineCount;	// 0x34a2e629
// declared property getter: - (id)text;	// 0x34a2ba45
- (CGRect)tightFrameOfAllLines;	// 0x34a2bda9
- (CGRect)tightFrameOfLineAtIndex:(int)index;	// 0x34a2bea5
- (void)trimWhitespace;	// 0x34a2ea1d
// declared property getter: - (BOOL)truncate;	// 0x34a2eb5d
@end

