/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ATVAirPlayDataClient : XXUnknownSuperclass {
}
+ (id)airPlayDataClient;	// 0x46a945
- (void)concreteDataClientConnect;	// 0x46aa15
- (BOOL)supportsProperty:(id)property;	// 0x46a9e1
@end

