/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BRSingleton.h"

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface BRDarwinNotificationTranslator : BRSingleton {
	NSMutableDictionary *_registrations;	// 4 = 0x4
}
+ (BOOL)deregisterDarwinNotification:(const char *)notification;	// 0x3ff68d
+ (int)notificationTokenForDarwinNotification:(const char *)darwinNotification;	// 0x3ff6d9
+ (BOOL)registerDarwinNotification:(const char *)notification sendsNotificationNamed:(id)named;	// 0x3ff625
+ (void)setSingleton:(id)singleton;	// 0x3ff479
+ (id)singleton;	// 0x3ff469
- (id)init;	// 0x3ff49d
- (void).cxx_destruct;	// 0x3ff771
- (BOOL)_deregisterDarwinNotification:(const char *)notification;	// 0x3ffad9
- (BOOL)_registerDarwinNotification:(const char *)notification sendsNotificationNamed:(id)named;	// 0x3ff785
- (id)_registrationForDarwinNotification:(const char *)darwinNotification;	// 0x3ffc1d
- (id)_registrationForToken:(int)token;	// 0x3ffc81
- (void)dealloc;	// 0x3ff509
@end

