/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import "GQDGraphic.h"
#import "GQDNameMappable.h"
#import "iWorkImport-Structs.h"

@class GQDTTableModel, GQDSStyle;

@interface GQDTTable : GQDGraphic <GQDNameMappable> {
	GQDTTableModel *mModel;	// 40 = 0x28
	GQDSStyle *mStyle;	// 44 = 0x2c
	BOOL mIsStreamed;	// 48 = 0x30
}
@property(retain) id model;	// G=0x34bf6865; S=0x34bf6875; converted property
@property(retain) id tableStyle;	// G=0x34bf68b1; S=0x34bf68c1; converted property
+ (const StateSpec *)stateForReading;	// 0x34bf67f5
- (void)dealloc;	// 0x34bf6801
- (id)defaultVectorStyleForVectorType:(int)vectorType;	// 0x34bf690d
- (BOOL)isStreamed;	// 0x34bf68fd
// converted property getter: - (id)model;	// 0x34bf6865
// converted property setter: - (void)setModel:(id)model;	// 0x34bf6875
// converted property setter: - (void)setTableStyle:(id)style;	// 0x34bf68c1
// converted property getter: - (id)tableStyle;	// 0x34bf68b1
- (int)walkTableWithGenerator:(Class)generator state:(id)state;	// 0x34bf6975
@end

