/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

#import <NSObject.h> // Unknown library

@class NSMutableSet, NSSet, GEOTileKeyList, GEOTileKeyMap;
@protocol _GEORegionalResourcesRequestDelegate;

__attribute__((visibility("hidden")))
@interface _GEORegionalResourcesRequest : NSObject {
	GEOTileKeyList *_list;	// 4 = 0x4
	GEOTileKeyList *_keysWithResources;	// 8 = 0x8
	GEOTileKeyList *_completedList;	// 12 = 0xc
	GEOTileKeyMap *_keysToResourceIdentifiers;	// 16 = 0x10
	NSMutableSet *_resourceIdentifiers;	// 20 = 0x14
	id<_GEORegionalResourcesRequestDelegate> _delegate;	// 24 = 0x18
}
@property(assign, nonatomic) id<_GEORegionalResourcesRequestDelegate> delegate;	// G=0x34582005; S=0x34582015; @synthesize=_delegate
@property(readonly, assign, nonatomic) NSSet *resourceIdentifiers;	// G=0x34582035; @synthesize=_resourceIdentifiers
@property(readonly, assign, nonatomic) GEOTileKeyList *tileKeys;	// G=0x34582025; @synthesize=_list
- (id)initWithTileKeys:(id)tileKeys;	// 0x34581a55
- (void)addCompletedResourceIdentifier:(id)identifier;	// 0x34581dd9
- (void)addResourceIdentifiers:(id)identifiers forTileKeys:(id)tileKeys;	// 0x34581b4d
- (void)dealloc;	// 0x34581aad
// declared property getter: - (id)delegate;	// 0x34582005
// declared property getter: - (id)resourceIdentifiers;	// 0x34582035
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x34582015
// declared property getter: - (id)tileKeys;	// 0x34582025
@end

