/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

#import "GeoServices-Structs.h"
#import <NSObject.h> // Unknown library

@class NSLock, GEOTileDBMRU, NSMutableArray, NSMutableSet, NSString;
@protocol OS_dispatch_queue;

@interface GEOTileDBWriter : NSObject {
	NSString *_path;	// 4 = 0x4
	sqlite3 *_db;	// 8 = 0x8
	sqlite3_stmt *_versionQuery;	// 12 = 0xc
	sqlite3_stmt *_versionInsert;	// 16 = 0x10
	sqlite3_stmt *_editionQuery;	// 20 = 0x14
	sqlite3_stmt *_editionDelete;	// 24 = 0x18
	sqlite3_stmt *_editionUpdate;	// 28 = 0x1c
	sqlite3_stmt *_tileInsert;	// 32 = 0x20
	sqlite3_stmt *_tileDelete;	// 36 = 0x24
	sqlite3_stmt *_tileSize;	// 40 = 0x28
	sqlite3_stmt *_sizeQuery;	// 44 = 0x2c
	long long _lastRowID;	// 48 = 0x30
	unsigned long long _databaseSize;	// 56 = 0x38
	unsigned long long _maxDatabaseSize;	// 64 = 0x40
	BOOL _closed;	// 72 = 0x48
	BOOL _defunct;	// 73 = 0x49
	NSMutableArray *_writeList;	// 76 = 0x4c
	NSMutableSet *_uncommitedWriteSet;	// 80 = 0x50
	unsigned _pendingWriteBytes;	// 84 = 0x54
	NSLock *_writeListLock;	// 88 = 0x58
	NSObject<OS_dispatch_queue> *_writeQueue;	// 92 = 0x5c
	void *_editionMap;	// 96 = 0x60
	long long _evictionRowsThreshold;	// 100 = 0x64
	GEOTileDBMRU *_tileDBMRU;	// 108 = 0x6c
	XXStruct_nbUehC *_expirationRecords;	// 112 = 0x70
	unsigned _expirationRecordCount;	// 116 = 0x74
	BOOL _preloading;	// 120 = 0x78
	double _lastCheckedGeneralExpiration;	// 124 = 0x7c
}
@property(assign) BOOL closed;	// G=0x34518521; S=0x34518439; 
@property(readonly, assign, nonatomic) unsigned long long databaseSize;	// G=0x3451af09; @synthesize=_databaseSize
@property(assign, nonatomic) unsigned long long maxDatabaseSize;	// G=0x3451af21; S=0x3451af39; @synthesize=_maxDatabaseSize
@property(readonly, assign, nonatomic) NSString *path;	// G=0x3451aed9; @synthesize=_path
@property(retain, nonatomic) GEOTileDBMRU *tileDBMRU;	// G=0x3451aee9; S=0x3451aef9; @synthesize=_tileDBMRU
- (id)initWithPath:(id)path;	// 0x34517089
- (void)_assertDatabaseSize;	// 0x34517f5d
- (void)_closeDB;	// 0x345179ad
- (void)_createTables;	// 0x34517ab9
- (unsigned long long)_dbFileSize;	// 0x345193a5
- (void)_deleteKey:(GEOTileKey)key;	// 0x3451a5d9
- (void)_deviceLocked;	// 0x34517369
- (void)_editionUpdate:(id)update;	// 0x34517415
- (void)_evict;	// 0x345196ad
- (void)_localeChanged:(id)changed;	// 0x345172d9
- (void)_openDBForceRecreate:(BOOL)recreate;	// 0x34517f61
- (void)_openIfNecessary;	// 0x34518411
- (void)_performWrites:(BOOL)writes;	// 0x34519d25
- (void)_prepareStatements;	// 0x34517b2d
- (void)_printDBStatus:(const char *)status;	// 0x34518531
- (BOOL)_readEditions;	// 0x34517e45
- (void)_shrinkToUnderSize:(unsigned long long)underSize vacuum:(BOOL)vacuum;	// 0x345185d1
- (BOOL)_tileSetExpires:(unsigned)expires;	// 0x345196e1
- (void)_updateEdition:(unsigned)edition forTileset:(unsigned)tileset provider:(unsigned)provider;	// 0x34519a05
- (void)_updateSize;	// 0x34517f15
- (void)_writeEntry:(id)entry;	// 0x3451972d
- (void)_writeVersion;	// 0x34517dc5
- (void)addTile:(id)tile forKey:(GEOTileKey *)key edition:(unsigned)edition tileSet:(unsigned)set;	// 0x3451a119
- (void)beginPreloadSessionOfSize:(unsigned long long)size;	// 0x3451ac15
// declared property getter: - (BOOL)closed;	// 0x34518521
// declared property getter: - (unsigned long long)databaseSize;	// 0x3451af09
- (void)dealloc;	// 0x3451adb5
- (void)deleteTile:(const GEOTileKey *)tile;	// 0x3451a86d
- (void)endPreloadSession;	// 0x3451ad39
- (void)flushPendingWrites;	// 0x3451791d
// declared property getter: - (unsigned long long)maxDatabaseSize;	// 0x3451af21
// declared property getter: - (id)path;	// 0x3451aed9
- (id)pendingWriteForKey:(GEOTileKey *)key;	// 0x3451a2b9
- (void)pendingWritesForKeys:(id)keys handler:(id)handler;	// 0x3451a42d
// declared property setter: - (void)setClosed:(BOOL)closed;	// 0x34518439
- (void)setExpirationRecords:(XXStruct_nbUehC *)records count:(unsigned)count;	// 0x3451ab59
// declared property setter: - (void)setMaxDatabaseSize:(unsigned long long)size;	// 0x3451af39
// declared property setter: - (void)setTileDBMRU:(id)dbmru;	// 0x3451aef9
- (void)shrinkToSize:(unsigned long long)size finished:(id)finished;	// 0x345193fd
// declared property getter: - (id)tileDBMRU;	// 0x3451aee9
@end

