/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BRControl.h"

@class ATVCarouselView;
@protocol ATVCarouselViewUIDelegate;

__attribute__((visibility("hidden")))
@interface ATVPhotoDetailView : BRControl {
	ATVCarouselView *_carousel;	// 80 = 0x50
	BRControl *_metadataView;	// 84 = 0x54
	int _carouselType;	// 88 = 0x58
	id<ATVCarouselViewUIDelegate> __carouselUIDelegate;	// 92 = 0x5c
	id _transitionEndHandler;	// 96 = 0x60
	double _typeChangeAnimationDuration;	// 100 = 0x64
	int __carouselUIDelegateType;	// 108 = 0x6c
	id _transitionBeginHandler;	// 112 = 0x70
	id _carouselUIViewDelegateHandler;	// 116 = 0x74
	BOOL _isTransitioning;	// 120 = 0x78
}
@property(retain, nonatomic) id<ATVCarouselViewUIDelegate> _carouselUIDelegate;	// G=0x10061d; S=0x10062d; @synthesize=__carouselUIDelegate
@property(assign, nonatomic) int _carouselUIDelegateType;	// G=0x10068d; S=0x10069d; @synthesize=__carouselUIDelegateType
@property(retain, nonatomic) ATVCarouselView *carousel;	// G=0x1005dd; S=0x1005ed; @synthesize=_carousel
@property(assign, nonatomic) int carouselType;	// G=0x10060d; S=0xffd35; @synthesize=_carouselType
@property(copy, nonatomic) id carouselUIViewDelegateHandler;	// G=0x1006d1; S=0x1006e5; @synthesize=_carouselUIViewDelegateHandler
@property(assign, nonatomic) BOOL isTransitioning;	// G=0x1006f5; S=0x100705; @synthesize=_isTransitioning
@property(retain, nonatomic) BRControl *metadataView;	// G=0x1005fd; S=0xffc99; @synthesize=_metadataView
@property(copy, nonatomic) id transitionBeginHandler;	// G=0x1006ad; S=0x1006c1; @synthesize=_transitionBeginHandler
@property(copy, nonatomic) id transitionEndHandler;	// G=0x10063d; S=0x100651; @synthesize=_transitionEndHandler
@property(assign, nonatomic) double typeChangeAnimationDuration;	// G=0x100661; S=0x100679; @synthesize=_typeChangeAnimationDuration
- (id)init;	// 0xffae9
// declared property getter: - (id)_carouselUIDelegate;	// 0x10061d
// declared property getter: - (int)_carouselUIDelegateType;	// 0x10068d
- (void)animationDidStop:(id)animation finished:(BOOL)finished;	// 0x100525
- (BOOL)brEventAction:(id)action;	// 0x100445
// declared property getter: - (id)carousel;	// 0x1005dd
// declared property getter: - (int)carouselType;	// 0x10060d
// declared property getter: - (id)carouselUIViewDelegateHandler;	// 0x1006d1
- (void)dealloc;	// 0xffbe5
// declared property getter: - (BOOL)isTransitioning;	// 0x1006f5
- (void)layoutSubcontrols;	// 0xffda9
// declared property getter: - (id)metadataView;	// 0x1005fd
// declared property setter: - (void)setCarousel:(id)carousel;	// 0x1005ed
// declared property setter: - (void)setCarouselType:(int)type;	// 0xffd35
// declared property setter: - (void)setCarouselUIViewDelegateHandler:(id)handler;	// 0x1006e5
// declared property setter: - (void)setIsTransitioning:(BOOL)transitioning;	// 0x100705
// declared property setter: - (void)setMetadataView:(id)view;	// 0xffc99
// declared property setter: - (void)setTransitionBeginHandler:(id)handler;	// 0x1006c1
// declared property setter: - (void)setTransitionEndHandler:(id)handler;	// 0x100651
// declared property setter: - (void)setTypeChangeAnimationDuration:(double)duration;	// 0x100679
// declared property setter: - (void)set_carouselUIDelegate:(id)delegate;	// 0x10062d
// declared property setter: - (void)set_carouselUIDelegateType:(int)type;	// 0x10069d
// declared property getter: - (id)transitionBeginHandler;	// 0x1006ad
// declared property getter: - (id)transitionEndHandler;	// 0x10063d
// declared property getter: - (double)typeChangeAnimationDuration;	// 0x100661
@end

