/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BRControl.h"
#import "AppleTV-Structs.h"

@class BRImageControl, BRTextControl, NSDictionary, BRAsyncImageControl, BRTableView;

__attribute__((visibility("hidden")))
@interface ATVThunderLineScoreView : BRControl {
	NSDictionary *_data;	// 80 = 0x50
	BRTextControl *_homeTeamName;	// 84 = 0x54
	BRTextControl *_awayTeamName;	// 88 = 0x58
	BRTextControl *_homeTeamScore;	// 92 = 0x5c
	BRTextControl *_awayTeamScore;	// 96 = 0x60
	BRAsyncImageControl *_homeTeamLogo;	// 100 = 0x64
	BRAsyncImageControl *_awayTeamLogo;	// 104 = 0x68
	BRTextControl *_gamePeriod;	// 108 = 0x6c
	BRTextControl *_gameTime;	// 112 = 0x70
	BRTextControl *_gameState;	// 116 = 0x74
	BRImageControl *_lineScoreBG;	// 120 = 0x78
	BRTableView *_lineScoreTable;	// 124 = 0x7c
}
- (id)initWithDictionary:(id)dictionary;	// 0x22e8a5
- (id)_gamePeriodAttributes;	// 0x22fbd5
- (id)_gameStateAttributes;	// 0x22fc1d
- (id)_gameTimeAttributes;	// 0x22fbf9
- (id)_scoreAttributes;	// 0x22fbb1
- (id)_tableCellAttributes;	// 0x22fc65
- (id)_tableHeaderAttributes;	// 0x22fc41
- (id)_teamNameAttributes;	// 0x22fb8d
- (id)accessibilityLabel;	// 0x22faad
- (void)dealloc;	// 0x22eea9
- (float)headerHeightForTableView:(id)tableView;	// 0x22faa1
- (void)layoutSubcontrols;	// 0x22efed
- (long)numberOfColumnsInTableView:(id)tableView;	// 0x22f6bd
- (long)numberOfHeaderColumnsInTableView:(id)tableView;	// 0x22f6c1
- (long)numberOfRowsInTableView:(id)tableView;	// 0x22f6b9
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x22efd5
- (id)tableView:(id)view headerForColumn:(long)column;	// 0x22f879
- (float)tableView:(id)view heightForRow:(long)row;	// 0x22fa95
- (id)tableView:(id)view itemForRow:(long)row inColumn:(long)column;	// 0x22f6c5
- (float)tableView:(id)view widthForColumn:(long)column;	// 0x22fa3d
- (float)tableView:(id)view widthForHeaderColumn:(long)headerColumn;	// 0x22fa85
@end

