/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/UIAccessibility.framework/UIAccessibility
 */

#import <NSBundle.h> // Unknown library


@interface NSBundle (UIAccessibilityLoader)
+ (id)accessibilityBundleWithLastPathComponent:(id)lastPathComponent;	// 0x360cbed9
- (void)_accessibilityInitializeContainerLogic;	// 0x360cbfb5
- (id)accessibilityBundlePath;	// 0x360cbf39
@end

