/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

#import <NSObject.h> // Unknown library


@interface AFPreferences : NSObject {
	BOOL _shouldSynchronizePrivateDomain;	// 4 = 0x4
}
@property(assign) BOOL assistantIsEnabled;	// G=0x3461c0bd; S=0x3461c181; converted property
@property(assign) BOOL debugButtonIsEnabled;	// G=0x3461c3b1; S=0x3461c3f1; converted property
@property(assign) BOOL dictationIsEnabled;	// G=0x3461c0c9; S=0x3461c1e5; converted property
@property(assign) BOOL disableAssistantWhilePasscodeLocked;	// G=0x3461c45d; S=0x3461c4c9; converted property
@property(assign) BOOL fileLoggingIsEnabled;	// G=0x3461c9e1; S=0x3461c95d; converted property
@property(assign) int handsFreeMode;	// G=0x3461c43d; S=0x3461c441; converted property
+ (id)sharedPreferences;	// 0x3461be55
- (id)init;	// 0x3461bf79
- (void)_preferencesDidChangeExternally;	// 0x3461becd
- (void)_setAssistantIsEnabledLocal:(BOOL)local;	// 0x3461c101
- (void)_setDictationIsEnabledLocal:(BOOL)local;	// 0x3461c141
- (void)_synchronizeSessionContext;	// 0x3461c089
// converted property getter: - (BOOL)assistantIsEnabled;	// 0x3461c0bd
- (id)birthCertificateDataForLanguageCode:(id)languageCode;	// 0x3461c691
- (void)dealloc;	// 0x3461bff1
// converted property getter: - (BOOL)debugButtonIsEnabled;	// 0x3461c3b1
// converted property getter: - (BOOL)dictationIsEnabled;	// 0x3461c0c9
- (void)didShowReadyForLanguageCode:(id)languageCode;	// 0x3461c575
// converted property getter: - (BOOL)disableAssistantWhilePasscodeLocked;	// 0x3461c45d
// converted property getter: - (BOOL)fileLoggingIsEnabled;	// 0x3461c9e1
// converted property getter: - (int)handsFreeMode;	// 0x3461c43d
- (id)languagesMissingBirthCertificates;	// 0x3461c841
// converted property setter: - (void)setAssistantIsEnabled:(BOOL)enabled;	// 0x3461c181
- (void)setBirthCertificateData:(id)data forLanguageCode:(id)languageCode;	// 0x3461c7bd
// converted property setter: - (void)setDebugButtonIsEnabled:(BOOL)enabled;	// 0x3461c3f1
// converted property setter: - (void)setDictationIsEnabled:(BOOL)enabled;	// 0x3461c1e5
// converted property setter: - (void)setDisableAssistantWhilePasscodeLocked:(BOOL)locked;	// 0x3461c4c9
// converted property setter: - (void)setFileLoggingIsEnabled:(BOOL)enabled;	// 0x3461c95d
// converted property setter: - (void)setHandsFreeMode:(int)mode;	// 0x3461c441
- (void)setShouldShowReadyForLanguageCode:(id)showReadyForLanguageCode;	// 0x3461c605
- (void)setValue:(id)value forSessionContextKey:(id)sessionContextKey;	// 0x3461c2a5
- (BOOL)shouldShowReadyForLanguageCode:(id)languageCode;	// 0x3461c539
- (void)synchronize;	// 0x3461c035
- (id)valueForSessionContextPreferenceKey:(id)sessionContextPreferenceKey;	// 0x3461c249
- (id)whitelistedLanguages;	// 0x3461c625
@end

