/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <UIGestureRecognizer.h> // Unknown library
#import "MediaPlayer-Structs.h"

@class UITouch, NSTimer;

@interface MPTapGestureRecognizer : UIGestureRecognizer {
	unsigned _lastTapCount;	// 56 = 0x38
	CGPoint _tapLocation;	// 60 = 0x3c
	UITouch *_trackingTouch;	// 68 = 0x44
	NSTimer *_tapHandleTimer;	// 72 = 0x48
}
@property(assign) unsigned tapCount;	// G=0x36eff89d; S=0x36eff8b1; @synthesize=_lastTapCount
- (id)initWithTarget:(id)target action:(SEL)action;	// 0x36eff335
- (void)_delayedHandleTaps:(id)taps;	// 0x36eff735
- (void)_resetTapTimer;	// 0x36eff465
- (void)_setTapTimerWithDuration:(double)duration;	// 0x36eff37d
- (void)dealloc;	// 0x36eff839
- (CGPoint)locationInView:(id)view;	// 0x36eff7b1
- (void)reset;	// 0x36eff7c9
// declared property setter: - (void)setTapCount:(unsigned)count;	// 0x36eff8b1
// declared property getter: - (unsigned)tapCount;	// 0x36eff89d
- (void)touchesBegan:(id)began withEvent:(id)event;	// 0x36eff4a1
- (void)touchesCancelled:(id)cancelled withEvent:(id)event;	// 0x36eff6d9
- (void)touchesEnded:(id)ended withEvent:(id)event;	// 0x36eff5a1
@end

