/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <NSObject.h> // Unknown library

@class NSString, NSMutableArray;

@interface UIMovieClosedCaptionData : NSObject {
	NSString *_language;	// 4 = 0x4
	NSMutableArray *_data;	// 8 = 0x8
}
@property(retain, nonatomic) NSString *language;	// G=0x36f6153d; S=0x36f6154d; @synthesize=_language
- (void)addCaptionText:(id)text startTime:(double)time endTime:(double)time3;	// 0x36f61251
- (void)dealloc;	// 0x36f611e9
- (id)description;	// 0x36f614e1
// declared property getter: - (id)language;	// 0x36f6153d
// declared property setter: - (void)setLanguage:(id)language;	// 0x36f6154d
- (id)timeMarkers;	// 0x36f614d1
@end

