/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/XPCObjects.framework/XPCObjects
 */

#import "NSSecureCoding.h"
#import </libobjc.A.h>


@interface XPCMachSendRight : NSObject <NSSecureCoding> {
	unsigned _sendRight;	// 4 = 0x4
}
@property(readonly, assign) unsigned sendRight;	// G=0x33a97a55; converted property
+ (BOOL)supportsSecureCoding;	// 0x33a97a65
+ (id)wrapSendRight:(unsigned)right;	// 0x33a97959
- (id)initWithCoder:(id)coder;	// 0x33a97bad
- (void)dealloc;	// 0x33a97a05
- (void)encodeWithCoder:(id)coder;	// 0x33a97a69
// converted property getter: - (unsigned)sendRight;	// 0x33a97a55
@end

