/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "AceObject.h"
#import "SAAceSerializable.h"

@class NSString;
@protocol SASupportCondition;

@interface SAConstraintSupport : AceObject <SAAceSerializable> {
}
@property(retain, nonatomic) id<SASupportCondition> condition;	// G=0x36630b8d; S=0x36630be1; 
@property(copy, nonatomic) NSString *property;	// G=0x36630c1d; S=0x36630c39; 
+ (id)constraintSupport;	// 0x36630afd
+ (id)constraintSupportWithDictionary:(id)dictionary context:(id)context;	// 0x36630b41
// declared property getter: - (id)condition;	// 0x36630b8d
- (id)encodedClassName;	// 0x36630af1
- (id)groupIdentifier;	// 0x36630ae1
// declared property getter: - (id)property;	// 0x36630c1d
// declared property setter: - (void)setCondition:(id)condition;	// 0x36630be1
// declared property setter: - (void)setProperty:(id)property;	// 0x36630c39
@end

