/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

#import "CITile2Filter.h"
#import "CoreImage-Structs.h"


__attribute__((visibility("hidden")))
@interface CIFourfoldTranslatedTile : CITile2Filter {
}
+ (id)customAttributes;	// 0x3156d759
- (id)_kernel_name;	// 0x3156d78d
- (id)_kernel_source;	// 0x3156d799
- (id)outputImage;	// 0x3156d7a5
@end

