/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import "AVOutputSettings.h"

@class NSDictionary;

@interface AVAudioOutputSettings : AVOutputSettings {
}
@property(readonly, assign, nonatomic) NSDictionary *audioSettingsDictionary;	// G=0x2c3083f5; 
+ (id)_audioOutputSettingsWithAudioSettingsDictionary:(id)audioSettingsDictionary exceptionReason:(id *)reason;	// 0x2c307f71
+ (id)_outputSettingsWithOutputSettingsDictionary:(id)outputSettingsDictionary exceptionReason:(id *)reason;	// 0x2c307e79
+ (id)audioConverterPropertiesForAudioSettingsDictionary:(id)audioSettingsDictionary;	// 0x2c308001
+ (id)audioOutputSettingsWithAudioSettingsDictionary:(id)audioSettingsDictionary;	// 0x2c307e89
+ (id)audioOutputSettingsWithTrustedAudioSettingsDictionary:(id)trustedAudioSettingsDictionary;	// 0x2c307f01
+ (id)defaultAudioOutputSettings;	// 0x2c307fb5
+ (id)registeredOutputSettingsClasses;	// 0x2c307e35
- (id)initWithAudioSettingsDictionary:(id)audioSettingsDictionary exceptionReason:(id *)reason;	// 0x2c3083b9
// declared property getter: - (id)audioSettingsDictionary;	// 0x2c3083f5
- (id)compatibleMediaTypes;	// 0x2c3083c9
- (BOOL)validateUsingOutputSettingsValidator:(id)validator reason:(id *)reason;	// 0x2c308405
@end

