/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreControlPopulator.h"


__attribute__((visibility("hidden")))
@interface ATVMusicStoreActionControlPopulator : ATVMusicStoreControlPopulator {
}
+ (BOOL)canHandleData:(id)data;	// 0x32f58fc1
- (id)buttonForData:(id)data;	// 0x32f59025
- (id)listRowForData:(id)data;	// 0x32f594ed
@end

