/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <UIKit/UIViewController.h>

@class MPMoviePlayerController;

@interface MPMoviePlayerViewController : UIViewController {
	id _internal;	// 304 = 0x130
}
@property(readonly, assign, nonatomic) MPMoviePlayerController *moviePlayer;	// G=0x2e29d759; 
- (id)init;	// 0x2e29d471
- (id)initWithAsset:(id)asset;	// 0x2e29d569
- (id)initWithContentURL:(id)contentURL;	// 0x2e29d5cd
- (void).cxx_destruct;	// 0x2e29e2c5
- (BOOL)_canReloadView;	// 0x2e29df49
- (void)_moviePlayerViewController_applicationDidEnterBackgroundNotification:(id)_moviePlayerViewController_application;	// 0x2e29df51
- (void)_moviePlayerViewController_playbackDidFinishNotification:(id)_moviePlayerViewController_playback;	// 0x2e29dfd9
- (void)_restoreStatusBarAnimated:(BOOL)animated;	// 0x2e29e0b9
- (BOOL)_shouldUseFullScreenLayoutInWindow:(id)window parentViewController:(id)controller;	// 0x2e29df4d
- (BOOL)canBecomeFirstResponder;	// 0x2e29d8cd
- (void)dealloc;	// 0x2e29d631
- (void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;	// 0x2e29db41
- (void)loadView;	// 0x2e29d9a5
// declared property getter: - (id)moviePlayer;	// 0x2e29d759
- (void)remoteControlReceivedWithEvent:(id)event;	// 0x2e29d8d1
- (BOOL)shouldAutorotate;	// 0x2e29dad9
- (unsigned)supportedInterfaceOrientations;	// 0x2e29dadd
- (void)viewDidAppear:(BOOL)view;	// 0x2e29dd49
- (void)viewDidDisappear:(BOOL)view;	// 0x2e29de71
- (void)viewWillAppear:(BOOL)view;	// 0x2e29dba5
- (void)viewWillDisappear:(BOOL)view;	// 0x2e29ddf9
- (void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;	// 0x2e29dae1
@end

