/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSURL;

@interface SAFmfVisibilityStateSet : SABaseClientBoundCommand {
}
@property(copy, nonatomic) NSURL *targetAppId;	// G=0x355b1b95; S=0x355b1c11; 
@property(assign, nonatomic) BOOL visible;	// G=0x355b1c71; S=0x355b1ce9; 
+ (id)visibilityStateSet;	// 0x355b1b05
+ (id)visibilityStateSetWithDictionary:(id)dictionary context:(id)context;	// 0x355b1b49
- (id)encodedClassName;	// 0x355b1af9
- (id)groupIdentifier;	// 0x355b1ae9
- (BOOL)requiresResponse;	// 0x355b1d2d
// declared property setter: - (void)setTargetAppId:(id)anId;	// 0x355b1c11
// declared property setter: - (void)setVisible:(BOOL)visible;	// 0x355b1ce9
// declared property getter: - (id)targetAppId;	// 0x355b1b95
// declared property getter: - (BOOL)visible;	// 0x355b1c71
@end

