/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GMM.framework/GMM
 */

#import <PBCodable.h> // Unknown library

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface GMMDirectionsIconResponse : PBCodable {
	BOOL _hasIconVersion;	// 4 = 0x4
	int _iconVersion;	// 8 = 0x8
	NSMutableArray *_iconDefinitions;	// 12 = 0xc
}
@property(assign, nonatomic) BOOL hasIconVersion;	// G=0x31fa65ad; S=0x31fa65bd; @synthesize=_hasIconVersion
@property(retain, nonatomic) NSMutableArray *iconDefinitions;	// G=0x31fa65cd; S=0x31fa65dd; @synthesize=_iconDefinitions
@property(assign, nonatomic) int iconVersion;	// G=0x31fa6155; S=0x31fa6179; @synthesize=_iconVersion
- (void)addIconDefinition:(id)definition;	// 0x31fa619d
- (void)dealloc;	// 0x31fa6111
- (id)description;	// 0x31fa6241
- (id)dictionaryRepresentation;	// 0x31fa62b1
// declared property getter: - (BOOL)hasIconVersion;	// 0x31fa65ad
- (id)iconDefinitionAtIndex:(unsigned)index;	// 0x31fa6221
// declared property getter: - (id)iconDefinitions;	// 0x31fa65cd
- (unsigned)iconDefinitionsCount;	// 0x31fa6201
// declared property getter: - (int)iconVersion;	// 0x31fa6155
- (BOOL)readFrom:(id)from;	// 0x31fa635d
// declared property setter: - (void)setHasIconVersion:(BOOL)version;	// 0x31fa65bd
// declared property setter: - (void)setIconDefinitions:(id)definitions;	// 0x31fa65dd
// declared property setter: - (void)setIconVersion:(int)version;	// 0x31fa6179
- (void)writeTo:(id)to;	// 0x31fa64a5
@end

