/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ImageCapture.framework/ImageCapture
 */

#import "DeviceManager.h"


@interface MSCameraDeviceManager : DeviceManager {
}
- (void)closeDeviceImp:(id)imp;	// 0x30d7bca5
- (void)closeSessionImp:(id)imp;	// 0x30d7c051
- (void)deleteFileImp:(id)imp;	// 0x30d7c6b5
- (void)downloadFileImp:(id)imp;	// 0x30d7c8d9
- (void)ejectImp:(id)imp;	// 0x30d7cdc5
- (void)getMetadataOfFileImp:(id)fileImp;	// 0x30d7c4f1
- (void)getThumbnailOfFileImp:(id)fileImp;	// 0x30d7c309
- (void)openDeviceImp:(id)imp;	// 0x30d7b941
- (void)openSessionImp:(id)imp;	// 0x30d7be7d
- (void)syncClockImp:(id)imp;	// 0x30d7c1ed
@end

