/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIScrollViewDelegate.h"
#import "NSCoding.h"
#import "UIView.h"

@class NSURLRequest, UIScrollView, UIWebViewInternal;
@protocol UIWebViewDelegate;

@interface UIWebView : UIView <NSCoding, UIScrollViewDelegate> {
	UIWebViewInternal *_internal;	// 84 = 0x54
}
@property(assign, nonatomic) BOOL allowsInlineMediaPlayback;	// G=0x32ef5325; S=0x32ef52f9; 
@property(readonly, assign, nonatomic, getter=canGoBack) BOOL canGoBack;	// G=0x32ef576d; 
@property(readonly, assign, nonatomic, getter=canGoForward) BOOL canGoForward;	// G=0x32ef57b5; 
@property(assign, nonatomic) unsigned dataDetectorTypes;	// G=0x32ef52cd; S=0x32ef52a1; 
@property(assign, nonatomic) id<UIWebViewDelegate> delegate;	// G=0x32ef54f1; S=0x32ef54d1; 
@property(assign, nonatomic) BOOL detectsPhoneNumbers;	// G=0x32ef526d; S=0x32ef5241; 
@property(assign, nonatomic) BOOL keyboardDisplayRequiresUserAction;	// G=0x32ef3821; S=0x32ef3861; 
@property(readonly, assign, nonatomic, getter=isLoading) BOOL loading;	// G=0x32ef54ad; 
@property(assign, nonatomic) BOOL mediaPlaybackAllowsAirPlay;	// G=0x32ef53e5; S=0x32ef53b9; 
@property(assign, nonatomic) BOOL mediaPlaybackRequiresUserAction;	// G=0x32ef5385; S=0x32ef5359; 
@property(readonly, assign, nonatomic) NSURLRequest *request;	// G=0x32ef55c5; 
@property(assign, nonatomic) BOOL scalesPageToFit;	// G=0x32ef5489; S=0x32ef5419; 
@property(readonly, assign, nonatomic) UIScrollView *scrollView;	// G=0x32ef5511; 
@property(assign, nonatomic) BOOL suppressesIncrementalRendering;	// G=0x32ef57fd; S=0x32ef5831; 
+ (void)_fixPathsForSandboxDirectoryChange;	// 0x32ef3f19
+ (id)_relativePathFromAbsolutePath:(id)absolutePath removingPathComponents:(unsigned)components;	// 0x32ef3e85
+ (void)_updatePersistentStoragePaths;	// 0x32ef40b9
- (id)initWithCoder:(id)coder;	// 0x32ef4d89
- (id)initWithFrame:(CGRect)frame;	// 0x32ef4d31
- (void)_addShortcut:(id)shortcut;	// 0x32ef83e9
- (BOOL)_alwaysDispatchesScrollEvents;	// 0x32ef8151
- (BOOL)_appliesExclusiveTouchToSubviewTree;	// 0x32ef6029
- (unsigned)_audioSessionCategoryOverride;	// 0x32ef81b1
- (void)_beginRotation;	// 0x32ef5939
- (id)_browserView;	// 0x32ef7c81
- (void)_define:(id)define;	// 0x32ef83bd
- (void)_didCompleteScrolling;	// 0x32ef6399
- (void)_didRotate:(id)rotate;	// 0x32ef389d
- (id)_documentView;	// 0x32ef7ca1
- (void)_finishRotation;	// 0x32ef599d
- (void)_frameOrBoundsChanged;	// 0x32ef5a8d
- (float)_gapBetweenPages;	// 0x32ef803d
- (id)_initWithFrame:(CGRect)frame enableReachability:(BOOL)reachability;	// 0x32ef4cd9
- (id)_initWithWebView:(id)webView;	// 0x32ef7c01
- (id)_makeAlertView;	// 0x32ef7129
- (unsigned)_pageCount;	// 0x32ef80d9
- (float)_pageLength;	// 0x32ef7fa1
- (BOOL)_paginationBehavesLikeColumns;	// 0x32ef7f09
- (int)_paginationMode;	// 0x32ef7dfd
- (id)_pdfViewHandler;	// 0x32ef7ce1
- (void)_populateArchivedSubviews:(id)subviews;	// 0x32ef4e7d
- (Class)_printFormatterClass;	// 0x32ff6a89
- (void)_reportError:(id)error;	// 0x32ef6491
- (void)_rescaleDocument;	// 0x32ef5a25
- (id)_scrollView;	// 0x32ef7cc1
- (void)_setAlwaysDispatchesScrollEvents:(BOOL)events;	// 0x32ef8125
- (void)_setAudioSessionCategoryOverride:(unsigned)override;	// 0x32ef8185
- (void)_setDrawInWebThread:(BOOL)webThread;	// 0x32ef7da5
- (void)_setDrawsCheckeredPattern:(BOOL)pattern;	// 0x32ef7d25
- (void)_setGapBetweenPages:(float)pages;	// 0x32ef8089
- (void)_setOverridesOrientationChangeEventHandling:(BOOL)handling;	// 0x32ef7d01
- (void)_setPageLength:(float)length;	// 0x32ef7fed
- (void)_setPaginationBehavesLikeColumns:(BOOL)columns;	// 0x32ef7f51
- (void)_setPaginationMode:(int)mode;	// 0x32ef7e61
- (void)_setRichTextReaderViewportSettings;	// 0x32ef3a55
- (void)_setScalesPageToFitViewportSettings;	// 0x32ef3919
- (void)_setWebSelectionEnabled:(BOOL)enabled;	// 0x32ef7d81
- (void)_updateCheckeredPattern;	// 0x32ef585d
- (void)_updateOpaqueAndBackgroundColor;	// 0x32ef5dc9
- (void)_updateRequest;	// 0x32ef6a7d
- (void)_updateScrollerViewForInputView:(id)inputView;	// 0x32ef603d
- (void)_updateViewSettings;	// 0x32ef3b39
- (void)_webViewCommonInitWithWebView:(id)webView scalesPageToFit:(BOOL)fit shouldEnableReachability:(BOOL)reachability;	// 0x32ef4461
- (void)alertView:(id)view didDismissWithButtonIndex:(int)buttonIndex;	// 0x32ef709d
// declared property getter: - (BOOL)allowsInlineMediaPlayback;	// 0x32ef5325
// declared property getter: - (BOOL)canGoBack;	// 0x32ef576d
// declared property getter: - (BOOL)canGoForward;	// 0x32ef57b5
- (BOOL)canPerformAction:(SEL)action withSender:(id)sender;	// 0x32ef8301
- (void)configureWithSettings:(id)settings;	// 0x32ef81dd
- (void)copy:(id)copy;	// 0x32ef8339
- (CGImageRef)createSnapshotWithRect:(CGRect)rect;	// 0x32ef7b6d
// declared property getter: - (unsigned)dataDetectorTypes;	// 0x32ef52cd
- (void)dealloc;	// 0x32ef4fc9
- (void)decodeRestorableStateWithCoder:(id)coder;	// 0x32ef896d
// declared property getter: - (id)delegate;	// 0x32ef54f1
// declared property getter: - (BOOL)detectsPhoneNumbers;	// 0x32ef526d
- (void)encodeRestorableStateWithCoder:(id)coder;	// 0x32ef88a5
- (void)encodeWithCoder:(id)coder;	// 0x32ef4ee1
- (void)goBack;	// 0x32ef56dd
- (void)goForward;	// 0x32ef5725
- (BOOL)isElementAccessibilityExposedToInterfaceBuilder;	// 0x32f2730d
// declared property getter: - (BOOL)isLoading;	// 0x32ef54ad
// declared property getter: - (BOOL)keyboardDisplayRequiresUserAction;	// 0x32ef3821
- (void)loadData:(id)data MIMEType:(id)type textEncodingName:(id)name baseURL:(id)url;	// 0x32ef5591
- (void)loadHTMLString:(id)string baseURL:(id)url;	// 0x32ef555d
- (void)loadRequest:(id)request;	// 0x32ef5531
// declared property getter: - (BOOL)mediaPlaybackAllowsAirPlay;	// 0x32ef53e5
// declared property getter: - (BOOL)mediaPlaybackRequiresUserAction;	// 0x32ef5385
- (CGImageRef)newSnapshotWithRect:(CGRect)rect;	// 0x32ef7b91
- (void)reload;	// 0x32ef5609
// declared property getter: - (id)request;	// 0x32ef55c5
- (void)restoreStateFromHistoryItem:(id)historyItem forWebView:(id)webView;	// 0x32ef6195
- (void)saveStateToHistoryItem:(id)historyItem forWebView:(id)webView;	// 0x32ef6161
// declared property getter: - (BOOL)scalesPageToFit;	// 0x32ef5489
// declared property getter: - (id)scrollView;	// 0x32ef5511
- (void)scrollViewDidEndDecelerating:(id)scrollView;	// 0x32ef6411
- (void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;	// 0x32ef63f9
- (void)scrollViewDidEndZooming:(id)scrollView withView:(id)view atScale:(float)scale;	// 0x32ef62cd
- (void)scrollViewDidScrollToTop:(id)scrollView;	// 0x32ef6421
- (void)scrollViewDidZoom:(id)scrollView;	// 0x32ef6271
- (void)scrollViewWasRemoved:(id)removed;	// 0x32ef6431
- (void)scrollViewWillBeginDragging:(id)scrollView;	// 0x32ef633d
- (void)scrollViewWillBeginZooming:(id)scrollView withView:(id)view;	// 0x32ef6215
- (void)select:(id)select;	// 0x32ef8365
- (void)selectAll:(id)all;	// 0x32ef8391
// declared property setter: - (void)setAllowsInlineMediaPlayback:(BOOL)playback;	// 0x32ef52f9
- (void)setBackgroundColor:(id)color;	// 0x32ef5f95
- (void)setBounds:(CGRect)bounds;	// 0x32ef5d1d
// declared property setter: - (void)setDataDetectorTypes:(unsigned)types;	// 0x32ef52a1
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x32ef54d1
// declared property setter: - (void)setDetectsPhoneNumbers:(BOOL)numbers;	// 0x32ef5241
- (void)setFrame:(CGRect)frame;	// 0x32ef5c71
// declared property setter: - (void)setKeyboardDisplayRequiresUserAction:(BOOL)action;	// 0x32ef3861
// declared property setter: - (void)setMediaPlaybackAllowsAirPlay:(BOOL)play;	// 0x32ef53b9
// declared property setter: - (void)setMediaPlaybackRequiresUserAction:(BOOL)action;	// 0x32ef5359
- (void)setOpaque:(BOOL)opaque;	// 0x32ef5f11
// declared property setter: - (void)setScalesPageToFit:(BOOL)fit;	// 0x32ef5419
// declared property setter: - (void)setSuppressesIncrementalRendering:(BOOL)rendering;	// 0x32ef5831
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x32ef58fd
- (void)stopLoading;	// 0x32ef56ad
- (id)stringByEvaluatingJavaScriptFromString:(id)string;	// 0x32ef51d1
// declared property getter: - (BOOL)suppressesIncrementalRendering;	// 0x32ef57fd
- (void)view:(id)view didSetFrame:(CGRect)frame oldFrame:(CGRect)frame3;	// 0x32ef602d
- (id)viewForZoomingInScrollView:(id)scrollView;	// 0x32ef61c9
- (id)webView:(id)view connectionPropertiesForResource:(id)resource dataSource:(id)source;	// 0x32ef6cbd
- (void)webView:(id)view decidePolicyForGeolocationRequestFromOrigin:(id)origin frame:(id)frame listener:(id)listener;	// 0x32ef7615
- (void)webView:(id)view decidePolicyForMIMEType:(id)mimetype request:(id)request frame:(id)frame decisionListener:(id)listener;	// 0x32ef67b1
- (void)webView:(id)view decidePolicyForNavigationAction:(id)navigationAction request:(id)request frame:(id)frame decisionListener:(id)listener;	// 0x32ef656d
- (void)webView:(id)view decidePolicyForNewWindowAction:(id)newWindowAction request:(id)request newFrameName:(id)name decisionListener:(id)listener;	// 0x32ef6501
- (void)webView:(id)view didChangeLocationWithinPageForFrame:(id)frame;	// 0x32ef7ad9
- (void)webView:(id)view didClearWindowObject:(id)object forFrame:(id)frame;	// 0x32ef6d9d
- (void)webView:(id)view didCommitLoadForFrame:(id)frame;	// 0x32ef6bdd
- (void)webView:(id)view didFailLoadWithError:(id)error forFrame:(id)frame;	// 0x32ef6fd9
- (void)webView:(id)view didFailProvisionalLoadWithError:(id)error forFrame:(id)frame;	// 0x32ef6e1d
- (void)webView:(id)view didFinishLoadForFrame:(id)frame;	// 0x32ef6e71
- (void)webView:(id)view didFirstLayoutInFrame:(id)frame;	// 0x32ef702d
- (void)webView:(id)view didReceiveServerRedirectForProvisionalLoadForFrame:(id)frame;	// 0x32ef6e0d
- (void)webView:(id)view didReceiveTitle:(id)title forFrame:(id)frame;	// 0x32ef6c4d
- (void)webView:(id)view didStartProvisionalLoadForFrame:(id)frame;	// 0x32ef6b29
- (void)webView:(id)view exceededApplicationCacheOriginQuotaForSecurityOrigin:(id)securityOrigin totalSpaceNeeded:(unsigned)needed;	// 0x32ef6911
- (void)webView:(id)view frame:(id)frame exceededDatabaseQuotaForSecurityOrigin:(id)securityOrigin database:(id)database;	// 0x32ef6881
- (id)webView:(id)view identifierForInitialRequest:(id)initialRequest fromDataSource:(id)dataSource;	// 0x32ef76b1
- (void)webView:(id)view printFrameView:(id)view2;	// 0x32ef69a1
- (BOOL)webView:(id)view resource:(id)resource canAuthenticateAgainstProtectionSpace:(id)space forDataSource:(id)dataSource;	// 0x32ef79a1
- (void)webView:(id)view resource:(id)resource didCancelAuthenticationChallenge:(id)challenge fromDataSource:(id)dataSource;	// 0x32ef7931
- (void)webView:(id)view resource:(id)resource didFailLoadingWithError:(id)error fromDataSource:(id)dataSource;	// 0x32ef77d1
- (void)webView:(id)view resource:(id)resource didFinishLoadingFromDataSource:(id)dataSource;	// 0x32ef7761
- (void)webView:(id)view resource:(id)resource didReceiveAuthenticationChallenge:(id)challenge fromDataSource:(id)dataSource;	// 0x32ef7841
- (id)webView:(id)view resource:(id)resource willSendRequest:(id)request redirectResponse:(id)response fromDataSource:(id)dataSource;	// 0x32ef6d2d
- (void)webView:(id)view runJavaScriptAlertPanelWithMessage:(id)message initiatedByFrame:(id)frame;	// 0x32ef716d
- (BOOL)webView:(id)view runJavaScriptConfirmPanelWithMessage:(id)message initiatedByFrame:(id)frame;	// 0x32ef733d
- (id)webView:(id)view runJavaScriptTextInputPanelWithPrompt:(id)prompt defaultText:(id)text initiatedByFrame:(id)frame;	// 0x32ef7471
- (void)webView:(id)view unableToImplementPolicyWithError:(id)error frame:(id)frame;	// 0x32ef686d
- (void)webViewClose:(id)close;	// 0x32ef70bd
- (void)webViewMainFrameDidCommitLoad:(id)webViewMainFrame;	// 0x32ef6095
- (void)webViewMainFrameDidFailLoad:(id)webViewMainFrame withError:(id)error;	// 0x32ef6135
- (void)webViewMainFrameDidFinishLoad:(id)webViewMainFrame;	// 0x32ef60c1
- (void)webViewMainFrameDidFirstVisuallyNonEmptyLayoutInFrame:(id)webViewMainFrame;	// 0x32ef6069
- (void)webViewSupportedOrientationsUpdated:(id)updated;	// 0x32ef6a11
@end

