/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BRSingleton.h"

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface BRMenuSavedState : BRSingleton {
	NSMutableDictionary *_cachedMenuState;	// 4 = 0x4
	BOOL _enabled;	// 8 = 0x8
}
@property(assign) BOOL enabled;	// G=0x3b4619; S=0x3b4629; converted property
+ (void)clearSavedSelectionForOwnerKey:(id)ownerKey;	// 0x3b4379
+ (void)saveSelection:(id)selection atIndex:(id)index forOwnerKey:(id)ownerKey;	// 0x3b413d
+ (void)saveSelection:(id)selection atIndex:(id)index forOwnerKey:(id)ownerKey metadata:(id)metadata;	// 0x3b4161
+ (void)saveSelection:(id)selection atIndexPath:(id)indexPath forOwnerKey:(id)ownerKey metadata:(id)metadata;	// 0x3b426d
+ (id)selectionInfoForOwnerKey:(id)ownerKey;	// 0x3b43b9
+ (void)setSingleton:(id)singleton;	// 0x3b412d
+ (id)singleton;	// 0x3b411d
- (id)init;	// 0x3b43f1
- (void)dealloc;	// 0x3b446d
// converted property getter: - (BOOL)enabled;	// 0x3b4619
- (id)objectForKey:(id)key;	// 0x3b4535
- (void)purge;	// 0x3b45c5
- (void)removeObjectForKey:(id)key;	// 0x3b457d
// converted property setter: - (void)setEnabled:(BOOL)enabled;	// 0x3b4629
- (void)setObject:(id)object forKey:(id)key;	// 0x3b44e9
@end

