/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ATVSearchViewController.h"
#import "RUIYTListDataSourceAspectDelegate.h"
#import "RUIYTDocumentLoaderDelegate.h"

@class RUIYTListDataSourceAspect, RUIYTDocumentLoader, RUIYTSearchResultsLoader;

__attribute__((visibility("hidden")))
@interface RUIYTSearchController : ATVSearchViewController <RUIYTDocumentLoaderDelegate, RUIYTListDataSourceAspectDelegate> {
	RUIYTDocumentLoader *_documentLoader;	// 120 = 0x78
	RUIYTListDataSourceAspect *_listDataSourceAspect;	// 124 = 0x7c
	RUIYTSearchResultsLoader *_searchResultsLoader;	// 128 = 0x80
}
- (id)init;	// 0x2846a9
- (void).cxx_destruct;	// 0x285681
- (BOOL)_search:(id)search;	// 0x2852e9
- (void)_searchResultsDidLoad:(id)_searchResults;	// 0x2856c9
- (void)_updateSearchResults:(id)results searchString:(id)string;	// 0x2853f9
- (void)dealloc;	// 0x284a05
- (void)documentLoader:(id)loader didLoadDocument:(id)document;	// 0x284e91
- (BOOL)isNetworkDependent;	// 0x284e29
- (BOOL)listDataSourceAspect:(id)aspect loadMoreItemsForSection:(unsigned)section count:(unsigned)count;	// 0x285045
- (void)searchView:(id)view focusDidChangeToControl:(int)focus;	// 0x284e2d
- (void)wasPushed;	// 0x284aa5
@end

