/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreData.framework/CoreData
 */

#import "CoreData-Structs.h"
#import <NSObject.h> // Unknown library

@class NSManagedObjectContext;

__attribute__((visibility("hidden")))
@interface _PFManagedObjectReferenceQueue : NSObject {
@private
	int _cd_rc;	// 4 = 0x4
	int _spinLock;	// 8 = 0x8
	int _flags;	// 12 = 0xc
	int _signalRunloop;	// 16 = 0x10
	NSManagedObjectContext *_context;	// 20 = 0x14
	CFArrayRef _queue;	// 24 = 0x18
	CFRunLoopObserverRef _rlObserver;	// 28 = 0x1c
}
- (id)initForContext:(id)context;	// 0x322f37b5
- (BOOL)_GC_queueForDealloc:(id)dealloc;	// 0x32370309
- (void)_contextDidDealloc;	// 0x32322e51
- (BOOL)_isDeallocating;	// 0x32370305
- (void)_processReferenceQueue:(BOOL)queue;	// 0x32322575
- (BOOL)_queueBatchForDealloc:(CFArrayRef)dealloc;	// 0x32323459
- (int)_queueCount;	// 0x32325d69
- (BOOL)_queueForDealloc:(id)dealloc;	// 0x3232322d
- (BOOL)_signal;	// 0x3237030d
- (BOOL)_tryRetain;	// 0x32370301
- (void)_unregisterRunloopObservers;	// 0x32320d15
- (void)dealloc;	// 0x32323619
- (void)finalize;	// 0x3237b5c1
- (void)release;	// 0x322f38d9
- (id)retain;	// 0x322f38b9
- (unsigned)retainCount;	// 0x323702ed
@end

