/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <DOMHTMLOptGroupElement.h> // Unknown library


@interface DOMHTMLOptGroupElement (UIWebFormExtensions)
- (id)createPickerCell;	// 0x355219c5
- (id)createSelectedItem;	// 0x3552197d
- (id)itemTitle;	// 0x35521a7d
- (void)populateCell:(id)cell;	// 0x35521a0d
@end

