/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OADTextSpacing.h"


@interface OADPercentTextSpacing : OADTextSpacing {
	float mPercent;	// 4 = 0x4
}
- (id)initWithPercent:(float)percent;	// 0x34e5d951
- (unsigned)hash;	// 0x350a73c5
- (BOOL)isEqual:(id)equal;	// 0x34ec81b9
- (float)percent;	// 0x34ec823d
@end

