/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import <NSObject.h> // Unknown library


@interface PXTransition : NSObject {
}
+ (void)initialize;	// 0x34f96fbd
+ (int)readDirection:(xmlNode *)direction defaultValue:(int)value;	// 0x34fff109
+ (int)readInOut:(xmlNode *)anOut defaultValue:(int)value;	// 0x34fff175
+ (int)readOrientation:(xmlNode *)orientation attribute:(const char *)attribute defaultValue:(int)value;	// 0x35019345
+ (int)readReverseDirection:(xmlNode *)direction defaultValue:(int)value;	// 0x34fff201
+ (void)readTransitionFromNode:(xmlNode *)node tgtTransition:(id)transition drawingState:(id)state;	// 0x34f97061
@end

