/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "BRImageProxy.h"

@class MEAirTunesMediaAsset;

__attribute__((visibility("hidden")))
@interface MEAirTunesImageProxy : XXUnknownSuperclass <BRImageProxy> {
	MEAirTunesMediaAsset *_asset;	// 4 = 0x4
}
+ (id)imageProxyWithAsset:(id)asset;	// 0x4e75d
- (id)initWithAsset:(id)asset;	// 0x4e7ad
- (void).cxx_destruct;	// 0x4e90d
- (void)cancelImageRequestsForImageSizes:(int)imageSizes;	// 0x4e8f5
- (id)defaultImageForImageSize:(int)imageSize;	// 0x4e869
- (id)imageForImageSize:(int)imageSize;	// 0x4e849
- (id)imageIDForImageSize:(int)imageSize;	// 0x4e829
- (id)object;	// 0x4e8f9
- (BOOL)supportsImageForImageSize:(int)imageSize;	// 0x4e8d1
@end

