/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/Frameworks/DAEAS.framework/DAEAS
 */

#import "ASItem.h"

@class NSString;

@interface ASPolicy : ASItem {
	NSString *_type;	// 40 = 0x28
	NSString *_key;	// 44 = 0x2c
	NSString *_status;	// 48 = 0x30
}
@property(readonly, retain) NSString *key;	// G=0x34382c81; converted property
@property(readonly, retain) NSString *type;	// G=0x34382c71; converted property
+ (BOOL)acceptsTopLevelLeaves;	// 0x343830b5
+ (BOOL)frontingBasicTypes;	// 0x34382fdd
+ (BOOL)notifyOfUnknownTokens;	// 0x34382f95
+ (BOOL)parsingLeafNode;	// 0x3438306d
+ (BOOL)parsingWithSubItems;	// 0x34383025
- (void)_setKey:(id)key;	// 0x34382efd
- (void)_setStatus:(id)status;	// 0x34382ec1
- (void)_setType:(id)type;	// 0x34382f39
- (id)asParseRules;	// 0x34382c95
- (void)dealloc;	// 0x343830fd
- (id)description;	// 0x34382e29
// converted property getter: - (id)key;	// 0x34382c81
- (id)perDomainDictsForPolicy;	// 0x34382c91
- (int)status;	// 0x34382f75
// converted property getter: - (id)type;	// 0x34382c71
@end

