/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import "DOMHTMLElement.h"


@interface DOMHTMLMenuElement : DOMHTMLElement {
}
@property(assign) BOOL compact;	// G=0x31b0932d; S=0x31b09439; 
// declared property getter: - (BOOL)compact;	// 0x31b0932d
// declared property setter: - (void)setCompact:(BOOL)compact;	// 0x31b09439
@end

