/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CalDAV.framework/CalDAV
 */

#import <CoreDAVItem.h> // Unknown library

@class CoreDAVItemWithNoChildren;

@interface CalDAVCalendarServerAccessItem : CoreDAVItem {
	CoreDAVItemWithNoChildren *_accessLevel;	// 28 = 0x1c
}
@property(retain) CoreDAVItemWithNoChildren *accessLevel;	// G=0x338eac41; S=0x338eac55; @synthesize=_accessLevel
- (id)init;	// 0x338ea855
- (id)initWithAccess:(int)access;	// 0x338ea8c9
- (id)initWithNameSpace:(id)nameSpace andName:(id)name;	// 0x338ea881
// declared property getter: - (id)accessLevel;	// 0x338eac41
- (id)copyParseRules;	// 0x338eaa3d
- (void)dealloc;	// 0x338ea9cd
- (id)description;	// 0x338eaa11
// declared property setter: - (void)setAccessLevel:(id)level;	// 0x338eac55
@end

