/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
 */

#import "CoreDAVTask.h"

@class NSString, NSDictionary, CoreDAVXMLData, NSMutableDictionary;

@interface CoreDAVMultiPutTask : CoreDAVTask {
	NSString *_appSpecificNamespace;	// 120 = 0x78
	NSString *_appSpecificDataProp;	// 124 = 0x7c
	NSString *_checkCTag;	// 128 = 0x80
	CoreDAVXMLData *_pushedData;	// 132 = 0x84
	BOOL _validCTag;	// 136 = 0x88
	NSString *_nextCTag;	// 140 = 0x8c
	NSMutableDictionary *_uuidToHREF;	// 144 = 0x90
	NSMutableDictionary *_hrefToETag;	// 148 = 0x94
	NSMutableDictionary *_uuidToErrorItems;	// 152 = 0x98
	NSMutableDictionary *_hrefToErrorItems;	// 156 = 0x9c
}
@property(readonly, assign) NSDictionary *hrefToETag;	// G=0x3100e805; @synthesize=_hrefToETag
@property(readonly, assign) NSDictionary *hrefToErrorItems;	// G=0x3100e825; @synthesize=_hrefToErrorItems
@property(readonly, assign) NSString *nextCTag;	// G=0x3100e7e5; @synthesize=_nextCTag
@property(readonly, assign) NSDictionary *uuidToErrorItems;	// G=0x3100e815; @synthesize=_uuidToErrorItems
@property(readonly, assign) NSDictionary *uuidToHREF;	// G=0x3100e7f5; @synthesize=_uuidToHREF
- (id)initWithURL:(id)url checkCTag:(id)tag uuidsToAddActions:(id)addActions hrefsToModDeleteActions:(id)modDeleteActions;	// 0x3100d929
- (id)additionalHeaderValues;	// 0x3100dbf1
- (id)copyDefaultParserForContentType:(id)contentType;	// 0x3100e29d
- (void)dealloc;	// 0x3100db05
- (void)fillOutDataWithUUIDsToAddActions:(id)addActions hrefsToModDeleteActions:(id)modDeleteActions;	// 0x3100dcf1
- (void)finishCoreDAVTaskWithError:(id)error;	// 0x3100e455
// declared property getter: - (id)hrefToETag;	// 0x3100e805
// declared property getter: - (id)hrefToErrorItems;	// 0x3100e825
- (id)httpMethod;	// 0x3100dcc5
// declared property getter: - (id)nextCTag;	// 0x3100e7e5
- (id)requestBody;	// 0x3100dcd1
// declared property getter: - (id)uuidToErrorItems;	// 0x3100e815
// declared property getter: - (id)uuidToHREF;	// 0x3100e7f5
@end

