/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <NSObject.h> // Unknown library

@class MPMusicPlayerControllerInternal;

@protocol MPMusicPlayerController
@optional
@property(retain) id allowsRemoteUIAccess;	// converted property
@property(retain) id currentChapterIndex;	// converted property
@property(retain) id currentPlaybackTime;	// converted property
@property(retain) id nowPlayingItem;	// converted property
@property(retain) id playbackSpeed;	// converted property
@property(retain) id repeatMode;	// converted property
@property(retain) id shuffleMode;	// converted property
// converted property getter: - (id)allowsRemoteUIAccess;
- (void)beginSeekingBackward;
- (void)beginSeekingForward;
// converted property getter: - (id)currentChapterIndex;
// converted property getter: - (id)currentPlaybackTime;
- (void)endSeeking;
- (id)indexOfNowPlayingItem;
- (id)isGeniusAvailable;
- (id)isNowPlayingItemFromGeniusMix;
// converted property getter: - (id)nowPlayingItem;
- (id)nowPlayingItemAtIndex:(id)index;
- (id)numberOfItems;
- (void)pause;
- (void)pauseWithFadeoutDuration:(id)fadeoutDuration;
- (void)play;
- (void)playItem:(id)item;
// converted property getter: - (id)playbackSpeed;
- (id)playbackState;
- (void)prepareQueueForPlayback;
- (id)queueAsQuery;
- (void)registerForServerDiedNotifications;
// converted property getter: - (id)repeatMode;
- (id)serverIsAlive;
// converted property setter: - (void)setAllowsRemoteUIAccess:(id)access;
// converted property setter: - (void)setCurrentChapterIndex:(id)index;
// converted property setter: - (void)setCurrentPlaybackTime:(id)time;
// converted property setter: - (void)setNowPlayingItem:(id)item;
// converted property setter: - (void)setPlaybackSpeed:(id)speed;
- (void)setQueueWithGeniusMixPlaylist:(id)geniusMixPlaylist;
- (void)setQueueWithItemCollection:(id)itemCollection;
- (void)setQueueWithQuery:(id)query;
- (void)setQueueWithQuery:(id)query firstItem:(id)item;
- (id)setQueueWithSeedItems:(id)seedItems;
// converted property setter: - (void)setRepeatMode:(id)mode;
// converted property setter: - (void)setShuffleMode:(id)mode;
- (void)setUseApplicationSpecificQueue:(id)queue;
- (void)shuffle;
// converted property getter: - (id)shuffleMode;
- (void)skipToBeginning;
- (void)skipToBeginningOrPreviousItem;
- (void)skipToNextChapter;
- (void)skipToNextItem;
- (void)skipToPreviousChapter;
- (void)skipToPreviousItem;
- (void)stop;
- (id)unshuffledIndexOfNowPlayingItem;
@end

@interface MPMusicPlayerController : NSObject {
	MPMusicPlayerControllerInternal *_internal;	// 4 = 0x4
}
@property(assign) BOOL allowsRemoteUIAccess;	// G=0x34684411; S=0x34684445; converted property
@property(assign) unsigned currentChapterIndex;	// G=0x3468462d; S=0x34684665; converted property
@property(assign) double currentPlaybackTime;	// G=0x34684211; S=0x34684249; converted property
@property(assign) int playbackSpeed;	// G=0x346844d1; S=0x34684509; converted property
@property(assign) int repeatMode;	// G=0x34683fc9; S=0x34684001; converted property
@property(assign) int shuffleMode;	// G=0x34684049; S=0x34684081; converted property
@property(assign) float volume;	// G=0x346840c9; S=0x34684125; converted property
+ (id)applicationMusicPlayer;	// 0x346839c5
+ (id)iPodMusicPlayer;	// 0x34683a21
+ (void)initialize;	// 0x346847d5
+ (id)runLoopForNotifications;	// 0x34684871
+ (void)setRunLoopForNotifications:(id)notifications;	// 0x34684839
- (id)init;	// 0x34683a7d
- (void)_clientCheckInUsingExistencePort:(BOOL)usingExistencePort;	// 0x34684aad
- (void)_itemPlaybackDidEnd:(unsigned long long)_itemPlayback;	// 0x3468504d
- (void)_musicPlayerDidLaunch;	// 0x346849cd
- (void)_nowPlayingItemDidChange:(unsigned long long)_nowPlayingItem;	// 0x34684e31
- (void)_playbackStateDidChange:(int)_playbackState;	// 0x34684cb1
- (void)_registerForLaunchNotifications;	// 0x346849e1
- (void)_repeatModeDidChange:(int)_repeatMode;	// 0x34684fc1
- (void)_runMigServerOnPort:(unsigned)port;	// 0x34685135
- (void)_serverDied:(id)died;	// 0x34684949
- (void)_setUseApplicationSpecificQueue:(BOOL)queue;	// 0x346848b5
- (void)_shuffleModeDidChange:(int)_shuffleMode;	// 0x34684f39
- (void)_stopMigServer;	// 0x346851d9
- (void)_systemVolumeDidChange:(id)_systemVolume;	// 0x34683d41
- (void)_unregisterForLaunchNotifications;	// 0x34684a8d
// converted property getter: - (BOOL)allowsRemoteUIAccess;	// 0x34684411
- (void)beginGeneratingPlaybackNotifications;	// 0x34684295
// converted property getter: - (unsigned)currentChapterIndex;	// 0x3468462d
// converted property getter: - (double)currentPlaybackTime;	// 0x34684211
- (void)dealloc;	// 0x34683bf1
- (void)endGeneratingPlaybackNotifications;	// 0x346842b9
- (void)forwardInvocation:(id)invocation;	// 0x34683df5
- (unsigned)indexOfNowPlayingItem;	// 0x34684551
- (BOOL)isGeniusAvailable;	// 0x346842e1
- (BOOL)isNowPlayingItemFromGeniusMix;	// 0x346845f9
- (id)methodSignatureForSelector:(SEL)selector;	// 0x34683e19
- (id)nowPlayingItem;	// 0x34683e39
- (id)nowPlayingItemAtIndex:(unsigned)index;	// 0x34684349
- (unsigned)numberOfItems;	// 0x346845c1
- (void)pauseWithFadeoutDuration:(double)fadeoutDuration;	// 0x34684391
// converted property getter: - (int)playbackSpeed;	// 0x346844d1
- (int)playbackState;	// 0x34683f31
// converted property getter: - (int)repeatMode;	// 0x34683fc9
- (BOOL)serverIsAlive;	// 0x34684881
// converted property setter: - (void)setAllowsRemoteUIAccess:(BOOL)access;	// 0x34684445
// converted property setter: - (void)setCurrentChapterIndex:(unsigned)index;	// 0x34684665
// converted property setter: - (void)setCurrentPlaybackTime:(double)time;	// 0x34684249
// converted property setter: - (void)setPlaybackSpeed:(int)speed;	// 0x34684509
- (void)setQueueWithGeniusMixPlaylist:(id)geniusMixPlaylist;	// 0x346847b5
- (void)setQueueWithItemCollection:(id)itemCollection;	// 0x34683e8d
- (void)setQueueWithQuery:(id)query;	// 0x34683e79
- (void)setQueueWithQuery:(id)query firstItem:(id)item;	// 0x346846ad
- (BOOL)setQueueWithSeedItems:(id)seedItems;	// 0x34684315
// converted property setter: - (void)setRepeatMode:(int)mode;	// 0x34684001
// converted property setter: - (void)setShuffleMode:(int)mode;	// 0x34684081
- (void)setUseCachedPlaybackState:(BOOL)state;	// 0x346843dd
// converted property setter: - (void)setVolume:(float)volume;	// 0x34684125
// converted property getter: - (int)shuffleMode;	// 0x34684049
- (unsigned)unshuffledIndexOfNowPlayingItem;	// 0x34684589
// converted property getter: - (float)volume;	// 0x346840c9
@end

