/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CalDAV.framework/CalDAV
 */

#import <CoreDAVItem.h> // Unknown library

@class NSMutableSet;

@interface CalDAVItemWithRecurrenceChildren : CoreDAVItem {
	NSMutableSet *_recurrences;	// 28 = 0x1c
}
@property(retain) NSMutableSet *recurrences;	// G=0x32ed5e21; S=0x32ed5e35; @synthesize=_recurrences
- (void)addRecurrence:(id)recurrence;	// 0x32ed5ca9
- (id)copyParseRules;	// 0x32ed5d21
- (void)dealloc;	// 0x32ed5c5d
// declared property getter: - (id)recurrences;	// 0x32ed5e21
// declared property setter: - (void)setRecurrences:(id)recurrences;	// 0x32ed5e35
@end

