/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSURL, SAMPMediaItem;

@interface SAMPGeniusSummon : SABaseClientBoundCommand {
}
@property(retain, nonatomic) SAMPMediaItem *mediaItem;	// G=0x304d90b1; S=0x304d9105; 
@property(copy, nonatomic) NSURL *targetAppId;	// G=0x304d8fd5; S=0x304d9051; 
+ (id)geniusSummon;	// 0x304d8f45
+ (id)geniusSummonWithDictionary:(id)dictionary context:(id)context;	// 0x304d8f89
- (id)encodedClassName;	// 0x304d8f39
- (id)groupIdentifier;	// 0x304d8f29
// declared property getter: - (id)mediaItem;	// 0x304d90b1
- (BOOL)requiresResponse;	// 0x304d9141
// declared property setter: - (void)setMediaItem:(id)item;	// 0x304d9105
// declared property setter: - (void)setTargetAppId:(id)anId;	// 0x304d9051
// declared property getter: - (id)targetAppId;	// 0x304d8fd5
@end

