/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseCommand.h"
#import "SAServerBoundCommand.h"

@class NSString, NSArray;

@interface SASFinishSpeech : SABaseCommand <SAServerBoundCommand> {
}
@property(copy, nonatomic) NSString *aceId;	// @dynamic
@property(copy, nonatomic) NSString *endpoint;	// G=0x304d2121; S=0x304d213d; 
@property(copy, nonatomic) NSArray *orderedContext;	// G=0x304d218d; S=0x304d21a9; 
@property(assign, nonatomic) int packetCount;	// G=0x304d21f9; S=0x304d2269; 
@property(copy, nonatomic) NSString *refId;	// @dynamic
+ (id)finishSpeech;	// 0x304d2091
+ (id)finishSpeechWithDictionary:(id)dictionary context:(id)context;	// 0x304d20d5
- (id)encodedClassName;	// 0x304d2085
// declared property getter: - (id)endpoint;	// 0x304d2121
- (id)groupIdentifier;	// 0x304d2075
// declared property getter: - (id)orderedContext;	// 0x304d218d
// declared property getter: - (int)packetCount;	// 0x304d21f9
// declared property setter: - (void)setEndpoint:(id)endpoint;	// 0x304d213d
// declared property setter: - (void)setOrderedContext:(id)context;	// 0x304d21a9
// declared property setter: - (void)setPacketCount:(int)count;	// 0x304d2269
@end

