/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class SAUIAddViews, NSDictionary, NSString, NSURL, SAUIImageResource;

@interface SAUIAppPunchOut : SABaseClientBoundCommand {
}
@property(retain, nonatomic) SAUIAddViews *alternativePunchOut;	// G=0x305106f1; S=0x30510745; 
@property(copy, nonatomic) NSString *appDisplayName;	// G=0x30510781; S=0x3051079d; 
@property(retain, nonatomic) SAUIImageResource *appIcon;	// G=0x305107ed; S=0x30510841; 
@property(copy, nonatomic) NSDictionary *appIconMap;	// G=0x3051087d; S=0x305108f9; 
@property(assign, nonatomic) BOOL appInstalled;	// G=0x30510961; S=0x305109d9; 
@property(copy, nonatomic) NSURL *appStoreUri;	// G=0x30510a1d; S=0x30510a99; 
@property(copy, nonatomic) NSString *bundleId;	// G=0x30510af9; S=0x30510b15; 
@property(copy, nonatomic) NSString *providerId;	// G=0x30510b65; S=0x30510b81; 
@property(copy, nonatomic) NSString *punchOutName;	// G=0x30510bd1; S=0x30510bed; 
@property(copy, nonatomic) NSURL *punchOutUri;	// G=0x30510c3d; S=0x30510cb9; 
+ (id)appPunchOut;	// 0x30510661
+ (id)appPunchOutWithDictionary:(id)dictionary context:(id)context;	// 0x305106a5
// declared property getter: - (id)alternativePunchOut;	// 0x305106f1
// declared property getter: - (id)appDisplayName;	// 0x30510781
// declared property getter: - (id)appIcon;	// 0x305107ed
// declared property getter: - (id)appIconMap;	// 0x3051087d
// declared property getter: - (BOOL)appInstalled;	// 0x30510961
// declared property getter: - (id)appStoreUri;	// 0x30510a1d
// declared property getter: - (id)bundleId;	// 0x30510af9
- (id)encodedClassName;	// 0x30510655
- (id)groupIdentifier;	// 0x30510645
// declared property getter: - (id)providerId;	// 0x30510b65
// declared property getter: - (id)punchOutName;	// 0x30510bd1
// declared property getter: - (id)punchOutUri;	// 0x30510c3d
- (BOOL)requiresResponse;	// 0x30510d19
// declared property setter: - (void)setAlternativePunchOut:(id)anOut;	// 0x30510745
// declared property setter: - (void)setAppDisplayName:(id)name;	// 0x3051079d
// declared property setter: - (void)setAppIcon:(id)icon;	// 0x30510841
// declared property setter: - (void)setAppIconMap:(id)map;	// 0x305108f9
// declared property setter: - (void)setAppInstalled:(BOOL)installed;	// 0x305109d9
// declared property setter: - (void)setAppStoreUri:(id)uri;	// 0x30510a99
// declared property setter: - (void)setBundleId:(id)anId;	// 0x30510b15
// declared property setter: - (void)setProviderId:(id)anId;	// 0x30510b81
// declared property setter: - (void)setPunchOutName:(id)name;	// 0x30510bed
// declared property setter: - (void)setPunchOutUri:(id)uri;	// 0x30510cb9
@end

