/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSArray, NSNumber;

@interface SAUIRequestUpdateViews : SABaseClientBoundCommand {
}
@property(copy, nonatomic) NSArray *commands;	// G=0x32f6cb0d; S=0x32f6cb75; 
@property(retain, nonatomic) NSNumber *timeInSeconds;	// G=0x32f6cbdd; S=0x32f6cbf9; 
@property(copy, nonatomic) NSArray *viewIds;	// G=0x32f6cc15; S=0x32f6cc31; 
+ (id)requestUpdateViews;	// 0x32f6ca7d
+ (id)requestUpdateViewsWithDictionary:(id)dictionary context:(id)context;	// 0x32f6cac1
// declared property getter: - (id)commands;	// 0x32f6cb0d
- (id)encodedClassName;	// 0x32f6ca71
- (id)groupIdentifier;	// 0x32f6ca61
- (BOOL)requiresResponse;	// 0x32f6cc81
// declared property setter: - (void)setCommands:(id)commands;	// 0x32f6cb75
// declared property setter: - (void)setTimeInSeconds:(id)seconds;	// 0x32f6cbf9
// declared property setter: - (void)setViewIds:(id)ids;	// 0x32f6cc31
// declared property getter: - (id)timeInSeconds;	// 0x32f6cbdd
// declared property getter: - (id)viewIds;	// 0x32f6cc15
@end

