/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

#import <NSObject.h> // Unknown library

@class NSArray;

@interface AFSpeechInterpretation : NSObject {
	NSArray *_tokens;	// 4 = 0x4
}
@property(copy, nonatomic) NSArray *tokens;	// G=0x334ec2f5; S=0x334ec309; @synthesize=_tokens
- (id)initWithDKPlistRepresentation:(id)dkplistRepresentation;	// 0x334ec23d
- (void).cxx_destruct;	// 0x334ec319
- (id)dkPlistRepresentation;	// 0x334ec1c9
// declared property setter: - (void)setTokens:(id)tokens;	// 0x334ec309
// declared property getter: - (id)tokens;	// 0x334ec2f5
@end

