/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <NSObject.h> // Unknown library

@class NSString;

@interface UITextInputMode : NSObject {
}
@property(readonly, assign, nonatomic) NSString *primaryLanguage;	// G=0x30369105; 
+ (id)activeInputModes;	// 0x30369191
+ (id)currentInputMode;	// 0x3036915d
// declared property getter: - (id)primaryLanguage;	// 0x30369105
@end

