/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <NSObject.h> // Unknown library
#import "UIFormPeripheral.h"

@class DOMHTMLSelectElement;
@protocol UIWebFormControl;

__attribute__((visibility("hidden")))
@interface UIWebSelectPeripheral : NSObject <UIFormPeripheral> {
@private
	DOMHTMLSelectElement *_selectionNode;	// 4 = 0x4
	id<UIWebFormControl> _selectControl;	// 8 = 0x8
}
@property(retain, nonatomic) id<UIWebFormControl> _selectControl;	// G=0x30296875; S=0x30296885; @synthesize
@property(retain, nonatomic) DOMHTMLSelectElement *_selectionNode;	// G=0x30296855; S=0x30296865; @synthesize
+ (id)createPeripheralWithDOMHTMLSelectElement:(id)domhtmlselectElement;	// 0x30296775
- (id)initWithDOMHTMLSelectElement:(id)domhtmlselectElement;	// 0x3029657d
// declared property getter: - (id)_selectControl;	// 0x30296875
// declared property getter: - (id)_selectionNode;	// 0x30296855
- (id)assistantView;	// 0x30296815
- (void)beginEditing;	// 0x30296835
- (void)dealloc;	// 0x302967bd
// declared property setter: - (void)set_selectControl:(id)control;	// 0x30296885
// declared property setter: - (void)set_selectionNode:(id)node;	// 0x30296865
@end

