/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <WebFrame.h> // Unknown library


@interface WebFrame (BrowserAdditions)
- (void)_collectFormFieldElementsIntoArray:(id)array upToLimit:(unsigned)limit onlyIncludeFocusedElements:(BOOL)elements;	// 0x303213cd
- (id)_topFrame;	// 0x303213ad
- (id)allFormFields;	// 0x30321591
- (BOOL)containsAnyFocusedFormFields;	// 0x30321635
- (BOOL)containsAnyFormFields;	// 0x303215d9
- (BOOL)isMainFrame;	// 0x3012bb0d
- (BOOL)isOrphaned;	// 0x30321691
@end

@interface WebFrame (UIWebDocumentViewTextSelecting)
- (BOOL)isTexty;	// 0x30215101
@end

@interface WebFrame (UIWebSelectionAdditions)
- (BOOL)containsOnlySelectableElements;	// 0x30215215
@end

