/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AppleTV-Structs.h"
#import "ATVCarouselViewUIDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ATVPhotoCarouselViewUIDelegateCommentsImpl : XXUnknownSuperclass <ATVCarouselViewUIDelegate> {
	float _reflectionAmount;	// 4 = 0x4
	double _eventAnimationDuration;	// 8 = 0x8
	double _retriggerEventAnimationDuration;	// 16 = 0x10
	XXStruct_40SSZC _preferredImageSize;	// 24 = 0x18
}
@property(assign, nonatomic) double eventAnimationDuration;	// G=0xcd179; S=0xcd191; @synthesize=_eventAnimationDuration
@property(assign, nonatomic) XXStruct_40SSZC preferredImageSize;	// G=0xcd1d1; S=0xcd1e9; @synthesize=_preferredImageSize
@property(assign, nonatomic) float reflectionAmount;	// G=0xcd1fd; S=0xcd20d; @synthesize=_reflectionAmount
@property(assign, nonatomic) double retriggerEventAnimationDuration;	// G=0xcd1a5; S=0xcd1bd; @synthesize=_retriggerEventAnimationDuration
- (id)carouselView:(id)view configurePerspectiveForContext:(id)context;	// 0xcbfe9
- (ATVCarouselViewItemsConfig)carouselView:(id)view itemsConfigForContext:(id)context;	// 0xcbf31
- (id)carouselView:(id)view setPositionOfItem:(id)item toPositionAtIndex:(unsigned)index context:(id)context;	// 0xcc0e9
// declared property getter: - (double)eventAnimationDuration;	// 0xcd179
// declared property getter: - (XXStruct_40SSZC)preferredImageSize;	// 0xcd1d1
// declared property getter: - (float)reflectionAmount;	// 0xcd1fd
// declared property getter: - (double)retriggerEventAnimationDuration;	// 0xcd1a5
// declared property setter: - (void)setEventAnimationDuration:(double)duration;	// 0xcd191
// declared property setter: - (void)setPreferredImageSize:(XXStruct_40SSZC)size;	// 0xcd1e9
// declared property setter: - (void)setReflectionAmount:(float)amount;	// 0xcd20d
// declared property setter: - (void)setRetriggerEventAnimationDuration:(double)duration;	// 0xcd1bd
@end

