/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AppleTV-Structs.h"
#import "BRViewController.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface ATVSWUDownloadController : BRViewController {
	BOOL _applyStarted;	// 104 = 0x68
	NSString *_cancelTitle;	// 108 = 0x6c
	NSString *_cancelText;	// 112 = 0x70
	NSString *_cancelContinueLabel;	// 116 = 0x74
	NSString *_cancelCancelLabel;	// 120 = 0x78
}
@property(assign, nonatomic) BOOL applyStarted;	// G=0x354bd9; S=0x354be9; @synthesize=_applyStarted
@property(retain, nonatomic) NSString *cancelCancelLabel;	// G=0x354ba1; S=0x354bb1; @synthesize=_cancelCancelLabel
@property(retain, nonatomic) NSString *cancelContinueLabel;	// G=0x354b69; S=0x354b79; @synthesize=_cancelContinueLabel
@property(retain, nonatomic) NSString *cancelText;	// G=0x354b31; S=0x354b41; @synthesize=_cancelText
@property(retain, nonatomic) NSString *cancelTitle;	// G=0x354af9; S=0x354b09; @synthesize=_cancelTitle
- (id)init;	// 0x354975
- (id)initWithCancelTitle:(id)cancelTitle text:(id)text continueLabel:(id)label cancelLabel:(id)label4;	// 0x3546a1
- (void).cxx_destruct;	// 0x354bf9
- (void)_requestCancel;	// 0x355489
- (void)_updateApplyFailed:(id)failed;	// 0x3553e1
- (void)_updateApplyStarted:(id)started;	// 0x355375
- (void)_updateCheckFinished:(id)finished;	// 0x354cbd
- (void)_updateCheckStarted:(id)started;	// 0x354c55
- (void)_updateDownloadFinished:(id)finished;	// 0x354ea1
- (void)_updateDownloadStarted:(id)started;	// 0x354e39
- (void)_updateProgress:(id)progress;	// 0x355115
// declared property getter: - (BOOL)applyStarted;	// 0x354bd9
- (BOOL)brEventAction:(id)action;	// 0x3549ed
// declared property getter: - (id)cancelCancelLabel;	// 0x354ba1
// declared property getter: - (id)cancelContinueLabel;	// 0x354b69
- (void)cancelOperation;	// 0x354af5
// declared property getter: - (id)cancelText;	// 0x354b31
// declared property getter: - (id)cancelTitle;	// 0x354af9
- (void)dealloc;	// 0x354981
// declared property setter: - (void)setApplyStarted:(BOOL)started;	// 0x354be9
// declared property setter: - (void)setCancelCancelLabel:(id)label;	// 0x354bb1
// declared property setter: - (void)setCancelContinueLabel:(id)label;	// 0x354b79
// declared property setter: - (void)setCancelText:(id)text;	// 0x354b41
// declared property setter: - (void)setCancelTitle:(id)title;	// 0x354b09
- (void)startOperation;	// 0x354aed
- (void)stopOperation;	// 0x354af1
- (void)wasPopped;	// 0x354aad
- (void)wasPushed;	// 0x354a6d
@end

