/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRTextControl, BRTumblerControl;

__attribute__((visibility("hidden")))
@interface ATVTumblerWithTextListHeaderControl : BRControl {
	BOOL _customTextOnTop;	// 84 = 0x54
	float _tumblerMaxWidth;	// 88 = 0x58
	BRTumblerControl *_tumbler;	// 92 = 0x5c
	BRTextControl *_customText;	// 96 = 0x60
}
@property(readonly, assign) BRTextControl *customText;	// G=0xbb065; @synthesize=_customText
@property(assign, nonatomic) BOOL customTextOnTop;	// G=0xbb079; S=0xbaa4d; @synthesize=_customTextOnTop
@property(readonly, assign) BRTumblerControl *tumbler;	// G=0xbb051; @synthesize=_tumbler
@property(assign, nonatomic) float tumblerMaxWidth;	// G=0xbb031; S=0xbb041; @synthesize=_tumblerMaxWidth
- (id)init;	// 0xba931
- (id)accessibilityLabel;	// 0xbafc9
- (BOOL)brEventAction:(id)action;	// 0xbaa79
// declared property getter: - (id)customText;	// 0xbb065
// declared property getter: - (BOOL)customTextOnTop;	// 0xbb079
- (void)dealloc;	// 0xba9e9
- (void)layoutSubcontrols;	// 0xbabb9
// declared property setter: - (void)setCustomTextOnTop:(BOOL)top;	// 0xbaa4d
// declared property setter: - (void)setTumblerMaxWidth:(float)width;	// 0xbb041
- (CGSize)sizeThatFits:(CGSize)fits;	// 0xbaaa1
// declared property getter: - (id)tumbler;	// 0xbb051
// declared property getter: - (float)tumblerMaxWidth;	// 0xbb031
@end

