/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface BRUsageReporter : XXUnknownSuperclass {
}
+ (void)clearDistributionKey:(id)key;	// 0x42daad
+ (void)clearScalarKey:(id)key;	// 0x42d9c9
+ (void)decrementScalarKey:(id)key;	// 0x42da39
+ (void)incrementScalarKey:(id)key;	// 0x42da01
+ (void)pushValue:(double)value forDistributionKey:(id)distributionKey;	// 0x42dae5
+ (void)setValue:(long long)value forScalarKey:(id)scalarKey;	// 0x42da71
@end

