/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

#import "CIFilter.h"
#import "CoreImage-Structs.h"

@class CIVector, CIImage;

__attribute__((visibility("hidden")))
@interface CIStretch : CIFilter {
@private
	CIImage *inputImage;	// 36 = 0x24
	CIVector *inputPoint;	// 40 = 0x28
}
@property(retain, nonatomic) CIImage *inputImage;	// G=0x30257b21; S=0x30257b31; @synthesize
@property(copy, nonatomic) CIVector *inputPoint;	// G=0x30257b55; S=0x30257b65; @synthesize
+ (id)customAttributes;	// 0x302575b5
- (id)_kernel;	// 0x30257681
// declared property getter: - (id)inputImage;	// 0x30257b21
// declared property getter: - (id)inputPoint;	// 0x30257b55
- (id)outputImage;	// 0x30257885
- (void)setDefaults;	// 0x30257871
// declared property setter: - (void)setInputImage:(id)image;	// 0x30257b31
// declared property setter: - (void)setInputPoint:(id)point;	// 0x30257b65
@end

