/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <NSObject.h> // Unknown library
#import "UIKit-Structs.h"

@class NSString;

@interface UIWebElementAction : NSObject {
	NSString *_title;	// 4 = 0x4
	id _actionHandler;	// 8 = 0x8
	int _type;	// 12 = 0xc
}
@property(readonly, assign, nonatomic) int type;	// G=0x3047a04d; @synthesize=_type
+ (id)customElementActionWithTitle:(id)title actionHandler:(id)handler;	// 0x30479991
+ (id)standardElementActionWithType:(int)type;	// 0x30479fa1
+ (id)standardElementActionWithType:(int)type customTitle:(id)title;	// 0x30479a25
- (id)initWithTitle:(id)title actionHandler:(id)handler type:(int)type;	// 0x304798a5
- (void)_runActionWithElement:(id)element targetURL:(id)url documentView:(id)view interactionLocation:(CGPoint)location;	// 0x30479fc5
- (id)_title;	// 0x30479fb5
- (void)dealloc;	// 0x3047992d
// declared property getter: - (int)type;	// 0x3047a04d
@end

