/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import <NSObject.h> // Unknown library

@class UIWebDocumentView, UITextSelection;
@protocol UIWebSelectionBlock;

__attribute__((visibility("hidden")))
@interface UIWebSelection : NSObject {
	UIWebDocumentView *_documentView;	// 4 = 0x4
	id<UIWebSelectionBlock> _base;	// 8 = 0x8
	id<UIWebSelectionBlock> _extent;	// 12 = 0xc
	CGSize _desiredSize;	// 16 = 0x10
	UITextSelection *_textSelection;	// 24 = 0x18
}
@property(retain, nonatomic) id<UIWebSelectionBlock> base;	// G=0x30503425; S=0x30503435; @synthesize=_base
@property(readonly, assign, nonatomic) CGRect boundingRect;	// G=0x30500e49; @dynamic
@property(assign, nonatomic) CGSize desiredSize;	// G=0x30503475; S=0x3050348d; @synthesize=_desiredSize
@property(readonly, assign, nonatomic) UIWebDocumentView *documentView;	// G=0x30503415; @synthesize=_documentView
@property(retain, nonatomic) id<UIWebSelectionBlock> extent;	// G=0x30503445; S=0x30503455; @synthesize=_extent
@property(readonly, assign, nonatomic, getter=isTextOnly) BOOL textOnly;	// G=0x30502b09; 
@property(readonly, assign, nonatomic) UITextSelection *textSelection;	// G=0x30503465; @synthesize=_textSelection
@property(readonly, assign, nonatomic) BOOL valid;	// G=0x30500e2d; 
- (id)initWithDocumentView:(id)documentView;	// 0x305008e1
- (void)adjustSelectionFromPoint:(CGPoint)point towardsPoint:(CGPoint)point2 withNewRect:(CGRect)newRect;	// 0x30501111
- (void)applySelectionToWebDocumentView;	// 0x30503135
- (id)asDomRange;	// 0x30503059
// declared property getter: - (id)base;	// 0x30503425
- (id)blockAtPoint:(CGPoint)point;	// 0x305011a9
- (BOOL)blockContainsPoint:(CGPoint)point;	// 0x30503171
- (id)blockOfSameWidthAtPoint:(CGPoint)point;	// 0x305013d1
// declared property getter: - (CGRect)boundingRect;	// 0x30500e49
- (CGRect)boundingRectAndInsideFixedPosition:(int *)position;	// 0x30500e71
- (CGRect)boundingTextSelectionRect;	// 0x30502d25
- (CGRect)boundingTextSelectionRectAndInsideFixedPosition:(int *)position;	// 0x30502d4d
- (void)dealloc;	// 0x30500979
- (id)description;	// 0x30503249
// declared property getter: - (CGSize)desiredSize;	// 0x30503475
- (float)distanceBetweenFirstRect:(CGRect)rect second:(CGRect)second edge:(int)edge;	// 0x305014d9
// declared property getter: - (id)documentView;	// 0x30503415
- (id)domDocument;	// 0x30501021
- (id)duplicate;	// 0x305029d9
- (id)elementAtPoint:(CGPoint)point;	// 0x30501339
// declared property getter: - (id)extent;	// 0x30503445
- (void)growFromEdge:(int)edge;	// 0x30501555
- (void)growSelectionTowardsPoint:(CGPoint)point;	// 0x305020a9
- (BOOL)isEqual:(id)equal;	// 0x30501f51
- (BOOL)isEqualToSelection:(id)selection;	// 0x30503351
// declared property getter: - (BOOL)isTextOnly;	// 0x30502b09
- (void)moveEdge:(int)edge outwards:(BOOL)outwards;	// 0x30502081
- (void)selectionChanged;	// 0x30502f9d
// declared property setter: - (void)setBase:(id)base;	// 0x30503435
// declared property setter: - (void)setDesiredSize:(CGSize)size;	// 0x3050348d
// declared property setter: - (void)setExtent:(id)extent;	// 0x30503455
- (void)setSelectionWithPoint:(CGPoint)point;	// 0x305009f1
- (void)setSelectionWithPoint:(CGPoint)point ignoringLargeBlocks:(BOOL)blocks;	// 0x30500a15
- (void)shrinkFromEdge:(int)edge;	// 0x30501a25
- (void)shrinkSelectionFromPoint:(CGPoint)point towardsPoint:(CGPoint)point2 withNewRect:(CGRect)newRect;	// 0x3050254d
- (id)textRepresentation;	// 0x30501049
// declared property getter: - (id)textSelection;	// 0x30503465
- (id)textSelectionRects;	// 0x30502b61
- (BOOL)tryToShrinkToBaseAndExtent;	// 0x305023ed
- (void)useBlock;	// 0x30502b35
// declared property getter: - (BOOL)valid;	// 0x30500e2d
- (id)webArchive;	// 0x30501091
- (id)webFrame;	// 0x30500ff9
- (id)webView;	// 0x30500fd1
@end

