/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ATVSlideshow.framework/ATVSlideshow
 */

#import "MRLayer.h"
#import "ATVSlideshow-Structs.h"

@class NSMutableDictionary, NSMutableArray, MRTransition, MCContainerSerializer, NSArray;

@interface MRLayerSerializer : MRLayer {
	MCContainerSerializer *mContainer;	// 120 = 0x78
	NSMutableArray *mSublayers;	// 124 = 0x7c
	NSMutableDictionary *mSublayersForPlugs;	// 128 = 0x80
	MRLayer *mCurrentSublayer;	// 132 = 0x84
	MRLayer *mNextSublayer;	// 136 = 0x88
	MRTransition *mCurrentTransition;	// 140 = 0x8c
	MRLayer *mSublayerForTransition;	// 144 = 0x90
	MRLayer *mSublayerToPrecompute;	// 148 = 0x94
	id mPrecomputingTarget;	// 152 = 0x98
	unsigned mPrecomputingType;	// 156 = 0x9c
	MRLayer *mLiveSourceSublayer;	// 160 = 0xa0
	MRLayer *mLiveTargetSublayer;	// 164 = 0xa4
	BOOL mLiveTransitionIsBackwards;	// 168 = 0xa8
	BOOL mIsTransitioning;	// 169 = 0xa9
	BOOL mNeedsToUpdateSublayersTiming;	// 170 = 0xaa
	BOOL mNeedsToUpdateTransitionAttributes;	// 171 = 0xab
	BOOL mHasWarnedDelegateAboutNearingEnd;	// 172 = 0xac
}
@property(readonly, assign) NSArray *sublayers;	// G=0x361004b9; @synthesize=mSublayers
- (id)initWithPlug:(id)plug andParameters:(id)parameters inSuperlayer:(id)superlayer;	// 0x360fd7e9
- (id)_createSublayerForPlug:(id)plug;	// 0x36100aa9
- (id)_currentState;	// 0x36100245
- (void)_deleteSublayer:(id)sublayer;	// 0x36100c05
- (id)_dumpLayerWithOptions:(unsigned)options;	// 0x36100331
- (void)_executeLayerCommandQueue;	// 0x361004cd
- (BOOL)_isNative3D;	// 0x360ff629
- (void)_observePlug;	// 0x36100fb5
- (void)_observePlugOnPreactivate;	// 0x361010b1
- (void)_observeSublayer:(id)sublayer;	// 0x36100dad
- (void)_observeSublayerOnPreactivate:(id)preactivate;	// 0x36100f11
- (void)_precomputeAtTime:(double)time inContext:(id)context withArguments:(id)arguments;	// 0x361012b5
- (void)_preprecomputeAtTime:(double)time inContext:(id)context withArguments:(id)arguments;	// 0x36102121
- (void)_prerenderSublayersAtTime:(double)time inContext:(id)context withArguments:(id)arguments;	// 0x36101931
- (void)_renderAtTime:(double)time inContext:(id)context withArguments:(id)arguments;	// 0x36101559
- (id)_retainedByUserRenderedImageAtTime:(double)time inContext:(id)context withArguments:(id)arguments;	// 0x36101715
- (void)_setNeedsToRequestRebuildAudio:(BOOL)requestRebuildAudio;	// 0x361011cd
- (void)_unobservePlug;	// 0x36101041
- (void)_unobservePlugOnDepreactivate;	// 0x3610114d
- (void)_unobserveSublayer:(id)sublayer;	// 0x36100e69
- (void)_unobserveSublayerOnDepreactivate:(id)depreactivate;	// 0x36100f65
- (void)_updateSublayersTiming;	// 0x36100891
- (id)actionForKey:(id)key recursive:(BOOL)recursive;	// 0x360ffb75
- (id)actionHitAtPoint:(CGPoint)point layer:(id *)layer;	// 0x360ff9e1
- (void)beginMorphingToAspectRatio:(float)aspectRatio withDuration:(double)duration;	// 0x360fe2a9
- (void)cleanup;	// 0x360fd975
- (void)deactivate;	// 0x360fe495
- (void)depreactivate:(BOOL)depreactivate;	// 0x360fe655
- (void)endMorphing;	// 0x360fe3b9
- (void)endTransitionToSublayer;	// 0x361001f1
- (BOOL)hasAudio;	// 0x360ff511
- (BOOL)hasSomethingToRender;	// 0x360fe195
- (BOOL)isAlphaFriendly;	// 0x360fe959
- (BOOL)isLoadedForTime:(double)time;	// 0x360fe775
- (BOOL)isOpaque;	// 0x360fe8e5
- (void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void *)context;	// 0x360fdc3d
- (id)patchworkAtTime:(double)time inContext:(id)context withArguments:(id)arguments;	// 0x360ff1dd
- (BOOL)prerenderForTime:(double)time inContext:(id)context withArguments:(id)arguments;	// 0x360fe9cd
- (void)setPixelSize:(CGSize)size;	// 0x360fe0ad
- (id)sublayerAtIndex:(unsigned)index;	// 0x360ff67d
- (id)sublayerForPlugObjectID:(id)plugObjectID recursive:(BOOL)recursive;	// 0x360ff7a5
- (id)sublayerHitAtPoint:(CGPoint)point onlyIfHitElement:(BOOL)element localPoint:(CGPoint *)point3;	// 0x360ff389
// declared property getter: - (id)sublayers;	// 0x361004b9
- (BOOL)supportsDynamicExpansion;	// 0x360ff385
- (void)synchronizeTime;	// 0x360fe21d
- (double)transitionToNextSublayer;	// 0x360ffcc9
- (double)transitionToPreviousSublayer;	// 0x360ffd89
- (double)transitionToSublayerAtIndex:(unsigned)index;	// 0x360ffe41
@end

