/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "Foundation-Structs.h"
#import <NSMutableData.h> // Unknown library


__attribute__((visibility("hidden")))
@interface NSCFData : NSMutableData {
@private
	unsigned char _cfinfo[4];	// 4 = 0x4
	long _length;	// 8 = 0x8
	long _capacity;	// 12 = 0xc
	CFAllocatorRef _bytesDeallocator;	// 16 = 0x10
	char *_bytes;	// 20 = 0x14
}
@property(assign) unsigned length;	// G=0x35e39171; S=0x35e3917d; converted property
+ (BOOL)automaticallyNotifiesObserversForKey:(id)key;	// 0x35e39115
- (BOOL)allowsWeakReference;	// 0x35e390a5
- (const void *)bytes;	// 0x35e39175
- (id)copyWithZone:(NSZone *)zone;	// 0x35e39119
- (void)finalize;	// 0x35e390d1
- (unsigned)hash;	// 0x35e3908d
- (BOOL)isEqual:(id)equal;	// 0x35e39075
// converted property getter: - (unsigned)length;	// 0x35e39171
- (void *)mutableBytes;	// 0x35e39179
- (oneway void)release;	// 0x35e390a1
- (id)retain;	// 0x35e39091
- (unsigned)retainCount;	// 0x35e390cd
- (BOOL)retainWeakReference;	// 0x35e390b9
// converted property setter: - (void)setLength:(unsigned)length;	// 0x35e3917d
@end

