/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import <NSObject.h> // Unknown library


@interface NSValueTransformer : NSObject {
}
+ (id)_transformerRegistry;	// 0x35e0d03d
+ (BOOL)allowsReverseTransformation;	// 0x35e7b971
+ (void)setValueTransformer:(id)transformer forName:(id)name;	// 0x35e0cf81
+ (Class)transformedValueClass;	// 0x35e7b96d
+ (id)valueTransformerForName:(id)name;	// 0x35e0daad
+ (id)valueTransformerNames;	// 0x35e7b8f1
- (id)reverseTransformedValue:(id)value;	// 0x35e7b979
- (id)transformedValue:(id)value;	// 0x35e7b975
@end

