/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NetflixNrdObjectProtocol.h"
#import "NetflixNrdObject.h"

@class NSArray;

@interface NetflixLog : NetflixNrdObject <NetflixNrdObjectProtocol> {
}
@property(copy) NSArray *traceAreas;	// G=0x5670c1; S=0x567165; 
+ (id)sharedInstance;	// 0x566fa9
- (id)init;	// 0x567095
- (void)debug:(id)debug;	// 0x5671e1
- (void)error:(id)error;	// 0x567209
- (void)fatal:(id)fatal;	// 0x56721d
- (BOOL)handleEvent:(id)event;	// 0x5672a5
- (void)info:(id)info;	// 0x5671f5
- (void)log:(unsigned)log message:(id)message;	// 0x5671b5
// declared property setter: - (void)setTraceAreas:(id)areas;	// 0x567165
- (void)trace:(id)trace;	// 0x567231
// declared property getter: - (id)traceAreas;	// 0x5670c1
@end

