/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRMediaPlayer;

__attribute__((visibility("hidden")))
@interface RUIRetailControl : BRControl {
	BRMediaPlayer *_player;	// 84 = 0x54
	BOOL _playbackStarted;	// 88 = 0x58
}
- (id)initWithMediaURL:(id)mediaURL;	// 0x4b0ef1
- (void).cxx_destruct;	// 0x4b13d9
- (void)_movieCued:(id)cued;	// 0x4b1475
- (void)_playerVisualsChanged:(id)changed;	// 0x4b1465
- (void)_updateVisuals;	// 0x4b13ed
- (void)controlWasActivated;	// 0x4b1109
- (void)controlWasDeactivated;	// 0x4b1255
- (void)dealloc;	// 0x4b109d
- (void)layoutSubcontrols;	// 0x4b12cd
@end

