/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
 */

#import "UIFoundation-Structs.h"
#import <UIFont.h> // Unknown library


@interface UIFont (UIFont_AttributedStringDrawing)
+ (id)fontWithCTFont:(CTFontRef)ctfont;	// 0x35ad3f05
+ (id)fontWithDescriptor:(CTFontDescriptorRef)descriptor size:(float)size;	// 0x35ad3dbd
+ (id)userFontOfSize:(float)size;	// 0x35ad3dad
- (CTFontRef)CTFont;	// 0x35ad3d89
- (CTFontDescriptorRef)CTFontDescriptor;	// 0x35ad3f89
- (float)_ascenderDeltaForBehavior:(int)behavior;	// 0x35ad4041
- (CGFontRef)_backingCGSFont;	// 0x35ad4319
- (float)_baseLineHeightForFont:(BOOL)font;	// 0x35ad3fd9
- (unsigned)_defaultGlyphForChar:(unsigned short)aChar;	// 0x35ad44b9
- (float)_defaultLineHeightForUILayout;	// 0x35ad45ed
- (id)_familyName;	// 0x35ad44a1
- (BOOL)_isDefaultFace;	// 0x35ad3da1
- (BOOL)_isHiraginoFont;	// 0x35ad3fbd
- (id)_kernOverride;	// 0x35ad4139
- (const unsigned short *)_latin1MappingTable:(bool *)table;	// 0x35ad44b1
- (float)_leading;	// 0x35ad3fc1
- (CGAffineTransform)_textMatrixTransformForContext:(CGContextRef)context;	// 0x35ad4045
- (float)_totalAdvancementForNativeGlyphs:(const unsigned short *)nativeGlyphs count:(long)count;	// 0x35ad4141
- (CGSize)advancementForGlyph:(unsigned)glyph;	// 0x35ad4359
- (id)bestMatchingFontForCharacters:(const unsigned short *)characters length:(unsigned)length attributes:(id)attributes actualCoveredLength:(unsigned *)length4;	// 0x35ad451d
- (CGRect)boundingRectForFont;	// 0x35ad431d
- (id)coveredCharacterSet;	// 0x35ad3d9d
- (CTFontRef)ctFontRef;	// 0x35ad3d8d
- (void)getAdvancements:(CGSize *)advancements forGlyphs:(const unsigned *)glyphs count:(unsigned)count;	// 0x35ad417d
- (void)getAdvancements:(CGSize *)advancements forPackedGlyphs:(const void *)packedGlyphs length:(unsigned)length;	// 0x35ad42e5
- (void)getBoundingRects:(CGRect *)rects forCGGlyphs:(const unsigned short *)cgglyphs count:(unsigned)count;	// 0x35ad44ed
- (unsigned)getCaretPositions:(float *)positions forGlyph:(unsigned)glyph maximumLength:(unsigned)length;	// 0x35ad4449
- (unsigned)glyphWithName:(id)name;	// 0x35ad3f69
- (unsigned)hyphenGlyphForLocale:(id)locale;	// 0x35ad43f9
- (BOOL)isVertical;	// 0x35ad3fb9
- (id)lastResortFont;	// 0x35ad45a9
- (unsigned)numberOfGlyphs;	// 0x35ad3f4d
- (unsigned)renderingMode;	// 0x35ad413d
- (id)screenFontWithRenderingMode:(unsigned)renderingMode;	// 0x35ad43f5
- (void)setInContext:(CGContextRef)context;	// 0x35ad40a9
- (float)underlineThickness;	// 0x35ad4355
- (id)verticalFont;	// 0x35ad3fb5
@end

