/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SADomainObjectCommand.h"
#import "SABaseClientBoundCommand.h"

@class SADomainObject;

@interface SADomainObjectUpdate : SABaseClientBoundCommand <SADomainObjectCommand> {
}
@property(retain, nonatomic) SADomainObject *addFields;	// G=0x326ee021; S=0x326ee065; 
@property(retain, nonatomic) SADomainObject *identifier;	// G=0x326ee0a1; S=0x326ee0e5; 
@property(retain, nonatomic) SADomainObject *removeFields;	// G=0x326ee121; S=0x326ee165; 
@property(retain, nonatomic) SADomainObject *setFields;	// G=0x326ee1a1; S=0x326ee1e5; 
+ (id)domainObjectUpdate;	// 0x326edf91
+ (id)domainObjectUpdateWithDictionary:(id)dictionary context:(id)context;	// 0x326edfd5
// declared property getter: - (id)addFields;	// 0x326ee021
- (id)encodedClassName;	// 0x326edf85
- (id)groupIdentifier;	// 0x326edf75
// declared property getter: - (id)identifier;	// 0x326ee0a1
// declared property getter: - (id)removeFields;	// 0x326ee121
- (BOOL)requiresResponse;	// 0x326ee221
// declared property setter: - (void)setAddFields:(id)fields;	// 0x326ee065
// declared property getter: - (id)setFields;	// 0x326ee1a1
// declared property setter: - (void)setIdentifier:(id)identifier;	// 0x326ee0e5
// declared property setter: - (void)setRemoveFields:(id)fields;	// 0x326ee165
// declared property setter: - (void)setSetFields:(id)fields;	// 0x326ee1e5
@end

