/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SADomainObject.h"

@class SALocalSearchBusiness2, NSArray;

@interface SAMovieV2MovieTheater : SADomainObject {
}
@property(retain, nonatomic) SALocalSearchBusiness2 *business;	// G=0x326a5f01; S=0x326a5f45; 
@property(copy, nonatomic) NSArray *movies;	// G=0x326a5f81; S=0x326a5fe9; 
+ (id)movieTheater;	// 0x326a5e71
+ (id)movieTheaterWithDictionary:(id)dictionary context:(id)context;	// 0x326a5eb5
// declared property getter: - (id)business;	// 0x326a5f01
- (id)encodedClassName;	// 0x326a5e65
- (id)groupIdentifier;	// 0x326a5e55
// declared property getter: - (id)movies;	// 0x326a5f81
// declared property setter: - (void)setBusiness:(id)business;	// 0x326a5f45
// declared property setter: - (void)setMovies:(id)movies;	// 0x326a5fe9
- (void)updateUsingSet:(id)set add:(id)add remove:(id)remove;	// 0x326a6051
@end

