/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ATVSlideshow.framework/ATVSlideshow
 */

#import "MCAnimationPathSupport.h"
#import "MCActionSupport.h"
#import "MCObject.h"

@class MCContainer, NSSet, NSDictionary, NSMutableSet, NSMutableDictionary;

@interface MCPlug : MCObject <MCAnimationPathSupport, MCActionSupport> {
	unsigned long mFlags;	// 16 = 0x10
	NSMutableSet *mAnimationPaths;	// 20 = 0x14
	NSMutableDictionary *mActions;	// 24 = 0x18
	MCContainer *mContainer;	// 28 = 0x1c
	double mPhaseInDuration;	// 32 = 0x20
	double mLoopDuration;	// 40 = 0x28
	double mPhaseOutDuration;	// 48 = 0x30
	double mNumberOfLoops;	// 56 = 0x38
}
@property(readonly, assign) NSDictionary *actions;	// G=0x334cf831; 
@property(readonly, assign) NSSet *animationPaths;	// G=0x334ce531; 
@property(retain) MCContainer *container;	// G=0x334cd63d; S=0x334cd741; @synthesize=mContainer
@property(readonly, assign, nonatomic) unsigned countOfActions;	// G=0x334cf981; 
@property(readonly, assign) unsigned countOfAnimationPaths;	// G=0x334ce681; 
@property(readonly, assign, nonatomic) double fullDuration;	// G=0x334cd919; 
@property(assign, nonatomic) double loopDuration;	// G=0x334cdef5; S=0x334cd8a9; @synthesize=mLoopDuration
@property(assign, nonatomic) double numberOfLoops;	// G=0x334cdf25; S=0x334cd975; @synthesize=mNumberOfLoops
@property(assign, nonatomic) double phaseInDuration;	// G=0x334cdedd; S=0x334cd871; @synthesize=mPhaseInDuration
@property(assign, nonatomic) double phaseOutDuration;	// G=0x334cdf0d; S=0x334cd8e1; @synthesize=mPhaseOutDuration
@property(assign, nonatomic) BOOL preactivatesWithParent;	// G=0x334cd9d9; S=0x334cd9ed; 
@property(assign, nonatomic) BOOL startsPaused;	// G=0x334cd9a1; S=0x334cd9b5; 
+ (id)keyPathsForValuesAffectingValueForKey:(id)key;	// 0x334ccf31
- (id)init;	// 0x334cd00d
- (void)initActionsWithImprints:(id)imprints;	// 0x334cf3d5
- (void)initAnimationPathsWithImprints:(id)imprints;	// 0x334cdf3d
- (id)initWithImprint:(id)imprint andMontage:(id)montage;	// 0x334cd059
- (void)_copySelfToSnapshot:(id)snapshot;	// 0x334cda11
- (id)actionForKey:(id)key;	// 0x334cfa85
// declared property getter: - (id)actions;	// 0x334cf831
- (void)addAnimationPath:(id)path;	// 0x334cea55
- (id)animationPathForKey:(id)key;	// 0x334ce785
// declared property getter: - (id)animationPaths;	// 0x334ce531
// declared property getter: - (id)container;	// 0x334cd63d
// declared property getter: - (unsigned)countOfActions;	// 0x334cf981
// declared property getter: - (unsigned)countOfAnimationPaths;	// 0x334ce681
- (void)demolish;	// 0x334cd2a9
- (void)demolishActions;	// 0x334cf531
- (void)demolishAnimationPaths;	// 0x334ce161
// declared property getter: - (double)fullDuration;	// 0x334cd919
- (id)imprint;	// 0x334cd311
- (id)imprintsForActions;	// 0x334cf719
- (id)imprintsForAnimationPaths;	// 0x334ce431
// declared property getter: - (double)loopDuration;	// 0x334cdef5
// declared property getter: - (double)numberOfLoops;	// 0x334cdf25
- (void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void *)context;	// 0x334cd5d1
// declared property getter: - (double)phaseInDuration;	// 0x334cdedd
// declared property getter: - (double)phaseOutDuration;	// 0x334cdf0d
// declared property getter: - (BOOL)preactivatesWithParent;	// 0x334cd9d9
- (void)removeActionForKey:(id)key;	// 0x334cfd2d
- (void)removeAllActions;	// 0x334cfe3d
- (void)removeAllAnimationPaths;	// 0x334cf091
- (void)removeAnimationPathForKey:(id)key;	// 0x334ced25
- (void)setAction:(id)action forKey:(id)key;	// 0x334cfbb9
- (void)setAnimationPath:(id)path forKey:(id)key;	// 0x334cdd1d
// declared property setter: - (void)setContainer:(id)container;	// 0x334cd741
// declared property setter: - (void)setLoopDuration:(double)duration;	// 0x334cd8a9
// declared property setter: - (void)setNumberOfLoops:(double)loops;	// 0x334cd975
// declared property setter: - (void)setPhaseInDuration:(double)duration;	// 0x334cd871
// declared property setter: - (void)setPhaseOutDuration:(double)duration;	// 0x334cd8e1
// declared property setter: - (void)setPreactivatesWithParent:(BOOL)parent;	// 0x334cd9ed
// declared property setter: - (void)setStartsPaused:(BOOL)paused;	// 0x334cd9b5
// declared property getter: - (BOOL)startsPaused;	// 0x334cd9a1
@end

