/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import "NSCopying.h"
#import <NSObject.h> // Unknown library


__attribute__((visibility("hidden")))
@interface TSUColor : NSObject <NSCopying> {
@private
	CGColorRef mCGColor;	// 4 = 0x4
}
@property(readonly, assign) CGColorRef CGColor;	// G=0x313b55b1; @synthesize=mCGColor
+ (id)blackColor;	// 0x313b597d
+ (id)blueColor;	// 0x313b57e1
+ (id)brownColor;	// 0x313b560d
+ (id)clearColor;	// 0x313b59bd
+ (id)colorWithCGColor:(CGColorRef)cgcolor;	// 0x313b5abd
+ (id)colorWithCalibratedHue:(float)calibratedHue saturation:(float)saturation brightness:(float)brightness alpha:(float)alpha;	// 0x313b2ced
+ (id)colorWithCalibratedRed:(float)calibratedRed green:(float)green blue:(float)blue alpha:(float)alpha;	// 0x313b2ccd
+ (id)colorWithRed:(float)red green:(float)green blue:(float)blue alpha:(float)alpha;	// 0x313b5a6d
+ (id)colorWithWhite:(float)white alpha:(float)alpha;	// 0x313b5a2d
+ (id)cyanColor;	// 0x313b5799
+ (id)grayColor;	// 0x313b58fd
+ (id)greenColor;	// 0x313b5829
+ (id)lightGrayColor;	// 0x313b58b9
+ (id)magentaColor;	// 0x313b5705
+ (id)orangeColor;	// 0x313b56b5
+ (id)purpleColor;	// 0x313b5669
+ (id)randomColor;	// 0x313b59f9
+ (id)redColor;	// 0x313b5871
+ (id)whiteColor;	// 0x313b593d
+ (id)yellowColor;	// 0x313b574d
- (id)initWithCGColor:(CGColorRef)cgcolor;	// 0x313b55c1
- (id)initWithRed:(float)red green:(float)green blue:(float)blue alpha:(float)alpha;	// 0x313b6169
- (id)initWithWhite:(float)white alpha:(float)alpha;	// 0x313b6119
// declared property getter: - (CGColorRef)CGColor;	// 0x313b55b1
- (float)alphaComponent;	// 0x313b5f15
- (id)blendedColorWithFraction:(float)fraction ofColor:(id)color;	// 0x313b5b85
- (float)blueComponent;	// 0x313b5f31
- (id)colorWithAlphaComponent:(float)alphaComponent;	// 0x313b5db9
- (id)copy;	// 0x313b2c7d
- (id)copyWithZone:(NSZone *)zone;	// 0x313b6011
- (void)dealloc;	// 0x313b60d9
- (id)grayscaleColor;	// 0x313b5e6d
- (float)greenComponent;	// 0x313b5f45
- (unsigned)hash;	// 0x313b60bd
- (id)invertedColor;	// 0x313b5dfd
- (BOOL)isEqual:(id)equal;	// 0x313b603d
- (BOOL)isOpaque;	// 0x313b5cf9
- (float)luminance;	// 0x313b5d29
- (float)p_rgbComponentWithIndex:(unsigned char)index;	// 0x313b5f6d
- (void)paintPath:(CGPathRef)path inContext:(CGContextRef)context;	// 0x313b5af9
- (void)paintRect:(CGRect)rect inContext:(CGContextRef)context;	// 0x313b5b35
- (float)redComponent;	// 0x313b5f59
- (void)set;	// 0x313b2c79
@end

