/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <NSObject.h> // Unknown library
#import "OfficeImport-Structs.h"


__attribute__((visibility("hidden")))
@interface WBDocument : NSObject {
}
+ (void)addImageBullets:(id)bullets;	// 0x31350b6d
+ (id)imageBulletParagraph:(id)paragraph;	// 0x313509d1
+ (id)readFrom:(id)from;	// 0x311fed69
+ (void)readNoteSeparatorFrom:(id)from type:(int)type separator:(id)separator;	// 0x31219231
+ (void)readProperties:(id)properties document:(id)document;	// 0x31206d75
+ (void)readSectionsFrom:(id)from document:(id)document;	// 0x31212b89
+ (void)readTextBoxesFrom:(id)from;	// 0x31219191
+ (void)setTimeStamp:(WrdDocumentProperties *)stamp;	// 0x31350a41
+ (unsigned)setupZIndices:(id)indices document:(id)document escherType:(int)type;	// 0x3121d6f1
- (id)init;	// 0x313509a5
- (id)applicationName;	// 0x31350999
@end

