/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "CPTracing.h"


@interface CPImportTracing : CPTracing {
}
- (id)initWithFilename:(id)filename;	// 0x34b06fe1
- (void)dealloc;	// 0x34b0700d
- (void)startImporting;	// 0x34b07049
- (void)startProcessors;	// 0x34b07041
- (void)startReading;	// 0x34b07039
- (void)stopImporting;	// 0x34b0704d
- (void)stopProcessors;	// 0x34b07045
- (void)stopReading;	// 0x34b0703d
@end

