/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRController.h"
#import "AppleTV-Structs.h"

@class BRHeaderControl, BRTextControl, NSString, BRWaitSpinnerControl;

__attribute__((visibility("hidden")))
@interface ATVAPDirectedScanController : BRController {
@private
	BRWaitSpinnerControl *_spinner;	// 80 = 0x50
	NSString *_networkName;	// 84 = 0x54
	BRHeaderControl *_header;	// 88 = 0x58
	BRTextControl *_prompt;	// 92 = 0x5c
}
- (id)initWithNetworkName:(id)networkName;	// 0x35d5e1b1
- (void)dealloc;	// 0x35d5e38d
- (void)setFrame:(CGRect)frame;	// 0x35d5e415
@end

