/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSURLProtocol.h> // Unknown library


__attribute__((visibility("hidden")))
@interface NfhlsProtocol : NSURLProtocol {
}
+ (BOOL)canInitWithRequest:(id)request;	// 0x36070994
+ (id)canonicalRequestForRequest:(id)request;	// 0x36070978
+ (id)protocolScheme;	// 0x36070980
+ (void)registerProtocol;	// 0x36070a7c
+ (void)setDebug:(BOOL)debug;	// 0x36070964
+ (void)unregisterProtocol;	// 0x36070a0c
- (void)startLoading;	// 0x36070aec
- (void)stopLoading;	// 0x36070990
@end

