/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface UIInputSwitcherShadowView : UIView {
	int m_mode;	// 84 = 0x54
	float m_pointerOffset;	// 88 = 0x58
	NSArray *m_gradientColors;	// 92 = 0x5c
}
@property(retain, nonatomic) NSArray *gradientColors;	// G=0x31faff99; S=0x31faffa9; @synthesize=m_gradientColors
@property(assign, nonatomic) int mode;	// G=0x31d38361; S=0x31faff69; @synthesize=m_mode
@property(assign, nonatomic) float pointerOffset;	// G=0x31faff79; S=0x31faff89; @synthesize=m_pointerOffset
- (id)initWithFrame:(CGRect)frame;	// 0x31d381c9
- (void)dealloc;	// 0x31faf9b1
- (void)drawRect:(CGRect)rect;	// 0x31fafa01
// declared property getter: - (id)gradientColors;	// 0x31faff99
// declared property getter: - (int)mode;	// 0x31d38361
// declared property getter: - (float)pointerOffset;	// 0x31faff79
- (void)setFrame:(CGRect)frame;	// 0x31d382d5
// declared property setter: - (void)setGradientColors:(id)colors;	// 0x31faffa9
// declared property setter: - (void)setMode:(int)mode;	// 0x31faff69
// declared property setter: - (void)setPointerOffset:(float)offset;	// 0x31faff89
@end

