/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"
#import "_UIShadowedView.h"

@class UIImageView, NSArray, UITabBarItem, UIColor, NSMutableArray, UIImage;
@protocol UITabBarDelegate;

@interface UITabBar : UIView <_UIShadowedView> {
	UIView *_customizeView;	// 84 = 0x54
	UIView *_backgroundView;	// 88 = 0x58
	UIImageView *_shadowView;	// 92 = 0x5c
	id<UITabBarDelegate> _delegate;	// 96 = 0x60
	NSArray *_items;	// 100 = 0x64
	UITabBarItem *_selectedItem;	// 104 = 0x68
	NSArray *_customizationItems;	// 108 = 0x6c
	struct {
		unsigned pushedRunLoop : 1;
		unsigned isRotatingRight : 1;
		unsigned isZoomRubberBandEnabled : 1;
		unsigned zoomsFromCurrentToMinOrMax : 1;
		unsigned updatesScroller : 1;
		unsigned isAnimatingZoomFailure : 1;
	} _tabBarFlags;	// 112 = 0x70
	NSArray *_buttonItems;	// 116 = 0x74
	CFArrayRef _hiddenItems;	// 120 = 0x78
	id _appearanceStorage;	// 124 = 0x7c
	float _nextSelectionSlideDuration;	// 128 = 0x80
	float _tabButtonWidth;	// 132 = 0x84
	float _interTabButtonSpacing;	// 136 = 0x88
	BOOL _dividerImagesChangeWithSelection;	// 140 = 0x8c
	BOOL _dividerImagesAreInvalid;	// 141 = 0x8d
	NSMutableArray *_dividerImageViews;	// 144 = 0x90
}
@property(retain, nonatomic, setter=_setBackgroundView:) UIView *_backgroundView;	// G=0x31e5f2a1; S=0x31e5f231; 
@property(retain, nonatomic, setter=_setDividerImageViews:) NSMutableArray *_dividerImageViews;	// G=0x31e60fc1; S=0x31e60fd1; @synthesize
@property(assign, nonatomic, setter=_setDividerImagesAreInvalid:) BOOL _dividerImagesAreInvalid;	// G=0x31e60fa1; S=0x31e60fb1; @synthesize
@property(assign, nonatomic, setter=_setDividerImagesChangeWithSelection:) BOOL _dividerImagesChangeWithSelection;	// G=0x31e60f81; S=0x31e60f91; @synthesize
@property(assign, nonatomic, setter=_setInterTabButtonSpacing:) float _interTabButtonSpacing;	// G=0x31e60f61; S=0x31e60f71; @synthesize
@property(assign, nonatomic, setter=_setNextSelectionSlideDuration:) float _nextSelectionSlideDuration;	// G=0x31e60f21; S=0x31e60f31; @synthesize
@property(assign, nonatomic, setter=_setTabButtonWidth:) float _tabButtonWidth;	// G=0x31e60f41; S=0x31e60f51; @synthesize
@property(retain, nonatomic) UIImage *backgroundImage;	// G=0x31e60b7d; S=0x31c9a259; 
@property(retain) NSArray *buttonItems;	// G=0x31e6156d; S=0x31e6157d; converted property
@property(assign, nonatomic) id<UITabBarDelegate> delegate;	// G=0x31e60f11; S=0x31c67eed; @synthesize=_delegate
@property(copy, nonatomic) NSArray *items;	// G=0x31c6dc51; S=0x31e5fe3d; 
@property(assign, getter=isLocked) BOOL locked;	// G=0x31c14df5; S=0x31c147a9; converted property
@property(retain, nonatomic) UIColor *selectedImageTintColor;	// G=0x31e60ecd; S=0x31e60e25; 
@property(assign, nonatomic) UITabBarItem *selectedItem;	// G=0x31c98785; S=0x31c6b95d; 
@property(retain, nonatomic) UIImage *selectionIndicatorImage;	// G=0x31e60bc1; S=0x31c9a3b1; 
@property(retain, nonatomic) UIImage *shadowImage;	// G=0x31e60ba1; S=0x31c9a5a5; 
@property(retain, nonatomic) UIColor *tintColor;	// G=0x31c69ab5; S=0x31e60d6d; 
+ (float)_buttonGap;	// 0x31e615c1
+ (float)defaultHeightForBarSize:(int)barSize;	// 0x31e60fe1
- (id)initWithCoder:(id)coder;	// 0x31e5f839
- (id)initWithFrame:(CGRect)frame;	// 0x31c6756d
- (void)_activityViewControllerIsAppearing:(id)appearing;	// 0x31d6be8d
- (void)_activityViewControllerIsDisappearing:(id)disappearing;	// 0x31d785d1
- (void)_adjustButtonSelection:(id)selection;	// 0x31d0b4c9
- (void)_alertDidHide;	// 0x31e618c1
- (void)_alertWillShow:(BOOL)_alert duration:(float)duration;	// 0x31e615c9
- (void)_animateSelectionChangeFromView:(id)view toView:(id)view2 duration:(float)duration;	// 0x31e5fe71
- (id)_appearanceStorage;	// 0x31c69aa1
- (float)_autolayoutSpacingAtEdge:(int)edge inContainer:(id)container;	// 0x320134fd
- (float)_autolayoutSpacingAtEdge:(int)edge nextToNeighbor:(id)neighbor;	// 0x32013515
// declared property getter: - (id)_backgroundView;	// 0x31e5f2a1
- (void)_buttonCancel:(id)cancel;	// 0x31e61969
- (void)_buttonDown:(id)down;	// 0x31d0b3f5
- (void)_buttonDownDelayed:(id)delayed;	// 0x31e61921
- (void)_buttonUp:(id)up;	// 0x31d0b449
- (BOOL)_canDrawContent;	// 0x31c6763d
- (void)_configureTabBarReplacingItem:(id)item withNewItem:(id)newItem dragging:(BOOL)dragging swapping:(BOOL)swapping;	// 0x31e623b1
- (BOOL)_contentHuggingDefault_isUsuallyFixedHeight;	// 0x31e60879
- (void)_customizeDoneButtonAction:(id)action;	// 0x31e61ba1
- (void)_customizeWithAvailableItems:(id)availableItems;	// 0x31e61d19
- (void)_didMoveFromWindow:(id)window toWindow:(id)window2;	// 0x31c6ed51
- (void)_dismissCustomizeSheet:(BOOL)sheet;	// 0x31e619a1
- (id)_dividerImageForLeftButtonState:(unsigned)leftButtonState rightButtonState:(unsigned)state;	// 0x31e60ef1
// declared property getter: - (id)_dividerImageViews;	// 0x31e60fc1
// declared property getter: - (BOOL)_dividerImagesAreInvalid;	// 0x31e60fa1
// declared property getter: - (BOOL)_dividerImagesChangeWithSelection;	// 0x31e60f81
- (void)_finishCustomizeAnimation:(id)animation;	// 0x31e61bb5
- (void)_finishSetItems:(id)items finished:(id)finished context:(void *)context;	// 0x31c15be1
- (BOOL)_hasCustomAutolayoutNeighborSpacing;	// 0x320134f9
- (void)_hideItemsAnimated:(BOOL)animated;	// 0x31e6041d
// declared property getter: - (float)_interTabButtonSpacing;	// 0x31e60f61
- (CGSize)_intrinsicSizeWithinSize:(CGSize)size;	// 0x31c67e8d
- (void)_invalidateDividerImages;	// 0x31c9ac25
- (BOOL)_isHidden:(id)hidden;	// 0x31e6264d
// declared property getter: - (float)_nextSelectionSlideDuration;	// 0x31e60f21
- (void)_populateArchivedSubviews:(id)subviews;	// 0x31e5f991
- (void)_positionTabBarButtons:(id)buttons ignoringItem:(id)item;	// 0x31c14e91
- (void)_sendAction:(id)action withEvent:(id)event;	// 0x31d0b5f5
- (void)_setBackgroundImage:(id)image;	// 0x31e5f2b1
// declared property setter: - (void)_setBackgroundView:(id)view;	// 0x31e5f231
- (void)_setDividerImage:(id)image forLeftButtonState:(unsigned)leftButtonState rightButtonState:(unsigned)state;	// 0x31c9a8d9
// declared property setter: - (void)_setDividerImageViews:(id)views;	// 0x31e60fd1
// declared property setter: - (void)_setDividerImagesAreInvalid:(BOOL)invalid;	// 0x31e60fb1
// declared property setter: - (void)_setDividerImagesChangeWithSelection:(BOOL)selection;	// 0x31e60f91
// declared property setter: - (void)_setInterTabButtonSpacing:(float)spacing;	// 0x31e60f71
- (void)_setLabelFont:(id)font;	// 0x31e5f2c1
- (void)_setLabelShadowColor:(id)color;	// 0x31e5f581
- (void)_setLabelShadowOffset:(CGSize)offset;	// 0x31e5f6c9
- (void)_setLabelTextColor:(id)color selectedTextColor:(id)color2;	// 0x31e5f409
// declared property setter: - (void)_setNextSelectionSlideDuration:(float)duration;	// 0x31e60f31
- (void)_setSelectionIndicatorImage:(id)image;	// 0x31c9a3a1
// declared property setter: - (void)_setTabButtonWidth:(float)width;	// 0x31e60f51
- (id)_shadowView;	// 0x31d5cff5
- (void)_showItemsAnimated:(BOOL)animated;	// 0x31e60729
- (BOOL)_subclassImplementsDrawRect;	// 0x31c675bd
- (void)_tabBarFinishedAnimating;	// 0x31e61005
// declared property getter: - (float)_tabButtonWidth;	// 0x31e60f41
- (id)_topmostDividerImageView;	// 0x31e5fe51
- (void)_updateAppearanceCustomizationIfNecessaryForItem:(id)item;	// 0x31e62251
- (void)_updateBackgroundImage;	// 0x31c67775
- (void)_updateDividerImagesIfNecessary;	// 0x31c159f1
- (void)_updateTintedImages:(id)images selected:(BOOL)selected;	// 0x31e60be1
- (void)addConstraint:(id)constraint;	// 0x31e608fd
// declared property getter: - (id)backgroundImage;	// 0x31e60b7d
- (void)beginCustomizingItems:(id)items;	// 0x31e60a01
// converted property getter: - (id)buttonItems;	// 0x31e6156d
- (void)dealloc;	// 0x31e5fc21
// declared property getter: - (id)delegate;	// 0x31e60f11
- (void)dismissCustomizeSheet:(BOOL)sheet;	// 0x31e61025
- (void)drawRect:(CGRect)rect;	// 0x31e61359
- (void)encodeWithCoder:(id)coder;	// 0x31e5fae1
- (BOOL)endCustomizingAnimated:(BOOL)animated;	// 0x31e60af9
- (id)hitTest:(CGPoint)test forEvent:(GSEventRef)event;	// 0x31e625e5
- (id)hitTest:(CGPoint)test withEvent:(id)event;	// 0x31d0b359
- (BOOL)isCustomizing;	// 0x31d5a129
- (BOOL)isElementAccessibilityExposedToInterfaceBuilder;	// 0x31e70a5d
// converted property getter: - (BOOL)isLocked;	// 0x31c14df5
// declared property getter: - (id)items;	// 0x31c6dc51
- (void)layoutSubviews;	// 0x31c6f299
- (void)removeConstraint:(id)constraint;	// 0x31e6097d
// declared property getter: - (id)selectedImageTintColor;	// 0x31e60ecd
// declared property getter: - (id)selectedItem;	// 0x31c98785
// declared property getter: - (id)selectionIndicatorImage;	// 0x31e60bc1
- (void)setAutoresizingMask:(unsigned)mask;	// 0x31c67e9d
// declared property setter: - (void)setBackgroundImage:(id)image;	// 0x31c9a259
- (void)setBadgeAnimated:(BOOL)animated forButton:(int)button;	// 0x31e61251
- (void)setBadgeGlyph:(id)glyph forButton:(int)button;	// 0x31e611fd
- (void)setBadgeValue:(id)value forButton:(int)button;	// 0x31e611a9
- (void)setBounds:(CGRect)bounds;	// 0x31e612a9
// converted property setter: - (void)setButtonItems:(id)items;	// 0x31e6157d
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x31c67eed
- (void)setFrame:(CGRect)frame;	// 0x31c67689
// declared property setter: - (void)setItems:(id)items;	// 0x31e5fe3d
- (void)setItems:(id)items animated:(BOOL)animated;	// 0x31c147e1
// converted property setter: - (void)setLocked:(BOOL)locked;	// 0x31c147a9
// declared property setter: - (void)setSelectedImageTintColor:(id)color;	// 0x31e60e25
// declared property setter: - (void)setSelectedItem:(id)item;	// 0x31c6b95d
// declared property setter: - (void)setSelectionIndicatorImage:(id)image;	// 0x31c9a3b1
// declared property setter: - (void)setShadowImage:(id)image;	// 0x31c9a5a5
// declared property setter: - (void)setTintColor:(id)color;	// 0x31e60d6d
- (void)setTranslatesAutoresizingMaskIntoConstraints:(BOOL)constraints;	// 0x31e6087d
// declared property getter: - (id)shadowImage;	// 0x31e60ba1
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x31c67dc5
// declared property getter: - (id)tintColor;	// 0x31c69ab5
- (void)touchesBegan:(id)began withEvent:(id)event;	// 0x31e61049
- (void)touchesCancelled:(id)cancelled withEvent:(id)event;	// 0x31e61151
- (void)touchesEnded:(id)ended withEvent:(id)event;	// 0x31e610f9
- (void)touchesMoved:(id)moved withEvent:(id)event;	// 0x31e610a1
@end

