/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UINavigationController.h"

@class NSMutableDictionary, NSString;
@protocol UINavigationControllerDelegate, UIVideoEditorControllerDelegate;

@interface UIVideoEditorController : UINavigationController {
	int _previousStatusBarStyle;	// 288 = 0x120
	NSMutableDictionary *_properties;	// 292 = 0x124
	struct {
		unsigned clearsSelectionOnViewWillAppear : 1;
		unsigned insetsApplied : 1;
		unsigned adjustingInsets : 1;
	} _flags;	// 296 = 0x128
}
@property(assign, nonatomic) id<UINavigationControllerDelegate, UIVideoEditorControllerDelegate> delegate;	// @dynamic
@property(assign, nonatomic) double videoMaximumDuration;	// G=0x31ed711d; S=0x31ed7155; 
@property(copy, nonatomic) NSString *videoPath;	// G=0x31ed70e5; S=0x31ed7101; 
@property(assign, nonatomic) int videoQuality;	// G=0x31ed719d; S=0x31ed71d5; 
+ (BOOL)canEditVideoAtPath:(id)path;	// 0x31ed6989
- (id)init;	// 0x31ed69bd
- (void)_autoDismiss;	// 0x31ed6f15
- (id)_createInitialController;	// 0x31ed6e25
- (BOOL)_didRevertStatusBar;	// 0x31ed6d65
- (void)_initializeProperties;	// 0x31ed7281
- (BOOL)_isSupportedInterfaceOrientation:(int)orientation;	// 0x31ed6d79
- (id)_properties;	// 0x31ed7369
- (void)_removeAllChildren;	// 0x31ed6d85
- (void)_setProperties:(id)properties;	// 0x31ed721d
- (void)_setValue:(id)value forProperty:(id)property;	// 0x31ed73b9
- (void)_setupControllers;	// 0x31ed6e8d
- (id)_valueForProperty:(id)property;	// 0x31ed7429
- (void)editVideoViewController:(id)controller didFailWithError:(id)error;	// 0x31ed706d
- (void)editVideoViewController:(id)controller didTrimVideoWithOptions:(id)options;	// 0x31ed6fa9
- (void)editVideoViewControllerDidCancel:(id)editVideoViewController;	// 0x31ed6f41
// declared property setter: - (void)setVideoMaximumDuration:(double)duration;	// 0x31ed7155
// declared property setter: - (void)setVideoPath:(id)path;	// 0x31ed7101
// declared property setter: - (void)setVideoQuality:(int)quality;	// 0x31ed71d5
// declared property getter: - (double)videoMaximumDuration;	// 0x31ed711d
// declared property getter: - (id)videoPath;	// 0x31ed70e5
// declared property getter: - (int)videoQuality;	// 0x31ed719d
- (void)viewDidDisappear:(BOOL)view;	// 0x31ed6cd1
- (void)viewWillAppear:(BOOL)view;	// 0x31ed6a9d
- (void)viewWillDisappear:(BOOL)view;	// 0x31ed6b59
- (void)viewWillUnload;	// 0x31ed6a21
@end

