/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import "iWorkImport-Structs.h"
#import <NSObject.h> // Unknown library


@interface GQDChartModel : NSObject {
	CFArrayRef mChartData;	// 4 = 0x4
	CFArrayRef mColumnNames;	// 8 = 0x8
	CFArrayRef mRowNames;	// 12 = 0xc
	CFDictionaryRef mPropertyBag;	// 16 = 0x10
	long mDirection;	// 20 = 0x14
	CFStringRef mTitle;	// 24 = 0x18
	CFStringRef mCatagoryTitle;	// 28 = 0x1c
	CFStringRef mValueTitle;	// 32 = 0x20
	CFStringRef mValue2Title;	// 36 = 0x24
	CFBundleRef mProcessorBundle;	// 40 = 0x28
	BOOL mIsFormulaChart;	// 44 = 0x2c
}
- (CFStringRef)catagoryTitle;	// 0x3580a231
- (CFArrayRef)chartData;	// 0x3580a04d
- (CFArrayRef)columnNames;	// 0x3580a05d
- (void)dealloc;	// 0x3580a30d
- (long)direction;	// 0x3580a1dd
- (BOOL)hasFloatValueForProperty:(CFStringRef)property forSeriesAtIndex:(long)index value:(float *)value;	// 0x3580a1a5
- (BOOL)hasIntValueForProperty:(CFStringRef)property forSeriesAtIndex:(long)index value:(int *)value;	// 0x3580a16d
- (BOOL)hasStringValueForProperty:(CFStringRef)property forSeriesAtIndex:(long)index value:(const CFStringRef *)value;	// 0x3580a139
- (BOOL)hasValueForProperty:(CFStringRef)property forSeriesAtIndex:(long)index value:(const void **)value;	// 0x3580a0f1
- (BOOL)isFormulaChart;	// 0x3580a2fd
- (CFDictionaryRef)propertiesForSeriesAtIndex:(long)index;	// 0x3580a0b9
- (CFDictionaryRef)propertyBag;	// 0x3580a07d
- (CFArrayRef)rowNames;	// 0x3580a06d
- (CFArrayRef)seriesArray;	// 0x3580a08d
- (void)setProcessorBundle:(CFBundleRef)bundle;	// 0x3580a4d9
- (CFStringRef)title;	// 0x3580a1ed
- (void)transpose;	// 0x3580a3ed
- (CFStringRef)value2Title;	// 0x3580a2b9
- (CFStringRef)valueTitle;	// 0x3580a275
@end

