/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Symbolication.framework/Symbolication
 */

#import <NSObject.h> // Unknown library


@interface VMULoadCommand : NSObject {
	unsigned long long _cmdSize;	// 4 = 0x4
	unsigned _command;	// 12 = 0xc
}
@property(readonly, assign) unsigned long long cmdSize;	// G=0x30bb3bdd; converted property
+ (id)loadCommandWithMemory:(id)memory;	// 0x30bb3cb1
- (id)initWithMemory:(id)memory;	// 0x30bb3c19
// converted property getter: - (unsigned long long)cmdSize;	// 0x30bb3bdd
- (BOOL)isDyLinker;	// 0x30bb3c01
- (BOOL)isDySymTab;	// 0x30bb3bfd
- (BOOL)isIDDyLib;	// 0x30bb3c09
- (BOOL)isLoadDyLib;	// 0x30bb3c05
- (BOOL)isSegment;	// 0x30bb3c0d
- (BOOL)isSegment32;	// 0x30bb3c11
- (BOOL)isSegment64;	// 0x30bb3c15
- (BOOL)isSymTab;	// 0x30bb3bf9
- (BOOL)isUUID;	// 0x30bb3bf5
@end

