/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import "EBState.h"

@class OABReaderState, ECColumnWidthConvertor;

@interface EBReaderState : EBState {
	XlBinaryReader *mXlReader;	// 36 = 0x24
	XlSheetInfoTable *mXlSheetInfoTable;	// 40 = 0x28
	ECColumnWidthConvertor *mColumnWidthConvertor;	// 44 = 0x2c
	unsigned mTotalCellsWithContentCount;	// 48 = 0x30
	unsigned mTotalCellsWithFormulaCount;	// 52 = 0x34
	XlEshObjectFactory *mXlEshObjectFactory;	// 56 = 0x38
	OABReaderState *mOAState;	// 60 = 0x3c
	BOOL mImportCSV;	// 64 = 0x40
}
@property(assign, nonatomic) BOOL importCSV;	// G=0x37ab0d5d; S=0x37ab0d6d; @synthesize=mImportCSV
- (id)initWithXlReader:(XlBinaryReader *)xlReader cancelDelegate:(id)delegate tracing:(id)tracing;	// 0x37935f59
- (unsigned)cellsWithContentCount;	// 0x37ab0d4d
- (id)columnWidthConvertor;	// 0x379691b5
- (void)dealloc;	// 0x3795a5b1
// declared property getter: - (BOOL)importCSV;	// 0x37ab0d5d
- (void)incrementCellsWithContentCount;	// 0x37953529
- (void)incrementCellsWithFormulaCount;	// 0x37953fd5
- (id)oaState;	// 0x37940239
- (void)pauseReading;	// 0x37948965
- (void)readGlobalXlObjects;	// 0x379402d5
- (void)reportWarning:(CPTaggedMessageStructure *)warning;	// 0x37a47659
- (void)resumeReading;	// 0x3794987d
// declared property setter: - (void)setImportCSV:(BOOL)csv;	// 0x37ab0d6d
- (XlBinaryReader *)xlReader;	// 0x379380f9
- (XlSheetInfoTable *)xlSheetInfoTable;	// 0x3794819d
@end

