/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "SFUOutputStream.h"
#import <NSObject.h> // Unknown library


@interface SFUOffsetOutputStream : NSObject <SFUOutputStream> {
	id<SFUOutputStream> mOutputStream;	// 4 = 0x4
	long long mInitialOffset;	// 8 = 0x8
}
- (id)initWithOutputStream:(id)outputStream;	// 0x37b70385
- (BOOL)canCreateInputStream;	// 0x37b70599
- (BOOL)canSeek;	// 0x37b70455
- (void)close;	// 0x37b7065d
- (id)closeLocalStream;	// 0x37b7067d
- (void)dealloc;	// 0x37b703e9
- (id)inputStream;	// 0x37b705bd
- (long long)offset;	// 0x37b704b9
- (void)seekToOffset:(long long)offset whence:(int)whence;	// 0x37b70479
- (void)writeBuffer:(const char *)buffer size:(unsigned long)size;	// 0x37b70435
@end

