/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BackRow.framework/BackRow
 */

#import "BackRow-Structs.h"
#import <NSObject.h> // Unknown library


@interface BRProxyManager : NSObject {
}
- (id)init;	// 0x33030291
- (id)_copyProxyValueForKey:(CFStringRef)key;	// 0x330305b9
- (id)_httpProxyDictionaryForEnableValue:(BOOL)enableValue hostname:(id)hostname andPort:(id)port;	// 0x33030431
- (id)_proxyDictionaryForEnableValue:(BOOL)enableValue hostname:(id)hostname andPort:(id)port;	// 0x330304f5
- (void)enableProxies:(BOOL)proxies withHost:(id)host andPort:(id)port;	// 0x330302bd
- (void)enableProxies:(BOOL)proxies withHost:(id)host andPort:(id)port http:(BOOL)http;	// 0x33030609
- (id)httpProxyHost;	// 0x33030319
- (id)httpProxyPort;	// 0x330302e9
- (id)httpsProxyHost;	// 0x330303bd
- (id)httpsProxyPort;	// 0x3303038d
- (BOOL)isHTTPProxyEnabled;	// 0x33030349
- (BOOL)isHTTPSProxyEnabled;	// 0x330303ed
@end

