/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

#import <NSObject.h> // Unknown library

@class NSString, NSArray;

@interface DASettingsTemplate : NSObject {
	NSString *_name;	// 4 = 0x4
	int _order;	// 8 = 0x8
	NSString *_primaryDomain;	// 12 = 0xc
	NSArray *_domainAliasPatterns;	// 16 = 0x10
	NSString *_primaryUsernameDomain;	// 20 = 0x14
	int _httpPort;	// 24 = 0x18
	int _httpsPort;	// 28 = 0x1c
	int _port;	// 32 = 0x20
	NSString *_pathFormat;	// 36 = 0x24
	BOOL _isDefaultTemplate;	// 40 = 0x28
	BOOL _defaultUseSSL;	// 41 = 0x29
}
@property(readonly, assign, nonatomic) int defaultPort;	// G=0x311a4a41; 
@property(readonly, assign, nonatomic) NSString *defaultScheme;	// G=0x311a4a0d; 
@property(assign, nonatomic) BOOL defaultUseSSL;	// G=0x311a62a1; S=0x311a62b1; @synthesize=_defaultUseSSL
@property(retain, nonatomic) NSArray *domainAliasPatterns;	// G=0x311a61a5; S=0x311a61b5; @synthesize=_domainAliasPatterns
@property(assign, nonatomic) int httpPort;	// G=0x311a620d; S=0x311a621d; @synthesize=_httpPort
@property(assign, nonatomic) int httpsPort;	// G=0x311a622d; S=0x311a623d; @synthesize=_httpsPort
@property(assign) BOOL isDefaultTemplate;	// G=0x311a6281; S=0x311a6291; @synthesize=_isDefaultTemplate
@property(retain, nonatomic) NSString *name;	// G=0x311a611d; S=0x311a612d; @synthesize=_name
@property(assign, nonatomic) int order;	// G=0x311a6151; S=0x311a6161; @synthesize=_order
@property(retain, nonatomic) NSString *pathFormat;	// G=0x311a624d; S=0x311a625d; @synthesize=_pathFormat
@property(retain, nonatomic) NSString *primaryDomain;	// G=0x311a6171; S=0x311a6181; @synthesize=_primaryDomain
@property(retain, nonatomic) NSString *primaryUsernameDomain;	// G=0x311a61d9; S=0x311a61e9; @synthesize=_primaryUsernameDomain
+ (BOOL)_isValidPort:(int)port;	// 0x311a5e01
+ (id)defaultTemplate;	// 0x311a4129
+ (id)knownTemplates;	// 0x311a40e1
+ (BOOL)requiresPathFormat;	// 0x311a4171
+ (BOOL)requiresPorts;	// 0x311a4175
+ (id)templateWithDomain:(id)domain;	// 0x311a4179
- (void)initAccount:(id)account;	// 0x311a4b59
- (void)_appendPrimarySuffixToUsernameIfNeeded:(id)usernameIfNeeded;	// 0x311a5e11
- (id)_initWithName:(id)name plist:(id)plist;	// 0x311a42f5
- (BOOL)_isDomainInAliases:(id)aliases;	// 0x311a4a81
- (BOOL)_isPrincipalPathCustomForAccount:(id)account;	// 0x311a5fa1
- (id)_principalPathForAccount:(id)account;	// 0x311a6029
- (void)_setPrincipalURLForAccount:(id)account;	// 0x311a5a91
- (int)compare:(id)compare;	// 0x311a4985
- (void)dealloc;	// 0x311a4851
// declared property getter: - (int)defaultPort;	// 0x311a4a41
// declared property getter: - (id)defaultScheme;	// 0x311a4a0d
// declared property getter: - (BOOL)defaultUseSSL;	// 0x311a62a1
- (id)description;	// 0x311a60b9
- (id)descriptionForAccount:(id)account;	// 0x311a5f41
// declared property getter: - (id)domainAliasPatterns;	// 0x311a61a5
- (unsigned)hash;	// 0x311a48ed
// declared property getter: - (int)httpPort;	// 0x311a620d
// declared property getter: - (int)httpsPort;	// 0x311a622d
// declared property getter: - (BOOL)isDefaultTemplate;	// 0x311a6281
- (BOOL)isEqual:(id)equal;	// 0x311a4915
// declared property getter: - (id)name;	// 0x311a611d
// declared property getter: - (int)order;	// 0x311a6151
// declared property getter: - (id)pathFormat;	// 0x311a624d
// declared property getter: - (id)primaryDomain;	// 0x311a6171
// declared property getter: - (id)primaryUsernameDomain;	// 0x311a61d9
// declared property setter: - (void)setDefaultUseSSL:(BOOL)ssl;	// 0x311a62b1
- (void)setDomain:(id)domain forAccount:(id)account;	// 0x311a4c25
// declared property setter: - (void)setDomainAliasPatterns:(id)patterns;	// 0x311a61b5
// declared property setter: - (void)setHttpPort:(int)port;	// 0x311a621d
// declared property setter: - (void)setHttpsPort:(int)port;	// 0x311a623d
// declared property setter: - (void)setIsDefaultTemplate:(BOOL)aTemplate;	// 0x311a6291
// declared property setter: - (void)setName:(id)name;	// 0x311a612d
// declared property setter: - (void)setOrder:(int)order;	// 0x311a6161
// declared property setter: - (void)setPathFormat:(id)format;	// 0x311a625d
- (void)setPort:(int)port forAccount:(id)account;	// 0x311a5491
// declared property setter: - (void)setPrimaryDomain:(id)domain;	// 0x311a6181
// declared property setter: - (void)setPrimaryUsernameDomain:(id)domain;	// 0x311a61e9
- (void)setPrincipalURLForAccount:(id)account toURL:(id)url;	// 0x311a5a7d
- (void)setURL:(id)url forAccount:(id)account;	// 0x311a5675
- (void)setUseSSL:(BOOL)ssl forAccount:(id)account;	// 0x311a528d
- (void)setUsername:(id)username forAccount:(id)account;	// 0x311a50a1
@end

