/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreBaseMetadataProvider.h"

@class ATVSedonaCatalogItem;

__attribute__((visibility("hidden")))
@interface ATVSedonaMovieMetadataProvider : ATVMusicStoreBaseMetadataProvider {
@private
	ATVSedonaCatalogItem *_sedonaItem;	// 12 = 0xc
}
+ (void)initialize;	// 0x339cdac5
+ (id)providerWithCatalogItem:(id)catalogItem;	// 0x339cde85
- (id)init;	// 0x339cdec1
- (id)initWithCatalogItem:(id)catalogItem;	// 0x339cded9
- (void)_populateActors:(id)actors;	// 0x339ce5a1
- (void)_populateAudio:(id)audio;	// 0x339ce831
- (void)_populateCategories:(id)categories;	// 0x339ce705
- (void)_populateDirector:(id)director;	// 0x339ce641
- (void)_populateMetadataDetails:(id)details;	// 0x339ce051
- (void)_populateMovieDetails:(id)details;	// 0x339ce0e5
- (void)_populateSubtitles:(id)subtitles;	// 0x339ce795
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x339cdf91
- (void)dealloc;	// 0x339cdf45
- (void)populateMetadataForControl:(id)control;	// 0x339cdfcd
@end

