/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL, NSString, BRMediaType;

__attribute__((visibility("hidden")))
@interface ATVShowInfoFetchKey : XXUnknownSuperclass {
	BRMediaType *_mediaType;	// 4 = 0x4
	NSString *_podcastGUID;	// 8 = 0x8
	NSURL *_podcastURL;	// 12 = 0xc
	NSString *_itemID;	// 16 = 0x10
}
@property(copy, nonatomic) NSString *itemID;	// G=0x3bae95; S=0x3baea9; @synthesize=_itemID
@property(retain, nonatomic) BRMediaType *mediaType;	// G=0x3bae31; S=0x3bae41; @synthesize=_mediaType
@property(copy, nonatomic) NSString *podcastGUID;	// G=0x3bae51; S=0x3bae65; @synthesize=_podcastGUID
@property(retain, nonatomic) NSURL *podcastURL;	// G=0x3bae75; S=0x3bae85; @synthesize=_podcastURL
+ (id)fetchKeyFromEpisodeDictionary:(id)episodeDictionary;	// 0x3badfd
- (void)dealloc;	// 0x3bad71
// declared property getter: - (id)itemID;	// 0x3bae95
// declared property getter: - (id)mediaType;	// 0x3bae31
// declared property getter: - (id)podcastGUID;	// 0x3bae51
// declared property getter: - (id)podcastURL;	// 0x3bae75
// declared property setter: - (void)setItemID:(id)anId;	// 0x3baea9
// declared property setter: - (void)setMediaType:(id)type;	// 0x3bae41
// declared property setter: - (void)setPodcastGUID:(id)guid;	// 0x3bae65
// declared property setter: - (void)setPodcastURL:(id)url;	// 0x3bae85
@end

