/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "BRProvider.h"

@class NSDate, NSString, NSMutableArray;
@protocol BRControlFactory;

__attribute__((visibility("hidden")))
@interface ATVDotMacProvider : XXUnknownSuperclass <BRProvider> {
	NSMutableArray *_data;	// 4 = 0x4
	id<BRControlFactory> _controlFactory;	// 8 = 0x8
	NSDate *_lastUpdateDate;	// 12 = 0xc
	BOOL _updatePending;	// 16 = 0x10
	NSString *_uniqueID;	// 20 = 0x14
	BOOL _chainLoadingDisabled;	// 24 = 0x18
	BOOL _isTemporaryProvider;	// 25 = 0x19
}
@property(assign) BOOL chainLoadingDisabled;	// G=0x1844fd; S=0x1844ed; converted property
@property(readonly, retain) NSString *uniqueID;	// G=0x1846f1; converted property
+ (BOOL)accountWithNameIsPersistent:(id)nameIsPersistent;	// 0x184111
+ (id)providerOfPersistentAccounts;	// 0x1840cd
- (id)initAsTemporaryProvider:(BOOL)provider;	// 0x1841d9
- (BOOL)_accountIconLoadedForAccount:(id)account updateData:(id)data;	// 0x18597d
- (void)_accountToRemove:(id)remove;	// 0x184d4d
- (id)_accountWithName:(id)name;	// 0x1865b1
- (id)_assetWithIdentifier:(id)identifier parentCollection:(id)collection;	// 0x186531
- (BOOL)_assetsLoadedForCollection:(id)collection updateData:(id)data;	// 0x185ba1
- (id)_cachedAccountIconForIconPath:(id)iconPath;	// 0x1863f9
- (void)_cancelDataMonitoringForAccounts;	// 0x184a11
- (id)_collectionWithIdentifier:(id)identifier withParentAccountName:(id)parentAccountName;	// 0x1864a1
- (id)_data;	// 0x186491
- (BOOL)_handlesObject:(id)object;	// 0x1852f9
- (BOOL)_imageLoadedForAsset:(id)asset updateData:(id)data;	// 0x186295
- (id)_initForPersistentAccounts;	// 0x184701
- (void)_listenerUpdate:(id)update;	// 0x184f1d
- (BOOL)_mediaLoadedForAccount:(id)account updateData:(id)data;	// 0x1852fd
- (void)_newAccountToAdd:(id)add;	// 0x184a9d
- (BOOL)_newAuthenticationForCollection:(id)collection updateData:(id)data;	// 0x185a31
- (id)_persistentAccounts;	// 0x184815
- (void)_postUpdateNotification:(id)notification;	// 0x1852c1
- (void)_processChangeToObject:(id)object;	// 0x184f6d
- (void)_sendUpdateNotification;	// 0x185151
- (void)_sendUpdateNotificationAfterDelay;	// 0x18511d
- (void)_updateDataCount;	// 0x18662d
- (id)accessibilityLabel;	// 0x186481
// converted property getter: - (BOOL)chainLoadingDisabled;	// 0x1844fd
- (id)controlFactory;	// 0x1843ed
- (id)dataAtIndex:(long)index;	// 0x184425
- (long)dataCount;	// 0x1843fd
- (void)dealloc;	// 0x1842f5
- (void)handleDataUpdate:(id)update updateData:(id)data;	// 0x184559
- (id)hashForDataAtIndex:(long)index;	// 0x184491
- (void)invalidate;	// 0x18450d
// converted property setter: - (void)setChainLoadingDisabled:(BOOL)disabled;	// 0x1844ed
// converted property getter: - (id)uniqueID;	// 0x1846f1
@end

