/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSNetServiceBrowserDelegate.h"
#import "NSNetServiceDelegate.h"

@class NSNetServiceBrowser, BRAccount, NSString, NSMutableArray;

__attribute__((visibility("hidden")))
@interface ATVHSManager : XXUnknownSuperclass <NSNetServiceBrowserDelegate, NSNetServiceDelegate> {
	BOOL _isWirelessInterfaceActive;	// 4 = 0x4
	BOOL _isWiredInterfaceActive;	// 5 = 0x5
	BOOL _activeNetworkInterfaceInitialized;	// 6 = 0x6
	NSNetServiceBrowser *_iTunesServiceBrowser;	// 8 = 0x8
	NSNetServiceBrowser *_photoAppServiceBrowser;	// 12 = 0xc
	NSMutableArray *_resolvingServices;	// 16 = 0x10
	NSMutableArray *_monitoredServices;	// 20 = 0x14
	NSString *_hsGroupIDInternal;	// 24 = 0x18
}
@property(readonly, assign, nonatomic) BRAccount *hsAccount;	// G=0x38ba75; @dynamic
@property(readonly, assign, nonatomic) NSString *hsGroupID;	// G=0x38ba1d; @dynamic
@property(copy, nonatomic) NSString *hsGroupIDInternal;	// G=0x38de91; S=0x38dea5; @synthesize=_hsGroupIDInternal
@property(retain, nonatomic) NSNetServiceBrowser *iTunesServiceBrowser;	// G=0x38de11; S=0x38de21; @synthesize=_iTunesServiceBrowser
@property(retain, nonatomic) NSMutableArray *monitoredServices;	// G=0x38de71; S=0x38de81; @synthesize=_monitoredServices
@property(retain, nonatomic) NSNetServiceBrowser *photoAppServiceBrowser;	// G=0x38de31; S=0x38de41; @synthesize=_photoAppServiceBrowser
@property(retain, nonatomic) NSMutableArray *resolvingServices;	// G=0x38de51; S=0x38de61; @synthesize=_resolvingServices
+ (id)sharedInstance;	// 0x38af21
- (id)init;	// 0x38af91
- (id)_availableHomeSharesOfType:(unsigned long)type;	// 0x38e411
- (BOOL)_connectAvailableDataClientsForServer:(id)server;	// 0x38deb5
- (void)_dataClientConnectionHandlerWithObject:(id)object;	// 0x38e065
- (id)_dataServerWithID:(id)anId;	// 0x38e4d5
- (void)_handleITunesTXTRecord:(id)record service:(id)service;	// 0x38c2c9
- (void)_handlePhotoAppTXTRecord:(id)record service:(id)service;	// 0x38cd81
- (void)_handleTXTRecord:(id)record service:(id)service;	// 0x38c1f1
- (void)_iTunesRequestTimedOut:(id)anOut;	// 0x38e18d
- (void)_networkStateChanged:(id)changed;	// 0x38e265
- (void)_resolveBonjourWithDataServer:(id)dataServer;	// 0x38be91
- (void)_serverAvailableForConnection:(id)connection;	// 0x38dfd9
- (unsigned long long)_uint64ValueWithData:(id)data;	// 0x38e621
- (void)cleanUpOrEnableHomeShareState;	// 0x38bd49
- (BOOL)connectToServer:(id)server;	// 0x38bbf9
- (void)disableHomeSharing;	// 0x38b5fd
- (void)enableBonjourBrowseWithHSGroupID:(id)hsgroupID;	// 0x38b7e5
- (void)enableHomeSharingWithAccountName:(id)accountName andPassword:(id)password;	// 0x38b051
- (id)homeSharesOfTypes:(unsigned long)types;	// 0x38bae5
// declared property getter: - (id)hsAccount;	// 0x38ba75
// declared property getter: - (id)hsGroupID;	// 0x38ba1d
// declared property getter: - (id)hsGroupIDInternal;	// 0x38de91
// declared property getter: - (id)iTunesServiceBrowser;	// 0x38de11
// declared property getter: - (id)monitoredServices;	// 0x38de71
- (void)netService:(id)service didNotResolve:(id)resolve;	// 0x38db5d
- (void)netService:(id)service didUpdateTXTRecordData:(id)data;	// 0x38d9c5
- (void)netServiceBrowser:(id)browser didFindService:(id)service moreComing:(BOOL)coming;	// 0x38d2ad
- (void)netServiceBrowser:(id)browser didNotSearch:(id)search;	// 0x38d275
- (void)netServiceBrowser:(id)browser didRemoveService:(id)service moreComing:(BOOL)coming;	// 0x38d33d
- (void)netServiceBrowserDidStopSearch:(id)netServiceBrowser;	// 0x38d23d
- (void)netServiceBrowserWillSearch:(id)netServiceBrowser;	// 0x38d205
- (void)netServiceDidResolveAddress:(id)netService;	// 0x38da79
// declared property getter: - (id)photoAppServiceBrowser;	// 0x38de31
// declared property getter: - (id)resolvingServices;	// 0x38de51
// declared property setter: - (void)setHsGroupIDInternal:(id)internal;	// 0x38dea5
// declared property setter: - (void)setITunesServiceBrowser:(id)browser;	// 0x38de21
// declared property setter: - (void)setMonitoredServices:(id)services;	// 0x38de81
// declared property setter: - (void)setPhotoAppServiceBrowser:(id)browser;	// 0x38de41
// declared property setter: - (void)setResolvingServices:(id)services;	// 0x38de61
- (int)sharingState;	// 0x38bb5d
@end

