/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

#import "MusicLibrary-Structs.h"
#import <NSObject.h> // Unknown library

@class NSString;

@interface ML3SqliteDatabaseContext : NSObject {
	sqlite3 **_dbStack;	// 4 = 0x4
	unsigned _dbStackCurrentIndex;	// 8 = 0x8
	CFDictionaryRef _statementCache;	// 12 = 0xc
	BOOL _isInTransaction;	// 16 = 0x10
	NSString *_path;	// 20 = 0x14
	BOOL _enableWrites;	// 24 = 0x18
}
@property(readonly, assign, nonatomic) sqlite3 *db;	// G=0x3058e9f1; 
@property(assign, nonatomic) BOOL isInTransaction;	// G=0x305d5bd1; S=0x305d5be1; @synthesize=_isInTransaction
- (id)initWithDB:(sqlite3 *)db;	// 0x3058e911
- (void).cxx_destruct;	// 0x305d5bf1
// declared property getter: - (sqlite3 *)db;	// 0x3058e9f1
- (void)dealloc;	// 0x305d59e9
- (BOOL)executeSQL:(id)sql;	// 0x305d5a71
// declared property getter: - (BOOL)isInTransaction;	// 0x305d5bd1
- (void)popDB;	// 0x305d5b15
- (void)pushDB:(sqlite3 *)db;	// 0x305d5acd
// declared property setter: - (void)setIsInTransaction:(BOOL)transaction;	// 0x305d5be1
- (sqlite3_stmt *)statementForSQL:(id)sql;	// 0x3059df69
@end

