/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIView.h"

@class NSAttributedString, UIColor, UIRefreshControl;

__attribute__((visibility("hidden")))
@interface _UIRefreshControlContentView : UIView {
	UIRefreshControl *_refreshControl;	// 84 = 0x54
	UIColor *_tintColor;	// 88 = 0x58
}
@property(retain, nonatomic) NSAttributedString *attributedTitle;	// G=0x33e435fd; S=0x33e43601; 
@property(readonly, assign, nonatomic) float maximumSnappingHeight;	// G=0x33e4360d; 
@property(readonly, assign, nonatomic) float minimumSnappingHeight;	// G=0x33e43609; 
@property(assign, nonatomic) UIRefreshControl *refreshControl;	// G=0x33e4364d; S=0x33e4365d; @synthesize=_refreshControl
@property(readonly, assign, nonatomic) int style;	// G=0x33e43605; 
@property(retain, nonatomic) UIColor *tintColor;	// G=0x33e4366d; S=0x33e4367d; @synthesize=_tintColor
- (float)_heightAtWhichNoneOfTheInterfaceElementsAreVisibleEvenIfTheControlIsStillPartiallyOnScreen;	// 0x33e43649
// declared property getter: - (id)attributedTitle;	// 0x33e435fd
- (void)dealloc;	// 0x33e435b1
- (void)didTransitionFromState:(int)state toState:(int)state2;	// 0x33e43645
// declared property getter: - (float)maximumSnappingHeight;	// 0x33e4360d
// declared property getter: - (float)minimumSnappingHeight;	// 0x33e43609
// declared property getter: - (id)refreshControl;	// 0x33e4364d
- (void)refreshControlInvalidatedSnappingHeight;	// 0x33e43611
// declared property setter: - (void)setAttributedTitle:(id)title;	// 0x33e43601
// declared property setter: - (void)setRefreshControl:(id)control;	// 0x33e4365d
// declared property setter: - (void)setTintColor:(id)color;	// 0x33e4367d
// declared property getter: - (int)style;	// 0x33e43605
// declared property getter: - (id)tintColor;	// 0x33e4366d
- (void)willTransitionFromState:(int)state toState:(int)state2;	// 0x33e43615
@end

