/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import <NSObject.h> // Unknown library
#import "UIKit-Structs.h"

@class NSMutableIndexSet, NSMutableArray, UICollectionViewData, NSArray;

__attribute__((visibility("hidden")))
@interface UICollectionViewUpdate : NSObject {
	NSArray *_updateItems;	// 4 = 0x4
	UICollectionViewData *_oldModel;	// 8 = 0x8
	UICollectionViewData *_newModel;	// 12 = 0xc
	CGRect _oldVisibleBounds;	// 16 = 0x10
	CGRect _newVisibleBounds;	// 32 = 0x20
	NSMutableIndexSet *_movedItems;	// 48 = 0x30
	NSMutableIndexSet *_movedSections;	// 52 = 0x34
	NSMutableArray *_deletedSections;	// 56 = 0x38
	NSMutableArray *_insertedSections;	// 60 = 0x3c
	int *_oldSectionMap;	// 64 = 0x40
	int *_newSectionMap;	// 68 = 0x44
	int *_oldGlobalItemMap;	// 72 = 0x48
	int *_newGlobalItemMap;	// 76 = 0x4c
	id *_animatedItems;	// 80 = 0x50
	id *_animatedHeaders;	// 84 = 0x54
	id *_animatedFooters;	// 88 = 0x58
	NSMutableArray *_viewAnimations;	// 92 = 0x5c
	NSMutableArray *_gaps;	// 96 = 0x60
}
- (id)initWithUpdateItems:(id)updateItems oldModel:(id)model newModel:(id)model3 oldVisibleBounds:(CGRect)bounds newVisibleBounds:(CGRect)bounds5;	// 0x33dcad9d
- (void)_computeGaps;	// 0x33dcbbe5
- (void)_computeItemUpdates;	// 0x33dcb5c1
- (void)_computeSectionUpdates;	// 0x33dcb035
- (void)dealloc;	// 0x33dcaead
@end

