/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/BulletinBoard.framework/BulletinBoard
 */

#import <NSObject.h> // Unknown library

@class NSString;
@protocol BBAssertionDelegate;

@interface BBAssertion : NSObject {
	id<BBAssertionDelegate> _delegate;	// 4 = 0x4
	NSString *_identifier;	// 8 = 0x8
	unsigned _transactionID;	// 12 = 0xc
}
@property(readonly, retain) NSString *identifier;	// G=0x32c44f29; converted property
@property(readonly, assign) unsigned transactionID;	// G=0x32c44f39; converted property
- (id)initWithDelegate:(id)delegate identifier:(id)identifier;	// 0x32c44e05
- (void)dealloc;	// 0x32c44e7d
// converted property getter: - (id)identifier;	// 0x32c44f29
- (void)increaseOrIgnoreTransactionID:(unsigned)anId;	// 0x32c44f11
// converted property getter: - (unsigned)transactionID;	// 0x32c44f39
@end

