/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/MIME.framework/MIME
 */

#import <NSObject.h> // Unknown library
#import "MIME-Structs.h"


@protocol NSObject
- (id)autorelease;
- (Class)class;
- (BOOL)conformsToProtocol:(id)protocol;
- (id)description;
- (unsigned)hash;
- (BOOL)isEqual:(id)equal;
- (BOOL)isKindOfClass:(Class)aClass;
- (BOOL)isMemberOfClass:(Class)aClass;
- (BOOL)isProxy;
- (id)performSelector:(SEL)selector;
- (id)performSelector:(SEL)selector withObject:(id)object;
- (id)performSelector:(SEL)selector withObject:(id)object withObject:(id)object3;
- (oneway void)release;
- (BOOL)respondsToSelector:(SEL)selector;
- (id)retain;
- (unsigned)retainCount;
- (id)self;
- (Class)superclass;
- (NSZone *)zone;
@end

@interface NSObject (LockingAdditions)
+ (void)mf_clearLocks;	// 0x304b8f9d
- (void)_mf_checkToAllowExclusiveLocksWithLock:(id)lock;	// 0x304b85dd
- (void)_mf_checkToAllowLock:(id)allowLock;	// 0x304b8a79
- (void)_mf_checkToAllowOrderingWithLock:(id)lock;	// 0x304b8859
- (void)_mf_checkToAllowStrictProgressionWithLock:(id)lock;	// 0x304b872d
- (id)_mf_lockOrderingForType:(int)type;	// 0x304b8995
- (BOOL)_mf_ntsIsLocked;	// 0x304b8b81
- (id)mf_exclusiveLocks;	// 0x304b854d
- (void)mf_lock;	// 0x304b9ed1
- (id)mf_lockOrdering;	// 0x304b8549
- (void)mf_lockWithPriority;	// 0x304b9eb1
- (id)mf_strictLockOrdering;	// 0x304b8545
- (BOOL)mf_tryLock;	// 0x304b8dcd
- (BOOL)mf_tryLockWithPriority;	// 0x304b8da9
- (void)mf_unlock;	// 0x304b8df1
@end

