/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import "DOMObject.h"

@class NSString, DOMMediaList, DOMNode;

@interface DOMStyleSheet : DOMObject {
}
@property(assign) BOOL disabled;	// G=0x331c64c5; S=0x331c65b5; 
@property(readonly, assign) NSString *href;	// G=0x331c6931; 
@property(readonly, assign) DOMMediaList *media;	// G=0x331c6b99; 
@property(readonly, assign) DOMNode *ownerNode;	// G=0x331c66ad; 
@property(readonly, assign) DOMStyleSheet *parentStyleSheet;	// G=0x331c67a5; 
@property(readonly, assign) NSString *title;	// G=0x331c6a65; 
@property(readonly, assign) NSString *type;	// G=0x331c6391; 
- (void)dealloc;	// 0x331c62cd
// declared property getter: - (BOOL)disabled;	// 0x331c64c5
- (void)finalize;	// 0x331c6341
// declared property getter: - (id)href;	// 0x331c6931
// declared property getter: - (id)media;	// 0x331c6b99
// declared property getter: - (id)ownerNode;	// 0x331c66ad
// declared property getter: - (id)parentStyleSheet;	// 0x331c67a5
// declared property setter: - (void)setDisabled:(BOOL)disabled;	// 0x331c65b5
// declared property getter: - (id)title;	// 0x331c6a65
// declared property getter: - (id)type;	// 0x331c6391
@end

