/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SkankKit.framework/SkankKit
 */

#import <NSObject.h> // Unknown library
#import "SkankKit-Structs.h"

@class NSTimer;

@interface SKTelephonyController : NSObject {
	NSTimer *_hackTimer;	// 4 = 0x4
	CTServerConnectionRef _serverCon;	// 8 = 0x8
	BOOL _commCenterActive;	// 12 = 0xc
	int _stream;	// 16 = 0x10
}
@property(assign) CTCallRef activeCall;	// G=0x34f40831; S=0x34f40891; converted property
@property(readonly, assign, getter=isCommCenterActive) BOOL commCenterActive;	// G=0x34f41225; converted property
@property(assign) BOOL dataStatus;	// G=0x34f41115; S=0x34f41139; converted property
+ (id)sharedInstance;	// 0x34f400b9
- (id)init;	// 0x34f40189
- (id)activeBands;	// 0x34f4107d
// converted property getter: - (CTCallRef)activeCall;	// 0x34f40831
- (double)activeCallDuration;	// 0x34f408e1
- (void)answerIncomingCall;	// 0x34f40b0d
- (BOOL)autoSelectsNetwork;	// 0x34f41199
- (id)basebandVersion;	// 0x34f41275
- (void)callIsIncoming:(CTCallRef)incoming;	// 0x34f40965
- (void)closeBasebandStream;	// 0x34f41559
- (int)countCurrentCalls;	// 0x34f408bd
- (CFArrayRef)currentCalls;	// 0x34f408b5
// converted property getter: - (BOOL)dataStatus;	// 0x34f41115
- (void)dealloc;	// 0x34f406b1
- (BOOL)dialNumber:(id)number;	// 0x34f40de1
- (void)enableCommCenter:(BOOL)center;	// 0x34f411d5
- (void)enableMux:(BOOL)mux;	// 0x34f41235
- (void)hangupActiveCall;	// 0x34f40f11
- (void)hangupCall:(CTCallRef)call;	// 0x34f40e69
- (void)ignoreIncomingCall;	// 0x34f40be5
- (id)imei;	// 0x34f412c1
- (CTCallRef)incomingCall;	// 0x34f40929
- (BOOL)isCallConnected;	// 0x34f40895
// converted property getter: - (BOOL)isCommCenterActive;	// 0x34f41225
- (void)mainThreadAnswerIncomingCall;	// 0x34f40a79
- (void)mainThreadIgnoreIncomingCall;	// 0x34f40b65
- (id)myPhoneNumber;	// 0x34f40815
- (id)networkName;	// 0x34f41179
- (void)openBasebandStream;	// 0x34f41475
- (void)pulseRTS;	// 0x34f4136d
- (id)readATResponse;	// 0x34f41651
- (void)registerTelephonyNotification:(CFStringRef)notification withCallback:(/*function-pointer*/ void *)callback;	// 0x34f407ed
- (void)requestNetworkList;	// 0x34f411cd
- (void)resetModem;	// 0x34f41345
- (void)routeAudioToCall;	// 0x34f40f41
- (void)sendATCommand:(id)command;	// 0x34f41591
- (void)sendUSSDResponse:(id)response;	// 0x34f41785
- (CTServerConnectionRef)serverConnection;	// 0x34f407dd
- (void)setActiveBands:(CFArrayRef)bands;	// 0x34f410e1
// converted property setter: - (void)setActiveCall:(CTCallRef)call;	// 0x34f40891
- (void)setAutoSelectNetwork;	// 0x34f411c1
- (void)setBasebandSpeed:(int)speed;	// 0x34f413c5
// converted property setter: - (void)setDataStatus:(BOOL)status;	// 0x34f41139
- (void)setManuallySelectNetwork:(id)network;	// 0x34f411c5
- (void)setMasterVolume:(float)volume;	// 0x34f40fa9
- (void)setSpeechVolume:(float)volume;	// 0x34f40fe1
- (int)signalStrength;	// 0x34f411d1
- (id)supportedBands;	// 0x34f41019
- (void)updateWithCall:(CTCallRef)call;	// 0x34f40c4d
@end

