/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

#import </libobjc.A.h>


@interface SSWishlistDatabaseSchema : NSObject {
}
+ (void)_migrate7000to7001InDatabase:(id)database;	// 0x3285f851
+ (void)_migrate7001to7002InDatabase:(id)database;	// 0x3285f871
+ (void)createSchemaInDatabase:(id)database;	// 0x3285f6a1
+ (id)databasePathWithAccountIdentifier:(long long)accountIdentifier;	// 0x3285f76d
@end

