/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import "iTunesStore-Structs.h"
#import "ISOperation.h"

@class ISDialog, ISDialogButton, NSArray;
@protocol ISDialogOperationDelegate;

@interface ISDialogOperation : ISOperation {
	ISDialog *_dialog;	// 60 = 0x3c
	BOOL _performDefaultActions;	// 64 = 0x40
	ISDialogButton *_selectedButton;	// 68 = 0x44
	NSArray *_textFieldValues;	// 72 = 0x48
	id _userNotification;	// 76 = 0x4c
}
@property(assign) id<ISDialogOperationDelegate> delegate;	// @dynamic
@property(retain) ISDialog *dialog;	// G=0x37a63549; S=0x37a6355d; @synthesize=_dialog
@property(assign) BOOL performDefaultActions;	// G=0x37a6356d; S=0x37a63585; @synthesize=_performDefaultActions
@property(retain) ISDialogButton *selectedButton;	// G=0x37a6359d; S=0x37a635b1; @synthesize=_selectedButton
@property(readonly, assign) NSArray *textFieldValues;	// G=0x37a62c01; 
@property(retain) id userNotification;	// G=0x37a635c1; S=0x37a635d5; @synthesize=_userNotification
+ (id)operationWithDialog:(id)dialog;	// 0x37a6291d
+ (id)operationWithError:(id)error;	// 0x37a62981
- (id)init;	// 0x37a62839
- (void)_handleResponseForNotification:(CFUserNotificationRef)notification responseFlags:(unsigned long)flags;	// 0x37a62ebd
- (void)_run;	// 0x37a62f3d
- (void)_showUserNotification:(id)notification;	// 0x37a6338d
- (void)_waitForUserNotificationResponse:(CFUserNotificationRef)userNotificationResponse;	// 0x37a634d1
- (void)cancel;	// 0x37a62c61
- (void)dealloc;	// 0x37a62879
// declared property getter: - (id)dialog;	// 0x37a63549
- (void)handleButtonSelected:(int)selected withResponseDictionary:(id)responseDictionary;	// 0x37a629e5
// declared property getter: - (BOOL)performDefaultActions;	// 0x37a6356d
- (void)run;	// 0x37a62ca9
// declared property getter: - (id)selectedButton;	// 0x37a6359d
// declared property setter: - (void)setDialog:(id)dialog;	// 0x37a6355d
// declared property setter: - (void)setPerformDefaultActions:(BOOL)actions;	// 0x37a63585
// declared property setter: - (void)setSelectedButton:(id)button;	// 0x37a635b1
// declared property setter: - (void)setUserNotification:(id)notification;	// 0x37a635d5
// declared property getter: - (id)textFieldValues;	// 0x37a62c01
// declared property getter: - (id)userNotification;	// 0x37a635c1
@end

