/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ATVSlideshow.framework/ATVSlideshow
 */

#import "ATVSlideshow-Structs.h"
#import <NSObject.h> // Unknown library

@class MRImage, MRCroppingSprite;

@interface MRShiftingTilesRenderable : NSObject {
	MRImage *slide;	// 4 = 0x4
	MRCroppingSprite *sprite;	// 8 = 0x8
	CGPoint position;	// 12 = 0xc
	CGSize size;	// 20 = 0x14
}
@property(retain, nonatomic) MRImage *slide;	// G=0x321ec85d; S=0x321ec819; @synthesize
@property(retain, nonatomic) MRCroppingSprite *sprite;	// G=0x321ec86d; S=0x321ec87d; @synthesize
- (void)dealloc;	// 0x321ec7a1
// declared property setter: - (void)setSlide:(id)slide;	// 0x321ec819
// declared property setter: - (void)setSprite:(id)sprite;	// 0x321ec87d
// declared property getter: - (id)slide;	// 0x321ec85d
// declared property getter: - (id)sprite;	// 0x321ec86d
@end

