/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import "EBState.h"

@class ECColumnWidthConvertor, OABReaderState;

__attribute__((visibility("hidden")))
@interface EBReaderState : EBState {
@private
	XlBinaryReader *mXlReader;	// 36 = 0x24
	XlSheetInfoTable *mXlSheetInfoTable;	// 40 = 0x28
	ECColumnWidthConvertor *mColumnWidthConvertor;	// 44 = 0x2c
	unsigned mTotalCellsWithContentCount;	// 48 = 0x30
	XlEshObjectFactory *mXlEshObjectFactory;	// 52 = 0x34
	OABReaderState *mOAState;	// 56 = 0x38
}
- (id)initWithXlReader:(XlBinaryReader *)xlReader cancelDelegate:(id)delegate tracing:(id)tracing;	// 0x32bfccdd
- (unsigned)cellsWithContentCount;	// 0x32cfeedd
- (id)columnWidthConvertor;	// 0x32aec619
- (void)dealloc;	// 0x32b113c9
- (void)incrementCellsWithContentCount;	// 0x32af3e19
- (id)oaState;	// 0x32c03811
- (void)pauseReading;	// 0x32b06d91
- (void)readGlobalXlObjects;	// 0x32c03899
- (void)reportWarning:(CPTaggedMessageStructure *)warning;	// 0x32c08115
- (void)resumeReading;	// 0x32ae7f11
- (XlBinaryReader *)xlReader;	// 0x32ae80f9
- (XlSheetInfoTable *)xlSheetInfoTable;	// 0x32c05099
@end

