/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import "DOMObject.h"


__attribute__((visibility("hidden")))
@interface DOMNodeList : DOMObject {
}
@property(readonly, assign) unsigned length;	// G=0x315ed519; 
- (void)dealloc;	// 0x315ed535
- (void)finalize;	// 0x3169f5a9
- (id)item:(unsigned)item;	// 0x3169f589
// declared property getter: - (unsigned)length;	// 0x315ed519
@end

