/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/MailServices.framework/MailServices
 */

#import "MSMailDefaultService.h"

@class NSSet;

@interface MSNotificationService : MSMailDefaultService {
	NSSet *_accountIDs;	// 24 = 0x18
}
@property(retain, nonatomic) NSSet *accountIDs;	// G=0x361321e5; S=0x361321f5; @synthesize=_accountIDs
+ (id)registerNotificationObserver:(id)observer forAccounts:(id)accounts shouldLaunchMobileMail:(BOOL)mail;	// 0x361315d1
+ (id)smi_serverCommandName;	// 0x361315c5
- (id)_addObserverClientForNotifications;	// 0x36131ded
- (id)_didReceiveNotificationData:(id)data userInfo:(id)info;	// 0x36131e81
- (id)_initWithDelegate:(id)delegate;	// 0x3613170d
- (void)_requestInitialMessageStateForAccountIDs:(id)accountIDs;	// 0x361318d5
- (void)_smi_notifyClientDidFinishWithError:(id)_smi_notifyClient;	// 0x361317b5
- (void)_validateMessageReferences:(id)references;	// 0x36131b6d
// declared property getter: - (id)accountIDs;	// 0x361321e5
- (void)dealloc;	// 0x36131755
// declared property setter: - (void)setAccountIDs:(id)ids;	// 0x361321f5
@end

