/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import "AVReencodedAudioSettingsForFig.h"
#import "AVDecodedAudioSettingsForFig.h"
#import "AVFoundation-Structs.h"
#import "AVAudioOutputSettings.h"


@interface AVAVAudioSettingsAudioOutputSettings : AVAudioOutputSettings <AVReencodedAudioSettingsForFig, AVDecodedAudioSettingsForFig> {
}
+ (id)_audioOutputSettingsWithAudioSettingsDictionary:(id)audioSettingsDictionary exceptionReason:(id *)reason;	// 0x326dd3ed
+ (id)eligibleOutputSettingsDictionaryKeys;	// 0x326dd2b9
- (id)initWithAVAudioSettingsDictionary:(id)avaudioSettingsDictionary exceptionReason:(id *)reason;	// 0x326dd441
- (id)initWithTrustedAVAudioSettingsDictionary:(id)trustedAVAudioSettingsDictionary;	// 0x326de139
- (id)audioOptions;	// 0x326dee19
- (BOOL)canFullySpecifyOutputFormatReturningReason:(id *)reason;	// 0x326de1ed
- (AudioChannelLayout *)copyAudioChannelLayoutForSourceFormatDescription:(opaqueCMFormatDescription *)sourceFormatDescription audioChannelLayoutSize:(unsigned *)size;	// 0x326decc1
- (void)getAudioStreamBasicDescription:(AudioStreamBasicDescription *)description forAudioFileTypeID:(unsigned long)audioFileTypeID sourceFormatDescription:(opaqueCMFormatDescription *)description3;	// 0x326de459
- (BOOL)isCodecAvailableOnCurrentSystem;	// 0x326de1a5
- (BOOL)willYieldCompressedSamples;	// 0x326de14d
@end

