/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import "NSCopying.h"
#import <NSObject.h> // Unknown library
#import "AVFoundation-Structs.h"

@class NSLocale, AVMediaSelectionOptionInternal, NSString, NSArray;

@interface AVMediaSelectionOption : NSObject <NSCopying> {
	AVMediaSelectionOptionInternal *_mediaSelectionOption;	// 4 = 0x4
}
@property(readonly, assign, nonatomic) NSArray *availableMetadataFormats;	// G=0x326d99f5; 
@property(readonly, assign, nonatomic) NSArray *commonMetadata;	// G=0x326d9911; 
@property(readonly, assign, nonatomic) NSLocale *locale;	// G=0x326d98c9; 
@property(readonly, assign, nonatomic) NSArray *mediaSubTypes;	// G=0x326d9879; 
@property(readonly, assign, nonatomic) NSString *mediaType;	// G=0x326d9875; 
@property(readonly, assign, nonatomic, getter=isPlayable) BOOL playable;	// G=0x326d9881; 
+ (id)mediaSelectionOptionForAsset:(id)asset group:(id)group dictionary:(id)dictionary hasUnderlyingTrack:(BOOL)track;	// 0x326d92ad
- (id)init;	// 0x326d9315
- (id)_ancillaryDescription;	// 0x326d94b5
- (id)_groupID;	// 0x326d9871
- (BOOL)_isDesignatedDefault;	// 0x326d9885
- (id)_title;	// 0x326d9915
- (id)associatedMediaSelectionOptionInMediaSelectionGroup:(id)mediaSelectionGroup;	// 0x326d99fd
// declared property getter: - (id)availableMetadataFormats;	// 0x326d99f5
// declared property getter: - (id)commonMetadata;	// 0x326d9911
- (id)copyWithZone:(NSZone *)zone;	// 0x326d93e5
- (void)dealloc;	// 0x326d9395
- (id)description;	// 0x326d93f5
- (id)dictionary;	// 0x326d9831
- (BOOL)displaysNonForcedSubtitles;	// 0x326d98cd
- (id)group;	// 0x326d986d
- (BOOL)hasMediaCharacteristic:(id)characteristic;	// 0x326d987d
// declared property getter: - (BOOL)isPlayable;	// 0x326d9881
// declared property getter: - (id)locale;	// 0x326d98c9
// declared property getter: - (id)mediaSubTypes;	// 0x326d9879
// declared property getter: - (id)mediaType;	// 0x326d9875
- (id)metadataForFormat:(id)format;	// 0x326d99f9
- (id)optionID;	// 0x326d9835
- (id)propertyList;	// 0x326d9a01
@end

