/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceIdentifiable.h"
#import "AceObject.h"

@class NSURL;

@interface SADomainObject : AceObject <SAAceIdentifiable> {
}
@property(copy, nonatomic) NSURL *identifier;	// G=0x342442d5; S=0x34244351; @dynamic
+ (id)domainObject;	// 0x34244245
+ (id)domainObjectWithDictionary:(id)dictionary context:(id)context;	// 0x34244289
- (id)encodedClassName;	// 0x34244239
- (id)groupIdentifier;	// 0x34244229
// declared property getter: - (id)identifier;	// 0x342442d5
// declared property setter: - (void)setIdentifier:(id)identifier;	// 0x34244351
- (void)updateUsingSet:(id)set add:(id)add remove:(id)remove;	// 0x342443b1
@end

