/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAServerBoundCommand.h"
#import "SABaseClientBoundCommand.h"

@class SAFmfGeoFence, NSString, NSURL;

@interface SAFmfGeoFenceSetCompleted : SABaseClientBoundCommand <SAServerBoundCommand> {
}
@property(copy, nonatomic) NSString *aceId;	// @dynamic
@property(retain, nonatomic) SAFmfGeoFence *geoFence;	// G=0x34252279; S=0x342522cd; 
@property(copy, nonatomic) NSString *refId;	// @dynamic
@property(copy, nonatomic) NSURL *searchContext;	// G=0x34252309; S=0x34252385; 
@property(copy, nonatomic) NSURL *targetAppId;	// G=0x3425219d; S=0x34252219; 
+ (id)geoFenceSetCompleted;	// 0x3425210d
+ (id)geoFenceSetCompletedWithDictionary:(id)dictionary context:(id)context;	// 0x34252151
- (id)encodedClassName;	// 0x34252101
// declared property getter: - (id)geoFence;	// 0x34252279
- (id)groupIdentifier;	// 0x342520f1
- (BOOL)requiresResponse;	// 0x342523e5
// declared property getter: - (id)searchContext;	// 0x34252309
// declared property setter: - (void)setGeoFence:(id)fence;	// 0x342522cd
// declared property setter: - (void)setSearchContext:(id)context;	// 0x34252385
// declared property setter: - (void)setTargetAppId:(id)anId;	// 0x34252219
// declared property getter: - (id)targetAppId;	// 0x3425219d
@end

