/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSData, NSArray, NSURL;

@interface SALocalSearchSendToProtobufConduit : SABaseClientBoundCommand {
}
@property(copy, nonatomic) NSArray *attributes;	// G=0x342650e9; S=0x34265165; 
@property(copy, nonatomic) NSURL *endpoint;	// G=0x342651cd; S=0x34265249; 
@property(copy, nonatomic) NSData *rawRequest;	// G=0x342652a9; S=0x342652c5; 
@property(copy, nonatomic) NSURL *targetAppId;	// G=0x3426500d; S=0x34265089; 
@property(assign, nonatomic) int timeoutInSeconds;	// G=0x34265315; S=0x34265385; 
+ (id)sendToProtobufConduit;	// 0x34264f7d
+ (id)sendToProtobufConduitWithDictionary:(id)dictionary context:(id)context;	// 0x34264fc1
// declared property getter: - (id)attributes;	// 0x342650e9
- (id)encodedClassName;	// 0x34264f71
// declared property getter: - (id)endpoint;	// 0x342651cd
- (id)groupIdentifier;	// 0x34264f61
// declared property getter: - (id)rawRequest;	// 0x342652a9
- (BOOL)requiresResponse;	// 0x342653c9
// declared property setter: - (void)setAttributes:(id)attributes;	// 0x34265165
// declared property setter: - (void)setEndpoint:(id)endpoint;	// 0x34265249
// declared property setter: - (void)setRawRequest:(id)request;	// 0x342652c5
// declared property setter: - (void)setTargetAppId:(id)anId;	// 0x34265089
// declared property setter: - (void)setTimeoutInSeconds:(int)seconds;	// 0x34265385
// declared property getter: - (id)targetAppId;	// 0x3426500d
// declared property getter: - (int)timeoutInSeconds;	// 0x34265315
@end

