/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAServerBoundCommand.h"
#import "SABaseCommand.h"

@class NSNumber, SAMPMediaItem, NSString;

@interface SAMPGetStateResponse : SABaseCommand <SAServerBoundCommand> {
}
@property(copy, nonatomic) NSString *aceId;	// @dynamic
@property(retain, nonatomic) SAMPMediaItem *listeningToItem;	// G=0x3422ce39; S=0x3422ce8d; 
@property(copy, nonatomic) NSNumber *listeningToMusicApplication;	// G=0x3422cec9; S=0x3422cee5; 
@property(copy, nonatomic) NSString *refId;	// @dynamic
@property(assign, nonatomic) int state;	// G=0x3422cf35; S=0x3422cf5d; 
+ (id)getStateResponse;	// 0x3422cda9
+ (id)getStateResponseWithDictionary:(id)dictionary context:(id)context;	// 0x3422cded
- (id)encodedClassName;	// 0x3422cd9d
- (id)groupIdentifier;	// 0x3422cd8d
// declared property getter: - (id)listeningToItem;	// 0x3422ce39
// declared property getter: - (id)listeningToMusicApplication;	// 0x3422cec9
// declared property setter: - (void)setListeningToItem:(id)item;	// 0x3422ce8d
// declared property setter: - (void)setListeningToMusicApplication:(id)musicApplication;	// 0x3422cee5
// declared property setter: - (void)setState:(int)state;	// 0x3422cf5d
// declared property getter: - (int)state;	// 0x3422cf35
@end

