/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <ML3Album.h> // Unknown library


@interface ML3Album (MPMediaAdditions)
+ (id)countingQueryForMPMediaEntityProperty:(id)mpmediaEntityProperty library:(id)library identifier:(long long)identifier;	// 0x341dfc91
+ (id)propertyForMPMediaEntityProperty:(id)mpmediaEntityProperty;	// 0x341dfabd
@end

