/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "EDProcessor.h"
#import "OfficeImport-Structs.h"


@interface CHPValueAxisFormatting : EDProcessor {
}
- (void)applyProcessorToObject:(id)object sheet:(id)sheet;	// 0x33ad0169
- (id)dataPointFormattingInData:(id)data;	// 0x33ad0535
- (id)dataPointFormattingInSeriesCollection:(id)seriesCollection;	// 0x33ad046d
- (id)dataPointFormattingInSources:(id)sources;	// 0x33ad4f49
- (bool)isObjectSupported:(id)supported;	// 0x33acc255
- (bool)isPercentageFormattingInContentFormatString:(id)contentFormatString edValue:(EDValue *)value;	// 0x33ad0611
@end

