/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OADEffect.h"

@class OADFill;

@interface OADFillOverlayEffect : OADEffect {
	int mBlendMode;	// 8 = 0x8
	OADFill *mFill;	// 12 = 0xc
}
@property(assign) int blendMode;	// G=0x33ba1499; S=0x33b15601; converted property
@property(retain) id fill;	// G=0x33ba14a9; S=0x33b15611; converted property
- (id)init;	// 0x33b15569
// converted property getter: - (int)blendMode;	// 0x33ba1499
- (void)dealloc;	// 0x33b15651
// converted property getter: - (id)fill;	// 0x33ba14a9
- (unsigned)hash;	// 0x33ba14b9
- (BOOL)isEqual:(id)equal;	// 0x33ba1511
// converted property setter: - (void)setBlendMode:(int)mode;	// 0x33b15601
// converted property setter: - (void)setFill:(id)fill;	// 0x33b15611
@end

