/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import <NSObject.h> // Unknown library


@interface ODIDrawable : NSObject {
}
+ (void)addArrowHeadToShapeProperties:(id)shapeProperties;	// 0x33c3ef2d
+ (id)addShapeWithBounds:(CGRect)bounds rotation:(float)rotation geometry:(id)geometry state:(id)state;	// 0x33c3e475
+ (void)map1dArrowStyleFromPoint:(id)point shape:(id)shape state:(id)state;	// 0x33c3e905
+ (void)map1dArrowStyleToShape:(id)shape state:(id)state;	// 0x33c3ea05
+ (void)mapShapeProperties:(id)properties shape:(id)shape state:(id)state;	// 0x33c3ee95
+ (void)mapShapeProperties:(id)properties shapeStyle:(id)style shape:(id)shape state:(id)state;	// 0x33c3ee25
+ (void)mapStyleAndTextFromPoint:(id)point shape:(id)shape state:(id)state;	// 0x33c3eb0d
+ (void)mapStyleForLabelName:(id)labelName point:(id)point shape:(id)shape state:(id)state;	// 0x33c3e869
+ (void)mapStyleForLabelName:(id)labelName shape:(id)shape state:(id)state;	// 0x33c3e7b1
+ (void)mapStyleForPresentationName:(id)presentationName point:(id)point shape:(id)shape state:(id)state;	// 0x33c3e70d
+ (void)mapStyleFromPoint:(id)point shape:(id)shape state:(id)state;	// 0x33c3e5dd
+ (id)presentationWithName:(id)name point:(id)point;	// 0x33c3eba1
+ (id)shapeGeometryForBezierPath:(CGPathRef)bezierPath gSpace:(CGRect)space;	// 0x33c3df69
+ (id)shapeGeometryForDoubleArrowWithControlPoint:(CGPoint)controlPoint;	// 0x33c3ddfd
+ (id)shapeGeometryForEllipse;	// 0x33c3dc2d
+ (id)shapeGeometryForRectangle;	// 0x33c3dbd1
+ (id)shapeGeometryForRightArrowWithControlPoint:(CGPoint)controlPoint;	// 0x33c3dd29
+ (id)shapeGeometryForRoundedRectangleWithRadius:(float)radius;	// 0x33c3dc89
+ (id)shapeGeometryWithShapeType:(int)shapeType adjustValues:(const int *)values;	// 0x33c3dec1
+ (CGSize)sizeOfDiagram:(id)diagram;	// 0x33c3e41d
+ (id)styleForLabelName:(id)labelName styleCount:(int)count styleIndex:(int)index state:(id)state;	// 0x33c3ed51
+ (id)styleForPresentation:(id)presentation point:(id)point state:(id)state;	// 0x33c3ec7d
@end

