/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

#import "NSMutableCopying.h"
#import <NSObject.h> // Unknown library
#import "SSXPCCoding.h"
#import "StoreServices-Structs.h"
#import "NSCopying.h"

@class NSArray, NSString;

@interface SSSoftwareUpdatesContext : NSObject <SSXPCCoding, NSCopying, NSMutableCopying> {
	NSString *_clientIdentifierHeader;	// 4 = 0x4
	BOOL _forced;	// 8 = 0x8
	NSArray *_softwareTypes;	// 12 = 0xc
}
@property(readonly, assign, nonatomic) NSString *clientIdentifierHeader;	// G=0x354cdb21; @synthesize=_clientIdentifierHeader
@property(readonly, assign, nonatomic, getter=isForced) BOOL forced;	// G=0x354cdb35; @synthesize=_forced
@property(readonly, assign, nonatomic) NSArray *softwareTypes;	// G=0x354cd865; @synthesize=_softwareTypes
- (id)initWithXPCEncoding:(id)xpcencoding;	// 0x354cd939
// declared property getter: - (id)clientIdentifierHeader;	// 0x354cdb21
- (id)copyWithZone:(NSZone *)zone;	// 0x354cd9f9
- (id)copyXPCEncoding;	// 0x354cd8d9
- (void)dealloc;	// 0x354cd801
// declared property getter: - (BOOL)isForced;	// 0x354cdb35
- (id)mutableCopyWithZone:(NSZone *)zone;	// 0x354cda8d
// declared property getter: - (id)softwareTypes;	// 0x354cd865
@end

