/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iCalendar.framework/iCalendar
 */

#import "ICSComponent.h"

@class ICSDuration, ICSColor, NSMutableSet, NSMutableDictionary, NSMutableArray, NSString;

@interface ICSCalendar : ICSComponent {
	NSMutableSet *_keys;	// 12 = 0xc
	NSMutableDictionary *_masters;	// 16 = 0x10
	NSMutableDictionary *_occurrences;	// 20 = 0x14
	NSMutableDictionary *_timezones;	// 24 = 0x18
	NSMutableArray *_parsingErrors;	// 28 = 0x1c
}
@property(retain) NSString *calscale;	// G=0x33c45e91; S=0x33c45ed9; 
@property(assign) int method;	// G=0x33c45ef9; S=0x33c45f51; 
@property(readonly, retain) NSMutableArray *parsingErrors;	// G=0x33c477c9; converted property
@property(retain) NSString *prodid;	// G=0x33c45fa1; S=0x33c45fe9; 
@property(retain) NSString *version;	// G=0x33c46009; S=0x33c46051; 
@property(retain) ICSDuration *x_apple_auto_refresh;	// G=0x33c46071; S=0x33c460d5; 
@property(retain) ICSColor *x_apple_calendar_color;	// G=0x33c46105; S=0x33c46281; 
@property(assign) BOOL x_apple_ignore_on_restore;	// @dynamic
@property(assign) int x_calendarserver_access;	// @dynamic
@property(retain) NSString *x_wr_caldesc;	// G=0x33c46349; S=0x33c46329; 
@property(retain) NSString *x_wr_calname;	// G=0x33c46391; S=0x33c463d9; 
@property(retain) NSString *x_wr_relcalid;	// G=0x33c463f9; S=0x33c46441; 
@property(retain) NSString *x_wr_timezone;	// G=0x33c46461; S=0x33c464a9; 
+ (id)ICSStringFromCalendarServerAccess:(int)calendarServerAccess;	// 0x33c45d21
+ (id)ICSStringFromMethod:(int)method;	// 0x33c45c25
+ (int)calendarServerAccessFromICSString:(id)icsstring;	// 0x33c45c9d
+ (id)calendarWithKnownTimeZones;	// 0x33c456f9
+ (id)defaultProdid;	// 0x33c45a59
+ (int)methodFromICSString:(id)icsstring;	// 0x33c45b31
+ (id)name;	// 0x33c45965
+ (void)setDefaultProdid:(id)prodid;	// 0x33c45971
- (id)init;	// 0x33c45d65
- (void)_addComponent:(id)component;	// 0x33c47209
- (void)_addTimeZonesInComponent:(id)component toDictionary:(id)dictionary;	// 0x33c46a91
- (void)_addTimeZonesInComponent:(id)component toSet:(id)set;	// 0x33c46801
- (id)_init;	// 0x33c45869
- (id)_timeZonesForComponents:(id)components options:(int)options;	// 0x33c46d69
- (void)addComponent:(id)component;	// 0x33c47745
- (void)addParsingError:(id)error;	// 0x33c477a9
// declared property getter: - (id)calscale;	// 0x33c45e91
- (id)componentForKey:(id)key;	// 0x33c47521
- (id)componentKeys;	// 0x33c47501
- (id)componentOccurrencesForKey:(id)key;	// 0x33c47541
- (void)dealloc;	// 0x33c45df1
- (void)fixComponent;	// 0x33c479a9
- (void)fixEntities;	// 0x33c47a55
- (void)fixPropertiesInheritance;	// 0x33c47829
// declared property getter: - (int)method;	// 0x33c45ef9
// converted property getter: - (id)parsingErrors;	// 0x33c477c9
// declared property getter: - (id)prodid;	// 0x33c45fa1
- (id)propertiesToIncludeForChecksumVersion:(int)checksumVersion;	// 0x33c47801
// declared property setter: - (void)setCalscale:(id)calscale;	// 0x33c45ed9
- (void)setComponents:(id)components;	// 0x33c47731
- (void)setComponents:(id)components options:(int)options;	// 0x33c47579
- (void)setComponents:(id)components timeZones:(BOOL)zones;	// 0x33c47561
// declared property setter: - (void)setMethod:(int)method;	// 0x33c45f51
// declared property setter: - (void)setProdid:(id)prodid;	// 0x33c45fe9
// declared property setter: - (void)setVersion:(id)version;	// 0x33c46051
// declared property setter: - (void)setX_apple_auto_refresh:(id)refresh;	// 0x33c460d5
// declared property setter: - (void)setX_apple_calendar_color:(id)color;	// 0x33c46281
// declared property setter: - (void)setX_wr_caldesc:(id)caldesc;	// 0x33c46329
// declared property setter: - (void)setX_wr_calname:(id)calname;	// 0x33c463d9
// declared property setter: - (void)setX_wr_relcalid:(id)relcalid;	// 0x33c46441
// declared property setter: - (void)setX_wr_timezone:(id)timezone;	// 0x33c464a9
- (id)systemCalendarForDate:(id)date options:(int)options;	// 0x33c465d1
- (id)systemDateForDate:(id)date options:(int)options;	// 0x33c4668d
- (id)systemTimeZoneForDate:(id)date;	// 0x33c464c9
- (id)timeZoneForKey:(id)key;	// 0x33c47789
// declared property getter: - (id)version;	// 0x33c46009
// declared property getter: - (id)x_apple_auto_refresh;	// 0x33c46071
// declared property getter: - (id)x_apple_calendar_color;	// 0x33c46105
// declared property getter: - (id)x_wr_caldesc;	// 0x33c46349
// declared property getter: - (id)x_wr_calname;	// 0x33c46391
// declared property getter: - (id)x_wr_relcalid;	// 0x33c463f9
// declared property getter: - (id)x_wr_timezone;	// 0x33c46461
@end

