/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iCalendar.framework/iCalendar
 */

#import </libobjc.A.h>

@class ICSCalendar;

@interface ICSDocument : NSObject {
	ICSCalendar *_calendar;	// 4 = 0x4
}
@property(readonly, retain) ICSCalendar *calendar;	// G=0x33c512c1; converted property
+ (int)ICSChecksumVersionSpecifiedInOptions:(unsigned)options;	// 0x33c514b1
+ (void)suppressParserSyntaxErrorLogging;	// 0x33c514e1
- (id)initWithCalendar:(id)calendar;	// 0x33c51221
- (id)initWithContentsOfURL:(id)url options:(unsigned)options error:(id *)error;	// 0x33c51079
- (id)initWithData:(id)data encoding:(unsigned)encoding options:(unsigned)options error:(id *)error;	// 0x33c510cd
- (id)initWithData:(id)data options:(unsigned)options error:(id *)error;	// 0x33c51169
- (id)initWithICSString:(id)icsstring options:(unsigned)options error:(id *)error;	// 0x33c51041
- (id)ICSChecksumForVersion:(int)version;	// 0x33c513c9
- (id)ICSChecksumStringForVersion:(int)version;	// 0x33c513ad
- (id)ICSDataWithOptions:(unsigned)options;	// 0x33c512d1
- (id)ICSStringWithOptions:(unsigned)options;	// 0x33c51351
// converted property getter: - (id)calendar;	// 0x33c512c1
- (void)dealloc;	// 0x33c51275
- (BOOL)validate:(id *)validate;	// 0x33c514b9
@end

