/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BRViewController.h"
#import "BRSecureResource.h"

@class BRMediaMenuView, BRWaitPromptControl, ATVDataQuery, BRController;

__attribute__((visibility("hidden")))
@interface ATViCloudActivatePhotosController : BRViewController <BRSecureResource> {
	BOOL _canDisplayActivation;	// 104 = 0x68
	BOOL _shouldEnableShared;	// 105 = 0x69
	BOOL _shouldAskForScreenSaverPhotos;	// 106 = 0x6a
	BOOL _cupidAccountOnInit;	// 107 = 0x6b
	BOOL _didActivatePhotos;	// 108 = 0x6c
	BRController *_activatingController;	// 112 = 0x70
	ATVDataQuery *_query;	// 116 = 0x74
	BRWaitPromptControl *_waitPrompt;	// 120 = 0x78
	BRMediaMenuView *_activationView;	// 124 = 0x7c
}
@property(retain, nonatomic) BRController *activatingController;	// G=0x2cf6d5; S=0x2cf6e5; @synthesize=_activatingController
@property(retain, nonatomic) BRMediaMenuView *activationView;	// G=0x2cf7bd; S=0x2cf7cd; @synthesize=_activationView
@property(assign, nonatomic) BOOL canDisplayActivation;	// G=0x2cf675; S=0x2cf685; @synthesize=_canDisplayActivation
@property(assign, nonatomic) BOOL cupidAccountOnInit;	// G=0x2cf70d; S=0x2cf71d; @synthesize=_cupidAccountOnInit
@property(assign, nonatomic) BOOL didActivatePhotos;	// G=0x2cf765; S=0x2cf775; @synthesize=_didActivatePhotos
@property(retain, nonatomic) ATVDataQuery *query;	// G=0x2cf72d; S=0x2cf73d; @synthesize=_query
@property(assign, nonatomic) BOOL shouldAskForScreenSaverPhotos;	// G=0x2cf6b5; S=0x2cf6c5; @synthesize=_shouldAskForScreenSaverPhotos
@property(assign, nonatomic) BOOL shouldEnableShared;	// G=0x2cf695; S=0x2cf6a5; @synthesize=_shouldEnableShared
@property(retain, nonatomic) BRWaitPromptControl *waitPrompt;	// G=0x2cf785; S=0x2cf795; @synthesize=_waitPrompt
- (id)init;	// 0x2ce905
- (void).cxx_destruct;	// 0x2cf7f5
- (void)_activatePhotos;	// 0x2cf2b5
- (void)_dismiss;	// 0x2cf33d
- (void)_displayScreensaverDialog;	// 0x2cef15
- (void)_queryComplete:(id)complete;	// 0x2cf415
- (void)_showSpinner;	// 0x2cf57d
// declared property getter: - (id)activatingController;	// 0x2cf6d5
// declared property getter: - (id)activationView;	// 0x2cf7bd
- (BOOL)brEventAction:(id)action;	// 0x2cece5
// declared property getter: - (BOOL)canDisplayActivation;	// 0x2cf675
- (void)controlWasActivated;	// 0x2cec09
// declared property getter: - (BOOL)cupidAccountOnInit;	// 0x2cf70d
// declared property getter: - (BOOL)didActivatePhotos;	// 0x2cf765
- (void)list:(id)list didSelectItemAtIndexPath:(id)indexPath;	// 0x2cee85
- (id)list:(id)list menuItemForRowAtIndexPath:(id)indexPath;	// 0x2cedd9
- (long)list:(id)list numberOfRowsInSection:(long)section;	// 0x2cef11
// declared property getter: - (id)query;	// 0x2cf72d
- (id)secureResourceAuthenticator;	// 0x2ced55
// declared property setter: - (void)setActivatingController:(id)controller;	// 0x2cf6e5
// declared property setter: - (void)setActivationView:(id)view;	// 0x2cf7cd
// declared property setter: - (void)setCanDisplayActivation:(BOOL)activation;	// 0x2cf685
// declared property setter: - (void)setCupidAccountOnInit:(BOOL)init;	// 0x2cf71d
// declared property setter: - (void)setDidActivatePhotos:(BOOL)activatePhotos;	// 0x2cf775
// declared property setter: - (void)setQuery:(id)query;	// 0x2cf73d
// declared property setter: - (void)setShouldAskForScreenSaverPhotos:(BOOL)askForScreenSaverPhotos;	// 0x2cf6c5
// declared property setter: - (void)setShouldEnableShared:(BOOL)enableShared;	// 0x2cf6a5
// declared property setter: - (void)setWaitPrompt:(id)prompt;	// 0x2cf795
// declared property getter: - (BOOL)shouldAskForScreenSaverPhotos;	// 0x2cf6b5
// declared property getter: - (BOOL)shouldEnableShared;	// 0x2cf695
// declared property getter: - (id)waitPrompt;	// 0x2cf785
@end

