/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSecureResource.h"
#import <BRController.h> // Unknown library

@class NSDictionary, BRWaitPromptControl;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreAcquisitionController : BRController <BRSecureResource> {
@private
	NSDictionary *_offer;	// 60 = 0x3c
	BRWaitPromptControl *_waitPrompt;	// 64 = 0x40
}
- (id)initWithOffer:(id)offer;	// 0x30791d31
- (void)_acquire;	// 0x3079199d
- (void)_acquisitionFailed:(id)failed;	// 0x30791bcd
- (void)_acquisitionSuccessful:(id)successful;	// 0x30791eed
- (void)_dismiss:(id)dismiss;	// 0x307918f1
- (void)_enablePrompt:(id)prompt;	// 0x30791959
- (void)dealloc;	// 0x30791b5d
- (void)requiredScope:(unsigned *)scope accountType:(id *)type;	// 0x30791b29
- (void)wasPopped;	// 0x30791aa5
- (void)wasPushed;	// 0x30791af9
@end

