/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface NccpTransactionResult : NSObject {
@private
	NSString *method;	// 4 = 0x4
	int nccpErr;	// 8 = 0x8
	int httpErr;	// 12 = 0xc
	NSString *nwErr;	// 16 = 0x10
	NSString *errorMsg;	// 20 = 0x14
}
@property(readonly, retain) NSString *errorMsg;	// G=0x308e952c; @synthesize
@property(readonly, assign) int httpErr;	// G=0x308e8134; @synthesize
@property(readonly, retain) NSString *method;	// G=0x308e94ec; @synthesize
@property(readonly, assign) int nccpErr;	// G=0x308e8148; @synthesize
@property(readonly, retain) NSString *nwErr;	// G=0x308e950c; @synthesize
- (id)init;	// 0x308e83ec
- (void)dealloc;	// 0x308e9438
// declared property getter: - (id)errorMsg;	// 0x308e952c
// declared property getter: - (int)httpErr;	// 0x308e8134
// declared property getter: - (id)method;	// 0x308e94ec
// declared property getter: - (int)nccpErr;	// 0x308e8148
// declared property getter: - (id)nwErr;	// 0x308e950c
- (void)reset;	// 0x308e9380
- (void)setNccpTransactionResult:(id)result withNccpErr:(int)nccpErr withHttpErr:(int)httpErr withNWErr:(id)nwerr withErrorMsg:(id)errorMsg;	// 0x308e924c
- (void)setNccpTransactionResultWithErrorMsg:(id)errorMsg;	// 0x308e91e0
@end

