/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BRControl.h"

@class BRPasscodeEntryControl, NSString, BRHeaderControl, BRTextControl;
@protocol SettingsPINEntryViewDelegate;

__attribute__((visibility("hidden")))
@interface SettingsPINEntryView : BRControl {
	BRHeaderControl *_header;	// 84 = 0x54
	BRPasscodeEntryControl *_editor;	// 88 = 0x58
	BRTextControl *_prompt;	// 92 = 0x5c
	NSString *_initialPINCode;	// 96 = 0x60
	id<SettingsPINEntryViewDelegate> _delegate;	// 100 = 0x64
}
@property(assign) id delegate;	// G=0xbdaa9; S=0xbda95; converted property
@property(retain) BRTextControl *prompt;	// G=0xbd9f9; S=0xbd939; converted property
@property(retain) id title;	// G=0xbd919; S=0xbd8f9; converted property
- (id)init;	// 0xbd38d
- (id)initWithNumDigits:(unsigned)numDigits userEditable:(BOOL)editable hideDigits:(BOOL)digits prompt:(id)prompt;	// 0xbd3f1
- (void).cxx_destruct;	// 0xbdb61
- (void)dealloc;	// 0xbd60d
// converted property getter: - (id)delegate;	// 0xbdaa9
- (void)layoutSubcontrols;	// 0xbd679
- (void)pinFailedTryAgainWithTitle:(id)title prompt:(id)prompt;	// 0xbdac9
// converted property getter: - (id)prompt;	// 0xbd9f9
// converted property setter: - (void)setDelegate:(id)delegate;	// 0xbda95
- (void)setInitialPINCode:(id)code;	// 0xbda4d
// converted property setter: - (void)setPrompt:(id)prompt;	// 0xbd939
// converted property setter: - (void)setTitle:(id)title;	// 0xbd8f9
- (void)textDidChange:(id)text;	// 0xbd8a5
- (void)textDidEndEditing:(id)text;	// 0xbd8a9
// converted property getter: - (id)title;	// 0xbd919
@end

