/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class Buffer;

@interface TransportPacket : XXUnknownSuperclass {
	Buffer *buffer;	// 4 = 0x4
	int payloadLength;	// 8 = 0x8
	BOOL objectID[17];	// 12 = 0xc
}
- (id)initWithData:(char *)data length:(unsigned)length;	// 0x49fff1
- (id)initWithData:(char *)data offset:(unsigned)offset length:(unsigned)length;	// 0x4a0011
- (void)dealloc;	// 0x4a0295
- (id)getError;	// 0x4a0291
- (char *)getHeaderObjectID;	// 0x4a0281
- (char *)getPayload;	// 0x4a0261
- (int)getPayloadLength;	// 0x4a0251
@end

