/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OADProperties3DParent.h"
#import "OADDrawableProperties.h"
#import "OADEffectsParent.h"

@class OADScene3D, OADStroke, OADFill, NSArray, OADShape3D;

__attribute__((visibility("hidden")))
@interface OADGraphicProperties : OADDrawableProperties <OADEffectsParent, OADProperties3DParent> {
@private
	OADFill *mFill;	// 28 = 0x1c
	NSArray *mEffects;	// 32 = 0x20
	OADScene3D *mScene3D;	// 36 = 0x24
	OADShape3D *mShape3D;	// 40 = 0x28
	OADStroke *mStroke;	// 44 = 0x2c
	unsigned mHasIsBehindText : 1;	// 48 = 0x30
	unsigned mIsBehindText : 1;	// 48 = 0x30
}
@property(retain) id effects;	// G=0x351ae845; S=0x351a34fd; converted property
@property(retain) id fill;	// G=0x35128b75; S=0x351a0a75; converted property
@property(assign) BOOL isBehindText;	// G=0x3526fafd; S=0x351e4431; converted property
@property(retain) id scene3D;	// G=0x353c92a9; S=0x351e42a1; converted property
@property(retain) id shape3D;	// G=0x353c9279; S=0x351e43f1; converted property
@property(retain) id stroke;	// G=0x351294e9; S=0x351a30b9; converted property
- (id)initWithDefaults;	// 0x351e3c8d
- (void)dealloc;	// 0x351b2789
// converted property getter: - (id)effects;	// 0x351ae845
// converted property getter: - (id)fill;	// 0x35128b75
- (BOOL)hasEffects;	// 0x351ae80d
- (BOOL)hasFill;	// 0x35128ba5
- (BOOL)hasIsBehindText;	// 0x351af1c9
- (BOOL)hasScene3D;	// 0x351ae875
- (BOOL)hasShape3D;	// 0x351ae8ad
- (BOOL)hasStroke;	// 0x35129519
- (unsigned)hash;	// 0x353c9145
// converted property getter: - (BOOL)isBehindText;	// 0x3526fafd
- (BOOL)isEqual:(id)equal;	// 0x353c8dd1
- (void)removeUnnecessaryOverrides;	// 0x351ae409
// converted property getter: - (id)scene3D;	// 0x353c92a9
// converted property setter: - (void)setEffects:(id)effects;	// 0x351a34fd
// converted property setter: - (void)setFill:(id)fill;	// 0x351a0a75
// converted property setter: - (void)setIsBehindText:(BOOL)text;	// 0x351e4431
- (void)setParent:(id)parent;	// 0x351303bd
// converted property setter: - (void)setScene3D:(id)d;	// 0x351e42a1
// converted property setter: - (void)setShape3D:(id)d;	// 0x351e43f1
// converted property setter: - (void)setStroke:(id)stroke;	// 0x351a30b9
// converted property getter: - (id)shape3D;	// 0x353c9279
// converted property getter: - (id)stroke;	// 0x351294e9
@end

