/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OADColor.h"
#import "OfficeImport-Structs.h"


__attribute__((visibility("hidden")))
@interface OADIndexedColor : OADColor {
@private
	int mIndex;	// 8 = 0x8
}
+ (id)indexedColorWithIndex:(int)index;	// 0x35644b8d
- (id)initWithIndex:(int)index;	// 0x35644bd9
- (id)colorFromPalette:(id)palette;	// 0x35780f05
- (id)copyWithZone:(NSZone *)zone;	// 0x3564bc2d
- (unsigned)hash;	// 0x35780ec9
- (int)index;	// 0x35658d89
- (BOOL)isEqual:(id)equal;	// 0x35780e25
@end

