/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <NSObject.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface PDHeadersFooters : NSObject {
@private
	BOOL mHasDateTime;	// 4 = 0x4
	BOOL mHasNowDateTime;	// 5 = 0x5
	BOOL mHasUserDateTime;	// 6 = 0x6
	BOOL mHasSlideNumber;	// 7 = 0x7
	BOOL mHasHeader;	// 8 = 0x8
	BOOL mHasFooter;	// 9 = 0x9
	int mDateTimeFormat;	// 12 = 0xc
	NSString *mUserDateTime;	// 16 = 0x10
	NSString *mHeader;	// 20 = 0x14
	NSString *mFooter;	// 24 = 0x18
}
@property(retain) id footer;	// G=0x356fa46d; S=0x356fa4fd; converted property
@property(assign) BOOL hasDateTime;	// G=0x356fa38d; S=0x356fa39d; converted property
@property(assign) BOOL hasFooter;	// G=0x356fa42d; S=0x356fa43d; converted property
@property(assign) BOOL hasHeader;	// G=0x356fa40d; S=0x356fa41d; converted property
@property(assign) BOOL hasNowDateTime;	// G=0x356fa3ad; S=0x356fa3bd; converted property
@property(assign) BOOL hasSlideNumber;	// G=0x356fa3ed; S=0x356fa3fd; converted property
@property(assign) BOOL hasUserDateTime;	// G=0x356fa3cd; S=0x356fa3dd; converted property
@property(retain) id header;	// G=0x356fa45d; S=0x356fa4bd; converted property
@property(retain) id userDateTime;	// G=0x356fa44d; S=0x356fa47d; converted property
- (void)dealloc;	// 0x356fa53d
// converted property getter: - (id)footer;	// 0x356fa46d
// converted property getter: - (BOOL)hasDateTime;	// 0x356fa38d
// converted property getter: - (BOOL)hasFooter;	// 0x356fa42d
// converted property getter: - (BOOL)hasHeader;	// 0x356fa40d
// converted property getter: - (BOOL)hasNowDateTime;	// 0x356fa3ad
// converted property getter: - (BOOL)hasSlideNumber;	// 0x356fa3ed
// converted property getter: - (BOOL)hasUserDateTime;	// 0x356fa3cd
// converted property getter: - (id)header;	// 0x356fa45d
// converted property setter: - (void)setFooter:(id)footer;	// 0x356fa4fd
// converted property setter: - (void)setHasDateTime:(BOOL)time;	// 0x356fa39d
// converted property setter: - (void)setHasFooter:(BOOL)footer;	// 0x356fa43d
// converted property setter: - (void)setHasHeader:(BOOL)header;	// 0x356fa41d
// converted property setter: - (void)setHasNowDateTime:(BOOL)time;	// 0x356fa3bd
// converted property setter: - (void)setHasSlideNumber:(BOOL)number;	// 0x356fa3fd
// converted property setter: - (void)setHasUserDateTime:(BOOL)time;	// 0x356fa3dd
// converted property setter: - (void)setHeader:(id)header;	// 0x356fa4bd
// converted property setter: - (void)setUserDateTime:(id)time;	// 0x356fa47d
// converted property getter: - (id)userDateTime;	// 0x356fa44d
@end

