/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKit.framework/EventKit
 */

#import "EventKit-Structs.h"
#import "NSCopying.h"
#import "EKObject.h"

@class NSString, NSURL;

@interface EKParticipant : EKObject <NSCopying> {
}
@property(readonly, assign, nonatomic) NSURL *URL;	// G=0x318deafd; 
@property(retain) id address;	// G=0x31896ef5; S=0x318dea61; converted property
@property(retain) id emailAddress;	// G=0x318970b9; S=0x318dea45; converted property
@property(retain) id firstName;	// G=0x318dea7d; S=0x318dea99; converted property
@property(readonly, assign, nonatomic) BOOL isCurrentUser;	// G=0x318deaf9; 
@property(retain) id lastName;	// G=0x318deab5; S=0x318dead1; converted property
@property(readonly, assign, nonatomic) NSString *name;	// G=0x318970f1; 
@property(readonly, assign, nonatomic) int participantRole;	// G=0x318deaf5; 
@property(readonly, assign, nonatomic) int participantStatus;	// G=0x318deaf1; 
@property(readonly, assign, nonatomic) int participantType;	// G=0x318deaed; 
+ (void *)findABPersonByURL:(id)url inAddressBook:(void *)addressBook;	// 0x318decad
- (void *)ABRecordWithAddressBook:(void *)addressBook;	// 0x318deb7d
// declared property getter: - (id)URL;	// 0x318deafd
- (id)UUID;	// 0x31896d25
- (id)_persistentItem;	// 0x31896d4d
// converted property getter: - (id)address;	// 0x31896ef5
- (id)copyWithZone:(NSZone *)zone;	// 0x318de9ed
// converted property getter: - (id)emailAddress;	// 0x318970b9
// converted property getter: - (id)firstName;	// 0x318dea7d
// declared property getter: - (BOOL)isCurrentUser;	// 0x318deaf9
- (BOOL)isEqualToParticipant:(id)participant;	// 0x31896e6d
// converted property getter: - (id)lastName;	// 0x318deab5
// declared property getter: - (id)name;	// 0x318970f1
// declared property getter: - (int)participantRole;	// 0x318deaf5
// declared property getter: - (int)participantStatus;	// 0x318deaf1
// declared property getter: - (int)participantType;	// 0x318deaed
// converted property setter: - (void)setAddress:(id)address;	// 0x318dea61
- (void)setDisplayName:(id)name;	// 0x318dea29
// converted property setter: - (void)setEmailAddress:(id)address;	// 0x318dea45
// converted property setter: - (void)setFirstName:(id)name;	// 0x318dea99
// converted property setter: - (void)setLastName:(id)name;	// 0x318dead1
@end

