/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRProvider.h"
#import <NSObject.h> // Unknown library

@class NSArray;

__attribute__((visibility("hidden")))
@interface BRApplianceProvider : NSObject <BRProvider> {
@private
	NSArray *_applianceInfo;	// 4 = 0x4
}
- (id)init;	// 0x331ef785
- (void)_loadAppliances;	// 0x331efa2d
- (id)applianceInfoAtIndex:(long)index;	// 0x331ef8b9
- (long)applianceInfoIndexForKey:(id)key;	// 0x331ef901
- (id)controlFactory;	// 0x331ef989
- (id)dataAtIndex:(long)index;	// 0x331ef9c5
- (long)dataCount;	// 0x331ef9a5
- (void)dealloc;	// 0x331ef83d
- (id)hashForDataAtIndex:(long)index;	// 0x331ef9e5
- (void)reloadAppliances;	// 0x331efa1d
@end

