/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSingleton.h"
#import "AppleTV-Structs.h"

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface BRFontCache : BRSingleton {
@private
	CGSize _displaySize;	// 4 = 0x4
	NSDictionary *_cache;	// 12 = 0xc
}
+ (void)setSingleton:(id)singleton;	// 0x332cad55
+ (id)singleton;	// 0x332cad45
- (id)init;	// 0x332cad65
- (CTFontRef)_createFontForAttributes:(id)attributes;	// 0x332cb061
- (id)addRealFontsToAttributedString:(id)attributedString;	// 0x332cae29
- (CTFontRef)createFontForRowHeight:(float)rowHeight fontName:(id)name;	// 0x332caf01
- (void)dealloc;	// 0x332caddd
- (void)setDisplaySize:(CGSize)size;	// 0x332caff5
@end

