/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKit.framework/EventKit
 */

#import "EventKit-Structs.h"
#import "EKCalendarDate.h"


__attribute__((visibility("hidden")))
@interface EKMutableCalendarDate : EKCalendarDate {
}
- (void)addDays:(int)days;	// 0x30e54fa1
- (void)addGregorianUnits:(XXStruct_mY3THC)units;	// 0x30e0af9d
- (id)copyWithZone:(NSZone *)zone;	// 0x30e54efd
@end

