/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import <NSObject.h> // Unknown library


__attribute__((visibility("hidden")))
@interface OAXStroke : NSObject {
}
+ (id)compoundLineEnumMap;	// 0x34d071b5
+ (id)lineCapEnumMap;	// 0x34d0715d
+ (id)lineEndLengthEnumMap;	// 0x34d444c5
+ (id)lineEndTypeEnumMap;	// 0x34d44415
+ (id)lineEndWidthEnumMap;	// 0x34d4446d
+ (id)penAlignmentEnumMap;	// 0x34d0720d
+ (id)presetDashEnumMap;	// 0x34d0730d
+ (id)readCustomDashFromXmlNode:(xmlNode *)xmlNode;	// 0x34e27e61
+ (void)readLineEnd:(id)end fromXmlNode:(xmlNode *)xmlNode;	// 0x34d12555
+ (id)readPresetDashFromXmlNode:(xmlNode *)xmlNode;	// 0x34d07265
+ (id)readStrokeFromXmlNode:(xmlNode *)xmlNode packagePart:(id)part drawingState:(id)state;	// 0x34d06d11
@end

