/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import "OADDrawable.h"

@class NSMutableArray;

@interface OADFlattenedGroup : OADDrawable {
	NSMutableArray *mDrawables;	// 24 = 0x18
}
- (id)init;	// 0x371495b1
- (void)addDrawable:(id)drawable;	// 0x3714967d
- (void)dealloc;	// 0x37149621
- (id)drawables;	// 0x3714966d
@end

