/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/DataAccess.framework/Frameworks/DAEAS.framework/DAEAS
 */

#import <NSObject.h> // Unknown library
#import "ASAccountActorMessages.h"


@interface ASAccountActorZombie : NSObject <ASAccountActorMessages> {
}
+ (id)sharedZombie;	// 0x31541aa5
- (oneway void)_accountPasswordChanged;	// 0x31541e4d
- (oneway void)_daemonDiedNotification:(id)notification;	// 0x31541e39
- (oneway void)_folderHierarchyChanged;	// 0x31541e45
- (oneway void)_folderUpdatedNotification:(id)notification;	// 0x31541e3d
- (oneway void)_foldersThatExternalClientsCareAboutChanged;	// 0x31541e49
- (oneway void)_newASPolicyKeyNotification:(id)notification;	// 0x31541e41
- (void)_sendFailureToConsumer:(id)consumer;	// 0x31541bcd
- (oneway void)cancelAllSearchQueries;	// 0x31541de9
- (oneway void)cancelSearchQuery:(id)query;	// 0x31541de5
- (oneway void)cancelTaskWithID:(int)anId;	// 0x31541d7d
- (id)deletedItemsFolder;	// 0x31541e59
- (id)encryptionIdentityPersistentReference;	// 0x31541ba5
- (id)folderIDsThatExternalClientsCareAboutForDataclasses:(int)dataclasses withTag:(id *)tag;	// 0x31541bc1
- (id)folderIDsThatExternalClientsCareAboutWithTag:(id *)tag;	// 0x31541bbd
- (BOOL)generatesBulletins;	// 0x31541b95
- (id)inboxFolder;	// 0x31541e51
- (BOOL)isHotmailAccount;	// 0x31541e5d
- (int)mailNumberOfPastDaysToSync;	// 0x31541b89
- (id)mailboxes;	// 0x31541b85
- (oneway void)monitorFoldersForUpdates:(id)updates;	// 0x31541bb1
- (int)performFetchAttachmentRequest:(id)request consumer:(id)consumer;	// 0x31541c8d
- (int)performFetchMessageSearchResultRequests:(id)requests consumer:(id)consumer;	// 0x31541ce1
- (void)performFolderChange:(id)change;	// 0x31541d19
- (int)performMailboxRequest:(id)request mailbox:(id)mailbox previousTag:(id)tag consumer:(id)consumer;	// 0x31541c39
- (int)performMailboxRequests:(id)requests mailbox:(id)mailbox previousTag:(id)tag consumer:(id)consumer;	// 0x31541c55
- (int)performMoveRequests:(id)requests consumer:(id)consumer;	// 0x31541c71
- (int)performResolveRecipientsRequest:(id)request consumer:(id)consumer;	// 0x31541cfd
- (oneway void)performSearchQuery:(id)query;	// 0x31541d81
- (BOOL)reattemptInvitationLinkageForMetaData:(id)metaData inFolderWithId:(id)anId;	// 0x31541bc9
- (BOOL)searchQueriesRunning;	// 0x31541ded
- (int)sendMessageWithRFC822Data:(id)rfc822Data messageID:(id)anId outgoingMessageType:(int)type originalMessageFolderID:(id)anId4 originalMessageItemID:(id)anId5 originalMessageLongID:(id)anId6 originalAccountID:(id)anId7 consumer:(id)consumer context:(void *)context;	// 0x31541c1d
- (id)sentItemsFolder;	// 0x31541e55
- (oneway void)setAccount:(id)account;	// 0x31541df5
- (oneway void)setEncryptionIdentityPersistentReference:(id)reference;	// 0x31541ba9
- (BOOL)setFolderIdsThatExternalClientsCareAboutAdded:(id)added deleted:(id)deleted foldersTag:(id)tag;	// 0x31541bc5
- (oneway void)setGeneratesBulletins:(BOOL)bulletins;	// 0x31541b99
- (oneway void)setMailNumberOfPastDaysToSync:(int)sync;	// 0x31541bad
- (oneway void)setSigningIdentityPersistentReference:(id)reference;	// 0x31541ba1
- (oneway void)shutdown;	// 0x31541df9
- (id)signingIdentityPersistentReference;	// 0x31541b9d
- (oneway void)startup;	// 0x31541df1
- (oneway void)stopMonitoringAllFolders;	// 0x31541bb9
- (oneway void)stopMonitoringFoldersForUpdates:(id)updates;	// 0x31541bb5
- (int)supportsEmailFlagging;	// 0x31541b91
- (int)supportsMailboxSearch;	// 0x31541b8d
@end

