/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/CoreThemeDefinition.framework/CoreThemeDefinition
 */

#import </libobjc.A.h>

@class CoreThemeDocument, NSThread;

@interface TDThreadMOCOrganizer : NSObject {
	NSThread *mainThread;	// 4 = 0x4
	CoreThemeDocument *document;	// 8 = 0x8
}
@property(readonly, retain) CoreThemeDocument *document;	// G=0x3073e50d; converted property
@property(readonly, retain) NSThread *mainThread;	// G=0x3073e471; converted property
@property(retain) id threadMOC;	// G=0x3073e545; S=0x3073e33d; converted property
- (id)init;	// 0x3073e669
- (id)initWithDocument:(id)document mainThread:(id)thread;	// 0x3073e6e5
// converted property getter: - (id)document;	// 0x3073e50d
- (id)mainMOC;	// 0x3073e51d
// converted property getter: - (id)mainThread;	// 0x3073e471
// converted property setter: - (void)setThreadMOC:(id)moc;	// 0x3073e33d
// converted property getter: - (id)threadMOC;	// 0x3073e545
@end

