/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
 */

#import <NSObject.h> // Unknown library

@class NSAttributedString, VSRecognitionSession, NSString;

@interface VSRecognitionAction : NSObject {
@private
	NSString *_resultString;	// 4 = 0x4
	NSString *_statusString;	// 8 = 0x8
	union {
		NSString *stringValue;
		NSAttributedString *attributedStringValue;
	} _spokenString;	// 12 = 0xc
	VSRecognitionSession *_session;	// 16 = 0x10
	unsigned _spokenStringIsAttributed : 1;	// 20 = 0x14
}
@property(retain) id resultDisplayString;	// G=0x348d68c1; S=0x348d6919; converted property
@property(retain) id spokenFeedbackAttributedString;	// G=0x348d68e1; S=0x348d6a6d; converted property
@property(retain) id spokenFeedbackString;	// G=0x348d69a9; S=0x348d69e5; converted property
@property(retain) id statusDisplayString;	// G=0x348d68d1; S=0x348d6961; converted property
- (void)_continueAfterDeferredStart;	// 0x348d6915
- (BOOL)_hasDeferredStartCallback;	// 0x348d6911
- (id)_session;	// 0x348d68a1
- (void)_setSession:(id)session;	// 0x348d68b1
- (id)cancel;	// 0x348d690d
- (void)completeWithNextAction:(id)nextAction error:(id)error;	// 0x348d6af5
- (int)completionType;	// 0x348d6909
- (void)dealloc;	// 0x348d6b49
- (id)perform;	// 0x348d6bbd
// converted property getter: - (id)resultDisplayString;	// 0x348d68c1
- (BOOL)sensitiveActionsEnabled;	// 0x348d6b25
// converted property setter: - (void)setResultDisplayString:(id)string;	// 0x348d6919
// converted property setter: - (void)setSpokenFeedbackAttributedString:(id)string;	// 0x348d6a6d
// converted property setter: - (void)setSpokenFeedbackString:(id)string;	// 0x348d69e5
// converted property setter: - (void)setStatusDisplayString:(id)string;	// 0x348d6961
// converted property getter: - (id)spokenFeedbackAttributedString;	// 0x348d68e1
// converted property getter: - (id)spokenFeedbackString;	// 0x348d69a9
// converted property getter: - (id)statusDisplayString;	// 0x348d68d1
@end

