/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

#import "QuartzCore-Structs.h"
#import "CAContext.h"


__attribute__((visibility("hidden")))
@interface CAContextImpl : CAContext {
@private
	Context *_impl;	// 4 = 0x4
}
@property(assign) CGColorSpaceRef colorSpace;	// G=0x32afbb09; S=0x32afbb1d; converted property
@property(retain) id layer;	// G=0x32a25ead; S=0x32a52e4d; converted property
@property(assign) float level;	// G=0x32afbb49; S=0x32a52ded; converted property
- (id)initRemoteWithOptions:(id)options;	// 0x32a527a9
- (id)initWithOptions:(id)options localContext:(bool)context;	// 0x32a527f5
// converted property getter: - (CGColorSpaceRef)colorSpace;	// 0x32afbb09
- (unsigned)contextId;	// 0x32a5323d
- (unsigned)createFencePort;	// 0x32afbb8d
- (unsigned)createSlot;	// 0x32afbc45
- (void)dealloc;	// 0x32a76069
- (void)deleteSlot:(unsigned)slot;	// 0x32afbc59
- (void)invalidate;	// 0x32afbaf5
// converted property getter: - (id)layer;	// 0x32a25ead
// converted property getter: - (float)level;	// 0x32afbb49
- (id)options;	// 0x32afbb5d
- (void)orderAbove:(unsigned)above;	// 0x32a53b99
- (void)orderBelow:(unsigned)below;	// 0x32afbb31
- (Context *)renderContext;	// 0x32afbc81
// converted property setter: - (void)setColorSpace:(CGColorSpaceRef)space;	// 0x32afbb1d
- (void)setFence:(unsigned)fence count:(unsigned)count;	// 0x32afbc19
- (void)setFencePort:(unsigned)port;	// 0x32afbbc5
- (void)setFencePort:(unsigned)port commitHandler:(id)handler;	// 0x32afbbed
// converted property setter: - (void)setLayer:(id)layer;	// 0x32a52e4d
// converted property setter: - (void)setLevel:(float)level;	// 0x32a52ded
- (void)setObject:(id)object forSlot:(unsigned)slot;	// 0x32afbc6d
- (BOOL)valid;	// 0x32afbb71
@end

