/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
 */

#import "Celestial-Structs.h"
#import <NSObject.h> // Unknown library

@class NSDictionary, AVItem;

@interface AVPlaybackItem : NSObject {
	id _delegate;	// 4 = 0x4
	AVItem *_avItem;	// 8 = 0x8
	OpaqueFigPlaybackItem *_fpItem;	// 12 = 0xc
	XXStruct_pwHToB _currentDuration;	// 16 = 0x10
	CGSize _currentSize;	// 40 = 0x28
	BOOL _currentSizeIsValid;	// 48 = 0x30
	BOOL _isPreparingForInspectionInitialSamples;	// 49 = 0x31
	BOOL _isPreparingForInspectionAccurateDuration;	// 50 = 0x32
	BOOL _isInPlayQueue;	// 51 = 0x33
	double _bookmarkTime;	// 52 = 0x34
	NSDictionary *_streamStateNotificationInfo;	// 60 = 0x3c
	NSDictionary *_lyricsNotificationInfo;	// 64 = 0x40
	NSDictionary *_inspectionNotificationInfo;	// 68 = 0x44
	NSDictionary *_playToEndNotificationInfo;	// 72 = 0x48
}
@property(readonly, retain) AVItem *avItem;	// G=0x3632239d; converted property
@property(readonly, assign) OpaqueFigPlaybackItem *fpItem;	// G=0x36322c85; converted property
@property(retain) NSDictionary *inspectionNotificationInfo;	// G=0x36323181; S=0x3632703d; @synthesize=_inspectionNotificationInfo
@property(assign) BOOL isInPlayQueue;	// G=0x36326b41; S=0x36326b29; @synthesize=_isInPlayQueue
@property(readonly, assign) BOOL isPreparingForInspection;	// G=0x363256d9; 
@property(assign) BOOL isPreparingForInspectionAccurateDuration;	// G=0x3633e579; S=0x3633e591; @synthesize=_isPreparingForInspectionAccurateDuration
@property(assign) BOOL isPreparingForInspectionInitialSamples;	// G=0x3633e549; S=0x3633e561; @synthesize=_isPreparingForInspectionInitialSamples
@property(retain) NSDictionary *lyricsNotificationInfo;	// G=0x36327725; S=0x36327029; @synthesize=_lyricsNotificationInfo
@property(retain) NSDictionary *playToEndNotificationInfo;	// G=0x363240c5; S=0x363285f1; @synthesize=_playToEndNotificationInfo
@property(retain) NSDictionary *streamStateNotificationInfo;	// G=0x36327739; S=0x3632774d; @synthesize=_streamStateNotificationInfo
+ (id)convertFigTimeDictionaryToTimeIntervalWithKey:(id)key stringURLToNSURLWithKey:(id)key2 inArrayOfDictionaries:(id)dictionaries;	// 0x3633dc8d
- (id)initWithDelegate:(id)delegate item:(id)item;	// 0x36321ad1
- (void)addFPListeners;	// 0x36324d3d
- (BOOL)addToPlayQueue:(OpaqueFigPlayer *)playQueue afterItem:(OpaqueFigPlaybackItem *)item;	// 0x3632698d
- (void)applyAttributesFromAVItemToFPItem:(id)fpitem;	// 0x36324fb9
- (void)applyBookmarkTime;	// 0x36325339
- (id)attributeForKey:(id)key;	// 0x3632712d
// converted property getter: - (id)avItem;	// 0x3632239d
- (void)cacheCurrentDuration;	// 0x363266ed
- (void)cacheCurrentSize;	// 0x36326689
- (void)dealloc;	// 0x3632832d
- (void)ensureFPItem;	// 0x363245d1
- (id)evenlySpacedThumbnailTimesFromStartTime:(double)startTime toEndTime:(double)endTime maxCount:(int)count;	// 0x3632e059
- (id)formatDetailsForTracks;	// 0x3633db5d
// converted property getter: - (OpaqueFigPlaybackItem *)fpItem;	// 0x36322c85
- (void)fpItemNotificationInfo:(id)info;	// 0x36325c79
- (void)fpItemNotificationName:(id)name userInfo:(id)info;	// 0x3633e1e9
- (id)fpNotificationNames;	// 0x36324e21
// declared property getter: - (id)inspectionNotificationInfo;	// 0x36323181
// declared property getter: - (BOOL)isInPlayQueue;	// 0x36326b41
// declared property getter: - (BOOL)isPreparingForInspection;	// 0x363256d9
// declared property getter: - (BOOL)isPreparingForInspectionAccurateDuration;	// 0x3633e579
// declared property getter: - (BOOL)isPreparingForInspectionInitialSamples;	// 0x3633e549
- (id)itemAttribute:(id)attribute forKey:(id)key;	// 0x363270c9
// declared property getter: - (id)lyricsNotificationInfo;	// 0x36327725
- (void)makeReadyForInspection;	// 0x36325555
- (id)nextThumbnailTimesStartingAt:(double)at minimumInterval:(double)interval forwards:(BOOL)forwards maxCount:(int)count;	// 0x3633e24d
// declared property getter: - (id)playToEndNotificationInfo;	// 0x363240c5
- (id)propertiesNeededForInspection;	// 0x36325719
- (void)release;	// 0x3633dab1
- (void)removeFPListeners;	// 0x36328515
- (void)removeFromPlayQueue:(OpaqueFigPlayer *)playQueue;	// 0x3632805d
- (void)setAttribute:(id)attribute forKey:(id)key;	// 0x3633de51
- (void)setBookmarkTime:(double)time;	// 0x36322495
// declared property setter: - (void)setInspectionNotificationInfo:(id)info;	// 0x3632703d
// declared property setter: - (void)setIsInPlayQueue:(BOOL)playQueue;	// 0x36326b29
// declared property setter: - (void)setIsPreparingForInspectionAccurateDuration:(BOOL)inspectionAccurateDuration;	// 0x3633e591
// declared property setter: - (void)setIsPreparingForInspectionInitialSamples:(BOOL)inspectionInitialSamples;	// 0x3633e561
- (void)setItemAttribute:(id)attribute value:(id)value forKey:(id)key error:(id *)error;	// 0x3633e185
// declared property setter: - (void)setLyricsNotificationInfo:(id)info;	// 0x36327029
// declared property setter: - (void)setPlayToEndNotificationInfo:(id)endNotificationInfo;	// 0x363285f1
// declared property setter: - (void)setStreamStateNotificationInfo:(id)info;	// 0x3632774d
- (void)stealControlOfAVItem;	// 0x36322c95
// declared property getter: - (id)streamStateNotificationInfo;	// 0x36327739
@end

