/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;
@protocol RUIYTDocumentLoaderDelegate;

__attribute__((visibility("hidden")))
@interface RUIYTDocumentLoader : XXUnknownSuperclass {
	NSMutableArray *_documentsBeingLoaded;	// 4 = 0x4
	id<RUIYTDocumentLoaderDelegate> _delegate;	// 8 = 0x8
}
@property(assign) __weak id<RUIYTDocumentLoaderDelegate> delegate;	// G=0x24ed39; S=0x24ed59; @synthesize=_delegate
- (id)init;	// 0x24e915
- (void).cxx_destruct;	// 0x24ed6d
- (void)_finalizeDocument:(id)document;	// 0x24ec89
- (void)cancelAllDocuments;	// 0x24eba1
- (void)cancelDocument:(id)document;	// 0x24eb3d
- (void)dealloc;	// 0x24e98d
// declared property getter: - (id)delegate;	// 0x24ed39
- (void)loadDocument:(id)document;	// 0x24ea21
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x24ed59
@end

