/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreImage.framework/CoreImage
 */

#import <NSObject.h> // Unknown library
#import "CoreImage-Structs.h"

@class NSString;

@interface CIFeature : NSObject {
}
@property(readonly, assign) CGRect bounds;	// G=0x30d57451; 
@property(readonly, assign) NSString *type;	// G=0x30d5744d; 
- (id)init;	// 0x30d573dd
// declared property getter: - (CGRect)bounds;	// 0x30d57451
// declared property getter: - (id)type;	// 0x30d5744d
@end

