/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/EventKit.framework/EventKit
 */

#import <NSObject.h> // Unknown library

@class EKEventStore, NSString;

@interface EKSource : NSObject {
@private
	EKEventStore *_store;	// 4 = 0x4
	NSString *_sourceId;	// 8 = 0x8
	void *_object;	// 12 = 0xc
	int _type;	// 16 = 0x10
	NSString *_title;	// 20 = 0x14
	NSString *_externalId;	// 24 = 0x18
	unsigned _loadFlags;	// 28 = 0x1c
}
@property(readonly, copy, nonatomic) NSString *externalId;	// G=0x32e4e089; 
@property(readonly, copy, nonatomic) NSString *sourceIdentifier;	// G=0x32e48fe9; 
@property(readonly, copy, nonatomic) NSString *title;	// G=0x32e8503d; 
@property(readonly, assign, nonatomic) int type;	// G=0x32e48e6d; 
- (id)initWithStore:(id)store object:(void *)object sourceIdentifier:(id)identifier;	// 0x32e48c01
- (void)_setStoreInternal:(id)internal;	// 0x32e48dd1
- (void)_storeClosed;	// 0x32e84e71
- (void)dealloc;	// 0x32e84e89
- (id)description;	// 0x32e84cdd
// declared property getter: - (id)externalId;	// 0x32e4e089
- (BOOL)isEqual:(id)equal;	// 0x32e84d8d
- (void)reconnectToServer;	// 0x32e84f35
- (void)refresh;	// 0x32e84e05
// declared property getter: - (id)sourceIdentifier;	// 0x32e48fe9
// declared property getter: - (id)title;	// 0x32e8503d
// declared property getter: - (int)type;	// 0x32e48e6d
@end

