/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ATVMediaOption.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface ATVSubtitleOption : XXUnknownSuperclass <ATVMediaOption> {
	NSString *_languageCodeISO;	// 4 = 0x4
	NSString *_languageCodeBCP47;	// 8 = 0x8
	NSString *_identifier;	// 12 = 0xc
	NSNumber *_trackIndex;	// 16 = 0x10
	NSString *_localizedDisplayString;	// 20 = 0x14
}
@property(readonly, retain) NSString *identifier;	// G=0x228cb1; converted property
@property(readonly, retain) NSString *languageCodeBCP47;	// G=0x228cc1; converted property
@property(retain) NSString *localizedDisplayString;	// G=0x228ce1; S=0x228df9; converted property
@property(readonly, retain) NSNumber *trackIndex;	// G=0x228cd1; converted property
+ (id)emptySubtitleOption;	// 0x2289e9
+ (id)subtitleOptionFromLanguageCodeISO:(id)languageCodeISO languageCodeBCP47:(id)a47 trackIndex:(id)index identifier:(id)identifier;	// 0x228a31
- (id)initWithLanguageCodeISO:(id)languageCodeISO languageCodeBCP47:(id)a47 trackIndex:(id)index identifier:(id)identifier;	// 0x228a7d
- (void)dealloc;	// 0x228b41
- (id)description;	// 0x228e35
// converted property getter: - (id)identifier;	// 0x228cb1
- (BOOL)isEqual:(id)equal;	// 0x228be1
- (id)languageCode;	// 0x228ca1
// converted property getter: - (id)languageCodeBCP47;	// 0x228cc1
// converted property getter: - (id)localizedDisplayString;	// 0x228ce1
- (id)localizedDisplayStringForIdentifier;	// 0x228d6d
- (void)saveToDiskForMediaAsset:(id)mediaAsset;	// 0x228c65
// converted property setter: - (void)setLocalizedDisplayString:(id)string;	// 0x228df9
// converted property getter: - (id)trackIndex;	// 0x228cd1
@end

