/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "BRSelectionHandler.h"


__attribute__((visibility("hidden")))
@interface BRMainMenuSelectionHandler : XXUnknownSuperclass <BRSelectionHandler> {
	id<BRSelectionHandler> _handler;	// 4 = 0x4
}
+ (id)handlerWithHandler:(id)handler;	// 0x360eb5
- (id)initWithHandler:(id)handler;	// 0x360ef1
- (void)dealloc;	// 0x360f45
- (BOOL)handlePlayForControl:(id)control;	// 0x360fb5
- (BOOL)handleSelectionForControl:(id)control;	// 0x360f91
@end

