/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BRStateMachine.h"
#import "AppleTV-Structs.h"

@class NSNumber, NSTimer, NSString, ATVDataItem;

__attribute__((visibility("hidden")))
@interface LTAVLeaseAgent : BRStateMachine {
	ATVDataItem *_item;	// 24 = 0x18
	unsigned long _FPMediaKind;	// 28 = 0x1c
	NSString *_storeMediaKind;	// 32 = 0x20
	NSString *_leaseID;	// 36 = 0x24
	int _numRenewalRetries;	// 40 = 0x28
	NSNumber *_sagaID;	// 44 = 0x2c
	BOOL _drmSyncComplete;	// 48 = 0x30
	FPLeaseSyncOpaque_Ref _lease;	// 52 = 0x34
	NSTimer *renewTimer;	// 56 = 0x38
	double _leaseDuration;	// 60 = 0x3c
}
@property(assign, nonatomic) double leaseDuration;	// G=0x744fd; S=0x74515; @synthesize=_leaseDuration
@property(assign, nonatomic) __weak NSTimer *renewTimer;	// G=0x744c9; S=0x744e9; @synthesize
+ (id)_generateRequestForOperation:(id)operation clientData:(id)data leaseID:(id)anId storeMediaKind:(id)kind;	// 0x74e3d
+ (void)initialize;	// 0x73c9d
+ (id)leaseAgentForMediaItem:(id)mediaItem player:(id)player;	// 0x73ccd
+ (void)stopAllLeases;	// 0x73d31
- (id)initWithMediaItem:(id)mediaItem player:(id)player;	// 0x73f59
- (void).cxx_destruct;	// 0x74529
- (void)_assetDidChange:(id)_asset;	// 0x74d05
- (void)_augmentSagaMediaItemWithDownloadResponse:(id)downloadResponse;	// 0x77091
- (void)_authenticationFailed:(id)failed;	// 0x7483d
- (void)_authenticationSucceeded:(id)succeeded;	// 0x74761
- (id)_decodeContent:(id)content;	// 0x74595
- (void)_delayedEventTimerFired:(id)fired;	// 0x776b1
- (void)_deviceWillSleep:(id)_device;	// 0x74dd5
- (void)_drmSyncCompleteWithError:(id)error wasCancelled:(BOOL)cancelled;	// 0x751c5
- (id)_dsidFromDownloadResponse:(id)downloadResponse;	// 0x774b9
- (id)_errorFromDictionary:(id)dictionary;	// 0x739c9
- (BOOL)_errorIsRecoverable:(int)recoverable;	// 0x77631
- (void)_initializeStateMachine:(id)machine;	// 0x75515
- (id)_initiateLease;	// 0x7722d
- (id)_invalidateAgentWithError:(id)error;	// 0x753c1
- (id)_invalidateAgentWithError:(id)error wasCancelled:(BOOL)cancelled;	// 0x753d5
- (void)_leaseAcquisitionLoaded:(id)loaded;	// 0x74919
- (id)_leaseID;	// 0x75395
- (void)_leaseRenewalLoaded:(id)loaded;	// 0x74aa1
- (void)_mediaDidNotResolve:(id)_media;	// 0x74db5
- (void)_mediaResolved:(id)resolved;	// 0x74d69
- (BOOL)_playerMediaIsLeasedItem:(id)item;	// 0x7547d
- (void)_playerWillStop:(id)_player;	// 0x74ca1
- (void)_postDelayedEvent:(id)event;	// 0x77651
- (void)_renewLease:(id)lease;	// 0x77021
- (void)_stopLease;	// 0x77495
- (void)dealloc;	// 0x74409
// declared property getter: - (double)leaseDuration;	// 0x744fd
// declared property getter: - (id)renewTimer;	// 0x744c9
// declared property setter: - (void)setLeaseDuration:(double)duration;	// 0x74515
// declared property setter: - (void)setRenewTimer:(id)timer;	// 0x744e9
- (void)startLease;	// 0x74489
- (void)stopLease;	// 0x744a9
@end

