/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

#import <NSObject.h> // Unknown library

@class MPMediaQueryCriteria;

@interface MPMediaLibraryEntityWriteStream : NSObject {
	id _entityArray;	// 4 = 0x4
	MPMediaQueryCriteria *_queryCriteria;	// 8 = 0x8
	unsigned _index;	// 12 = 0xc
	unsigned _count;	// 16 = 0x10
	BOOL _cancelled;	// 20 = 0x14
}
@property(readonly, assign, nonatomic, getter=isCancelled) BOOL cancelled;	// G=0x33744b9d; 
@property(readonly, assign, nonatomic) unsigned count;	// G=0x33744b7d; 
@property(readonly, assign, nonatomic) unsigned index;	// G=0x33744b8d; 
- (id)initWithEntityStreamArray:(id)entityStreamArray queryCriteria:(id)criteria count:(unsigned)count;	// 0x33744a2d
- (void)_writeCollectionWithIdentifier:(long long)identifier valuesForProperties:(id)properties itemsQueryCriteria:(id)criteria representativeItemIdentifier:(long long)identifier4;	// 0x33744e9d
- (void)cancel;	// 0x33744f45
// declared property getter: - (unsigned)count;	// 0x33744b7d
- (void)dealloc;	// 0x33744ac1
- (id)description;	// 0x33744b25
// declared property getter: - (unsigned)index;	// 0x33744b8d
// declared property getter: - (BOOL)isCancelled;	// 0x33744b9d
- (void)writeCollectionWithIdentifier:(long long)identifier valuesForProperties:(id)properties;	// 0x33744c1d
- (void)writeCollectionWithIdentifier:(long long)identifier valuesForProperties:(id)properties representativeItemIdentifier:(long long)identifier3;	// 0x33744c4d
- (void)writeItemWithIdentifier:(long long)identifier valuesForProperties:(id)properties;	// 0x33744bad
@end

