/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

#import </libobjc.A.h>

@class NSLock, NSHashTable;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface _GEOResourceManifestTileGroupObserverProxy : NSObject {
	NSHashTable *_observers;	// 4 = 0x4
	NSLock *_observersLock;	// 8 = 0x8
	NSObject<OS_dispatch_queue> *_queue;	// 12 = 0xc
}
@property(assign, nonatomic) NSObject<OS_dispatch_queue> *queue;	// G=0x30f28551; S=0x30f281dd; @synthesize=_queue
- (id)init;	// 0x30f28029
- (void)addObserver:(id)observer;	// 0x30f28215
- (void)dealloc;	// 0x30f28091
- (id)description;	// 0x30f28109
- (void)forEachObserver:(id)eachObserver finished:(id)finished;	// 0x30f2830d
- (unsigned)observersCount;	// 0x30f284f5
// declared property getter: - (id)queue;	// 0x30f28551
- (void)removeObserver:(id)observer;	// 0x30f282b1
// declared property setter: - (void)setQueue:(id)queue;	// 0x30f281dd
@end

