/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AppleTV-Structs.h"
#import "BRKeyboardControl.h"

@class BRListView, NSArray;

__attribute__((visibility("hidden")))
@interface BRKeyboardHistoryControl : BRKeyboardControl {
	NSArray *_textEntryHistoryClients;	// 96 = 0x60
	NSArray *_textEntryHistoryBehaviors;	// 100 = 0x64
	BRListView *_list;	// 104 = 0x68
	CGSize _preferredSize;	// 108 = 0x6c
	float _listOriginXOffset;	// 116 = 0x74
	float _listWidth;	// 120 = 0x78
}
@property(retain) id focusedKeyControl;	// G=0x2fd1fd; S=0x2fd201; converted property
- (id)initWithPreferredSize:(CGSize)preferredSize;	// 0x2fcf89
- (void)dealloc;	// 0x2fcfd5
- (BOOL)focusIsAtRightEdge;	// 0x2fd1f9
// converted property getter: - (id)focusedKeyControl;	// 0x2fd1fd
- (BOOL)keyboardFocusIsAtEdge:(int)edge;	// 0x2fd209
- (void)layoutSubcontrols;	// 0x2fd04d
- (void)setFocusToGlyphNamed:(id)glyphNamed;	// 0x2fd205
// converted property setter: - (void)setFocusedKeyControl:(id)control;	// 0x2fd201
- (void)setListOriginXOffset:(float)offset listWidth:(float)width;	// 0x2fd1c9
- (void)setTextEntryHistoryClients:(id)clients textEntryBehaviors:(id)behaviors list:(id)list;	// 0x2fd135
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x2fd11d
@end

