/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AppleTV-Structs.h"
#import "BRSingleton.h"
#import "NSNetServiceBrowserDelegate.h"
#import "NSNetServiceDelegate.h"

@class NSMutableSet, NSMutableArray, NSMutableDictionary;
@protocol MEITunesPlayerMessageHandler;

__attribute__((visibility("hidden")))
@interface MEITunesContext : BRSingleton <NSNetServiceBrowserDelegate, NSNetServiceDelegate> {
	AppContext *_iTunesContext;	// 4 = 0x4
	id<MEITunesPlayerMessageHandler> _playerHandler;	// 8 = 0x8
	NSMutableDictionary *_drmSyncInfo;	// 12 = 0xc
	BOOL _inRetailMode;	// 16 = 0x10
	NSMutableArray *_drmAccountQueries;	// 20 = 0x14
	NSMutableArray *_drmTokenQueries;	// 24 = 0x18
	NSMutableArray *_drmStoreKeysQueries;	// 28 = 0x1c
	NSMutableArray *_rentalQueries;	// 32 = 0x20
	NSMutableSet *_importedKeybagUserDSIDs;	// 36 = 0x24
}
@property(retain) id playerMessageHandler;	// G=0x654d; S=0x653d; converted property
+ (AppContext *)iTunesContext;	// 0x5529
+ (void)initialize;	// 0x54a1
+ (void)setSingleton:(id)singleton;	// 0x5509
+ (id)singleton;	// 0x5519
- (id)init;	// 0x5551
- (void)_addStoreKeysRequest:(ATVStoreRequestRef)request userID:(id)anId dataServerID:(id)anId3;	// 0x881d
- (void)_checkoutHomeShareRentalDelayed:(id)delayed;	// 0x73bd
- (void)_checkoutHomeShareRentalOnITunes:(id)tunes;	// 0x7501
- (void)_cleanupContext;	// 0x8c91
- (void)_dataClientDRMDataUpdated:(id)updated;	// 0x781d
- (void)_dataClientStatusChanged:(id)changed;	// 0x778d
- (void)_decrementDRMSyncCount:(id)count;	// 0x71c1
- (void)_drmAccountQueryHandler:(id)handler;	// 0x789d
- (void)_drmTokenQueryHandler:(id)handler;	// 0x7f6d
- (void)_homeShareAccountChanged:(id)changed;	// 0x773d
- (void)_incrementDRMSyncCount:(id)count;	// 0x70e5
- (void)_initiateCheckForPurchases:(id)purchases;	// 0x6fbd
- (void)_initiateRentalCount:(id)count;	// 0x6fd1
- (void)_mediaCued:(id)cued;	// 0x6ff9
- (void)_photoDBQueryHandler:(id)handler;	// 0x86ed
- (void)_photoDBRequested:(id)requested;	// 0x838d
- (void)_postDRMCompleteDelayed;	// 0x76a5
- (void)_removeStoreKeysRequestForUser:(id)user dataServerID:(id)anId;	// 0x88b9
- (void)_rentalCheckinQueryHandler:(id)handler;	// 0x81dd
- (void)_rentalCheckoutQueryHandler:(id)handler;	// 0x8345
- (id)_serverFromAsset:(id)asset;	// 0x8b49
- (void)_setStoreFront:(id)front;	// 0x6f65
- (void)_stateMachineStateChanged:(id)changed;	// 0x8bf5
- (BOOL)attemptAuthorizationForAsset:(id)asset error:(id *)error;	// 0x67f1
- (AppContext *)context;	// 0x5c39
- (void)dealloc;	// 0x5b45
- (void)deauthorizeAssetIfNecessary:(id)necessary;	// 0x6df1
- (void)deleteImportedKeybagData;	// 0x66fd
- (BOOL)drmSyncInProgressForServer:(id)server;	// 0x62ed
- (void)forceCheckInForJournalObject:(id)journalObject asset:(id)asset;	// 0x655d
- (void)importKeybagData:(id)data forDSID:(id)dsid;	// 0x66b1
// converted property getter: - (id)playerMessageHandler;	// 0x654d
// converted property setter: - (void)setPlayerMessageHandler:(id)handler;	// 0x653d
- (void)startDRMSyncForServer:(id)server;	// 0x5c49
@end

