/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SettingsUtilities : XXUnknownSuperclass {
}
+ (id)_IPConfigStringForInterface:(int)interface config:(id)config;	// 0x8b689
+ (id)activePortForConfig:(id)config;	// 0x8b495
+ (int)activePortValueForConfig:(id)config;	// 0x8b641
+ (id)localizedStringForKey:(id)key;	// 0x8b179
+ (id)networkNameForConfig:(id)config;	// 0x8b59d
+ (id)networkStringForType:(int)type config:(id)config;	// 0x8b18d
+ (id)networkTextureForType:(int)type config:(id)config;	// 0x8b3f9
+ (id)signalStrengthForConfig:(id)config;	// 0x8b531
+ (BOOL)truncateValueIfTooLong:(int)aLong;	// 0x8b485
+ (id)wiredIPConfigStringForConfig:(id)config;	// 0x8b575
+ (id)wirelessIPConfigStringForConfig:(id)config;	// 0x8b589
@end

