/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BRViewController.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface SettingsAVLanguageController : BRViewController {
	int _type;	// 104 = 0x68
	NSArray *_menuItemKeys;	// 108 = 0x6c
}
+ (id)audioLanguageController;	// 0xa77ad
+ (id)subtitleLanguageController;	// 0xa77f5
- (id)initWithType:(int)type;	// 0xa783d
- (void).cxx_destruct;	// 0xa7de1
- (void)list:(id)list didSelectItemAtIndexPath:(id)indexPath;	// 0xa7ce1
- (id)list:(id)list menuItemForRowAtIndexPath:(id)indexPath;	// 0xa7b25
- (long)list:(id)list numberOfRowsInSection:(long)section;	// 0xa7cc1
@end

