/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import "OfficeImport-Structs.h"
#import <NSObject.h> // Unknown library


__attribute__((visibility("hidden")))
@interface PXLegacyText : NSObject {
}
+ (void)readLegacyTextFromData:(id)data toShape:(id)shape state:(id)state;	// 0x3294ef91
+ (void)readLegacyTextGlobalsFromData:(id)data state:(id)state;	// 0x3294ee79
+ (PptTextMasterStyleAtom *)textMasterStyleOfType:(int)type state:(id)state;	// 0x3294e9b5
@end

