/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebKit.framework/WebKit
 */

#import "WebPolicyDecisionListener.h"
#import "WebFormSubmissionListener.h"
#import <NSObject.h> // Unknown library
#import "WebKit-Structs.h"


__attribute__((visibility("hidden")))
@interface WebFramePolicyListener : NSObject <WebPolicyDecisionListener, WebFormSubmissionListener> {
@private
	Frame *m_frame;	// 4 = 0x4
}
+ (void)initialize;	// 0x302afd91
- (id)initWithWebCoreFrame:(Frame *)webCoreFrame;	// 0x302afd95
- (void)continue;	// 0x302f48d1
- (void)dealloc;	// 0x302b246d
- (void)download;	// 0x302f48bd
- (void)finalize;	// 0x302f4921
- (void)ignore;	// 0x302f48a9
- (void)invalidate;	// 0x302f48e5
- (void)receivedPolicyDecision:(int)decision;	// 0x302afed9
- (void)use;	// 0x302afec5
@end

