/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
 */

#import <NSObject.h> // Unknown library


@interface CPDistributedMessagingDelayedReplyContext : NSObject {
	unsigned _replyPort;	// 4 = 0x4
	BOOL _portPassing;	// 8 = 0x8
}
@property(assign, nonatomic) BOOL portPassing;	// G=0x3103c169; S=0x3103c179; @synthesize=_portPassing
@property(assign, nonatomic) unsigned replyPort;	// G=0x3103c189; S=0x3103c199; @synthesize=_replyPort
- (id)initWithReplyPort:(unsigned)replyPort portPassing:(BOOL)passing;	// 0x3103c1c9
- (void)dealloc;	// 0x3103c219
// declared property getter: - (BOOL)portPassing;	// 0x3103c169
// declared property getter: - (unsigned)replyPort;	// 0x3103c189
// declared property setter: - (void)setPortPassing:(BOOL)passing;	// 0x3103c179
// declared property setter: - (void)setReplyPort:(unsigned)port;	// 0x3103c199
@end

