/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ATVSlideshow.framework/ATVSlideshow
 */

#import "MEPluginTypeGeneric.h"
#import "MEPluginRegistration.h"
#import "MEPlugin.h"
#import "ATVSlideshow-Structs.h"

@class NSOperationQueue, NSLock;

@interface MEPluginHTML5 : MEPlugin <MEPluginRegistration, MEPluginTypeGeneric> {
	NSLock *mXMLLock;	// 12 = 0xc
	NSOperationQueue *mImageQueue;	// 16 = 0x10
}
+ (BOOL)matchesOptions:(id)options;	// 0x3659a405
+ (void)registerPluginsToLoader:(id)loader;	// 0x3659a389
- (id)initWithIdentifier:(id)identifier andDocument:(id)document andDelegate:(id)delegate;	// 0x3659a409
- (id)_addTextLocationInfoWithEffectID:(id)effectID presetID:(id)anId size:(CGSize)size textDict:(id)dict textASPFactor:(float)factor;	// 0x3659d995
- (id)_addWordsLocationInfoWithEffectID:(id)effectID size:(CGSize)size textDict:(id)dict;	// 0x3659cca1
- (id)_wordsLocationFromString:(id)string;	// 0x3659e061
- (void)cacheImageAtPath:(id)path toPath:(id)path2 withAssetInfo:(id)assetInfo referenceOriginal:(BOOL)original createCache:(BOOL)cache alsoCreateBlackWhite:(BOOL)white;	// 0x3659c585
- (void)dealloc;	// 0x3659a50d
- (BOOL)exportToFile:(id)file andOptions:(id)options error:(id *)error;	// 0x3659a571
@end

