/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ATVSlideshow.framework/ATVSlideshow
 */

#import <NSDictionary.h> // Unknown library


@interface NSDictionary (MRUtilities)
- (int)sortPatchworkAscendingHorizontal:(id)horizontal;	// 0x36500a99
- (int)sortPatchworkAscendingVertical:(id)vertical;	// 0x36500959
- (int)sortPatchworkDescendingHorizontal:(id)horizontal;	// 0x36500b39
- (int)sortPatchworkDescendingVertical:(id)vertical;	// 0x365009f9
@end

