/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

#import "AVAssetWriterInputHelper.h"
#import "AVFoundation-Structs.h"

@class AVFigAssetWriterTrack, AVAssetWriterInputMediaDataRequester;

@interface AVAssetWriterInputWritingHelper : AVAssetWriterInputHelper {
	AVFigAssetWriterTrack *_assetWriterTrack;	// 12 = 0xc
	AVAssetWriterInputMediaDataRequester *_mediaDataRequester;	// 16 = 0x10
	CVPixelBufferPoolRef _pixelBufferPool;	// 20 = 0x14
}
@property(readonly, assign, nonatomic, getter=_assetWriterTrack) AVFigAssetWriterTrack *assetWriterTrack;	// G=0x341fa185; @synthesize=_assetWriterTrack
@property(readonly, assign) CVPixelBufferPoolRef pixelBufferPool;	// G=0x341fa05d; converted property
+ (id)keyPathsForValuesAffectingReadyForMoreMediaData;	// 0x341f9b19
- (id)initWithConfigurationState:(id)configurationState;	// 0x341f9691
- (id)initWithConfigurationState:(id)configurationState assetWriterTrack:(id)track error:(id *)error;	// 0x341f96b1
// declared property getter: - (id)_assetWriterTrack;	// 0x341fa185
- (BOOL)appendPixelBuffer:(CVBufferRef)buffer withPresentationTime:(XXStruct_pwHToB)presentationTime;	// 0x341f9da1
- (BOOL)appendSampleBuffer:(opaqueCMSampleBuffer *)buffer;	// 0x341f9ccd
- (void)dealloc;	// 0x341f9a61
- (void)finalize;	// 0x341f9ad5
- (BOOL)isReadyForMoreMediaData;	// 0x341f9b41
- (void)markAsFinished;	// 0x341f9ef1
// converted property getter: - (CVPixelBufferPoolRef)pixelBufferPool;	// 0x341fa05d
- (void)prepareToEndSession;	// 0x341f9e9d
- (BOOL)prepareToFinishWritingReturningError:(id *)finishWritingReturningError;	// 0x341f9ec5
- (void)requestMediaDataWhenReadyOnQueue:(id)queue usingBlock:(id)block;	// 0x341f9b75
- (int)status;	// 0x341f9b15
- (int)trackID;	// 0x341f9f51
- (void)transitionToTerminalStatus:(int)terminalStatus;	// 0x341f9f79
@end

