/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import <NSObject.h> // Unknown library

@class UIDelayedAction;

@interface UIKeyboardPreferencesController : NSObject {
	UIDelayedAction *m_synchronizePreferencesAction;	// 4 = 0x4
	BOOL dontSynchronizePreferences;	// 8 = 0x8
}
@property(assign, nonatomic) BOOL dontSynchronizePreferences;	// G=0x3103f529; S=0x3103f539; @synthesize
@property(readonly, assign) BOOL isInternalInstall;	// G=0x3103e999; 
+ (void)handleSpecificHardwareKeyboard;	// 0x3103f099
+ (void)preferencesChangedCallback:(id)callback;	// 0x3103e631
+ (id)sharedPreferencesController;	// 0x30c38469
- (id)init;	// 0x30c7ec69
- (BOOL)boolForKey:(int)key;	// 0x30c3849d
- (void)clearSynchronizePreferencesTimer;	// 0x3103e9f5
- (BOOL)costlyCapture;	// 0x3103ef0d
- (void)dealloc;	// 0x3103e84d
- (id)defaultForKey:(int)key;	// 0x30c7ed99
- (XXStruct_7wOxJB *)domainForType:(int)type;	// 0x30c385d9
- (XXStruct_7wOxJB *)domains;	// 0x30c38645
// declared property getter: - (BOOL)dontSynchronizePreferences;	// 0x3103f529
// declared property getter: - (BOOL)isInternalInstall;	// 0x3103e999
- (XXStruct_N0zFsC *)preferences;	// 0x30c385c9
- (void)releaseDontSynchronizePreferences;	// 0x3103ea35
- (float)rivenSizeFactor:(float)factor;	// 0x3103ef41
- (void)saveInputModes:(id)modes;	// 0x3103ec49
// declared property setter: - (void)setDontSynchronizePreferences:(BOOL)preferences;	// 0x3103f539
- (void)setInputModeLastUsed:(id)used;	// 0x3103ed45
- (void)setValue:(id)value forKey:(int)key;	// 0x3103ebb1
- (BOOL)spaceConfirmationEnabled;	// 0x3103f051
- (void)synchronizePreferences;	// 0x3103ea49
- (void)touchSynchronizePreferencesTimer;	// 0x3103eb31
- (BOOL)typologyEnabled;	// 0x3103eed9
- (id)valueForKey:(int)key;	// 0x30c384c5
@end

