/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

#import "StoreServices-Structs.h"
#import <NSObject.h> // Unknown library
#import "SSXPCCoding.h"
#import "NSCopying.h"

@class NSURL, NSMutableDictionary, NSString;

@interface SSItemArtworkImage : NSObject <SSXPCCoding, NSCopying> {
	NSMutableDictionary *_dictionary;	// 4 = 0x4
	NSString *_imageKind;	// 8 = 0x8
}
@property(retain, nonatomic) NSURL *URL;	// G=0x358635ad; S=0x358639b1; 
@property(readonly, assign, nonatomic) NSString *URLString;	// G=0x358639fd; 
@property(readonly, assign, nonatomic) int height;	// G=0x358632c9; 
@property(copy, nonatomic) NSString *imageKind;	// G=0x35863bd1; S=0x35863be5; @synthesize=_imageKind
@property(readonly, assign, nonatomic) int imageOrientation;	// G=0x35863371; 
@property(readonly, assign, nonatomic) float imageScale;	// G=0x35863431; 
@property(readonly, assign, nonatomic) CGSize imageSize;	// G=0x3586389d; 
@property(readonly, assign, nonatomic, getter=isPrerendered) BOOL prerendered;	// G=0x35863499; 
@property(readonly, assign, nonatomic) int width;	// G=0x35863505; 
- (id)initWithArtworkDictionary:(id)artworkDictionary;	// 0x35863849
- (id)initWithXPCEncoding:(id)xpcencoding;	// 0x35863aa9
// declared property getter: - (id)URL;	// 0x358635ad
// declared property getter: - (id)URLString;	// 0x358639fd
- (void)_setValue:(id)value forKey:(id)key;	// 0x35863a19
- (id)copyWithZone:(NSZone *)zone;	// 0x35863249
- (id)copyXPCEncoding;	// 0x35863b7d
- (void)dealloc;	// 0x358631e5
- (id)description;	// 0x35863681
- (unsigned)hash;	// 0x35863771
// declared property getter: - (int)height;	// 0x358632c9
// declared property getter: - (id)imageKind;	// 0x35863bd1
// declared property getter: - (int)imageOrientation;	// 0x35863371
// declared property getter: - (float)imageScale;	// 0x35863431
// declared property getter: - (CGSize)imageSize;	// 0x3586389d
- (BOOL)isEqual:(id)equal;	// 0x358637b1
// declared property getter: - (BOOL)isPrerendered;	// 0x35863499
// declared property setter: - (void)setImageKind:(id)kind;	// 0x35863be5
- (void)setImageKindWithTypeName:(id)typeName variantName:(id)name;	// 0x358638e9
// declared property setter: - (void)setURL:(id)url;	// 0x358639b1
- (void)setValue:(id)value forProperty:(id)property;	// 0x358639ed
- (id)valueForProperty:(id)property;	// 0x35863639
// declared property getter: - (int)width;	// 0x35863505
@end

