/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIPopoverBackgroundView.h"
#import "UIKit-Structs.h"


__attribute__((visibility("hidden")))
@interface _UIViewServiceDummyPopoverBackgroundView : UIPopoverBackgroundView {
	float arrowOffset;	// 52 = 0x34
	unsigned arrowDirection;	// 56 = 0x38
}
@property(assign) unsigned arrowDirection;	// G=0x2f89885d; S=0x2f89886d; converted property
@property(assign) float arrowOffset;	// G=0x2f89883d; S=0x2f89884d; converted property
+ (float)arrowBase;	// 0x2f8987fd
+ (float)arrowHeight;	// 0x2f8987f9
+ (UIEdgeInsets)contentViewInsets;	// 0x2f898801
+ (BOOL)wantsDefaultContentAppearance;	// 0x2f898819
- (CGSize)_shadowOffset;	// 0x2f898825
- (float)_shadowOpacity;	// 0x2f89881d
- (float)_shadowRadius;	// 0x2f898821
// converted property getter: - (unsigned)arrowDirection;	// 0x2f89885d
// converted property getter: - (float)arrowOffset;	// 0x2f89883d
// converted property setter: - (void)setArrowDirection:(unsigned)direction;	// 0x2f89886d
// converted property setter: - (void)setArrowOffset:(float)offset;	// 0x2f89884d
@end

