/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UITableViewCell.h"

@class UIActivityIndicatorView;

__attribute__((visibility("hidden")))
@interface UIPrintStatusJobTableViewCell : UITableViewCell {
	UIActivityIndicatorView *_activityIndicator;	// 360 = 0x168
}
@property(assign, nonatomic) BOOL showActive;	// G=0x2f7f67b1; S=0x2f7f67d5; 
- (id)initWithReuseIdentifier:(id)reuseIdentifier;	// 0x2f7f6615
- (void)dealloc;	// 0x2f7f6765
- (void)layoutSubviews;	// 0x2f7f689d
// declared property setter: - (void)setShowActive:(BOOL)active;	// 0x2f7f67d5
// declared property getter: - (BOOL)showActive;	// 0x2f7f67b1
@end

