/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import <ImageIO/NSObject.h>

@class NSIndexPath, UIView;

__attribute__((visibility("hidden")))
@interface UIViewAnimation : NSObject {
	UIView *_view;	// 4 = 0x4
	NSIndexPath *_indexPath;	// 8 = 0x8
	CGRect _endRect;	// 12 = 0xc
	float _endAlpha;	// 28 = 0x1c
	float _startFraction;	// 32 = 0x20
	float _endFraction;	// 36 = 0x24
	int _curve;	// 40 = 0x28
	BOOL _animateFromCurrentPosition;	// 44 = 0x2c
	BOOL _shouldDeleteAfterAnimation;	// 45 = 0x2d
	BOOL _editing;	// 46 = 0x2e
	BOOL _shouldAnimateShadow;	// 47 = 0x2f
	BOOL _shouldResetGroupOpacityAfterAnimation;	// 48 = 0x30
	BOOL _shouldAllowGroupOpacityAfterAnimation;	// 49 = 0x31
	BOOL _shouldClipToBoundsAfterAnimation;	// 50 = 0x32
}
@property(readonly, assign, nonatomic) BOOL animateFromCurrentPosition;	// G=0x2f465531; @synthesize=_animateFromCurrentPosition
@property(readonly, assign, nonatomic) int curve;	// G=0x2f465555; @synthesize=_curve
@property(readonly, assign, nonatomic) BOOL editing;	// G=0x2f4655ad; @synthesize=_editing
@property(readonly, assign, nonatomic) float endAlpha;	// G=0x2f465565; @synthesize=_endAlpha
@property(readonly, assign, nonatomic) float endFraction;	// G=0x2f4654a5; @synthesize=_endFraction
@property(readonly, assign, nonatomic) CGRect endRect;	// G=0x2f465585; @synthesize=_endRect
@property(readonly, assign, nonatomic) NSIndexPath *indexPath;	// G=0x2f46559d; @synthesize=_indexPath
@property(assign, nonatomic) BOOL shouldAllowGroupOpacityAfterAnimation;	// G=0x2f6eebcd; S=0x2f6eebdd; @synthesize=_shouldAllowGroupOpacityAfterAnimation
@property(assign, nonatomic) BOOL shouldAnimateShadow;	// G=0x2f465575; S=0x2f465301; @synthesize=_shouldAnimateShadow
@property(assign, nonatomic) BOOL shouldClipToBoundsAfterAnimation;	// G=0x2f6eebed; S=0x2f6eebfd; @synthesize=_shouldClipToBoundsAfterAnimation
@property(readonly, assign, nonatomic) BOOL shouldDeleteAfterAnimation;	// G=0x2f4655f1; @synthesize=_shouldDeleteAfterAnimation
@property(assign, nonatomic) BOOL shouldResetGroupOpacityAfterAnimation;	// G=0x2f6eebad; S=0x2f6eebbd; @synthesize=_shouldResetGroupOpacityAfterAnimation
@property(readonly, assign, nonatomic) float startFraction;	// G=0x2f465495; @synthesize=_startFraction
@property(readonly, assign, nonatomic) UIView *view;	// G=0x2f465485; @synthesize=_view
- (id)initWithView:(id)view indexPath:(id)path endRect:(CGRect)rect endAlpha:(float)alpha startFraction:(float)fraction endFraction:(float)fraction6 curve:(int)curve animateFromCurrentPosition:(BOOL)currentPosition shouldDeleteAfterAnimation:(BOOL)animation editing:(BOOL)editing;	// 0x2f41621d
// declared property getter: - (BOOL)animateFromCurrentPosition;	// 0x2f465531
// declared property getter: - (int)curve;	// 0x2f465555
- (void)dealloc;	// 0x2f4658e1
- (id)description;	// 0x2f6eea4d
// declared property getter: - (BOOL)editing;	// 0x2f4655ad
// declared property getter: - (float)endAlpha;	// 0x2f465565
// declared property getter: - (float)endFraction;	// 0x2f4654a5
// declared property getter: - (CGRect)endRect;	// 0x2f465585
// declared property getter: - (id)indexPath;	// 0x2f46559d
// declared property setter: - (void)setShouldAllowGroupOpacityAfterAnimation:(BOOL)allowGroupOpacityAfterAnimation;	// 0x2f6eebdd
// declared property setter: - (void)setShouldAnimateShadow:(BOOL)animateShadow;	// 0x2f465301
// declared property setter: - (void)setShouldClipToBoundsAfterAnimation:(BOOL)clipToBoundsAfterAnimation;	// 0x2f6eebfd
// declared property setter: - (void)setShouldResetGroupOpacityAfterAnimation:(BOOL)resetGroupOpacityAfterAnimation;	// 0x2f6eebbd
// declared property getter: - (BOOL)shouldAllowGroupOpacityAfterAnimation;	// 0x2f6eebcd
// declared property getter: - (BOOL)shouldAnimateShadow;	// 0x2f465575
// declared property getter: - (BOOL)shouldClipToBoundsAfterAnimation;	// 0x2f6eebed
// declared property getter: - (BOOL)shouldDeleteAfterAnimation;	// 0x2f4655f1
// declared property getter: - (BOOL)shouldResetGroupOpacityAfterAnimation;	// 0x2f6eebad
// declared property getter: - (float)startFraction;	// 0x2f465495
// declared property getter: - (id)view;	// 0x2f465485
@end

