/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/CoreData.framework/CoreData
 */

#import <NSObject.h> // Unknown library

@class NSDictionary, NSMutableDictionary;

@interface NSBinaryObjectStoreFile : NSObject {
	int _databaseVersion;	// 4 = 0x4
	NSDictionary *_fullMetadata;	// 8 = 0x8
	unsigned long long _primaryKeyGeneration;	// 12 = 0xc
	NSMutableDictionary *_mapData;	// 20 = 0x14
	NSDictionary *_storeOptions;	// 24 = 0x18
}
@property(assign) int databaseVersion;	// G=0x334c3429; S=0x334c3439; converted property
@property(retain) NSDictionary *fullMetadata;	// G=0x334c3449; S=0x334c3459; converted property
@property(retain) NSMutableDictionary *mapData;	// G=0x334c34c9; S=0x334c34d9; converted property
@property(assign) unsigned long long primaryKeyGeneration;	// G=0x334c349d; S=0x334c34b5; converted property
- (BOOL)_writeMetadataData:(id)data andMapDataData:(id)data2 toFile:(id)file error:(id *)error;	// 0x334c4df1
- (void)clearCurrentValues;	// 0x334c351d
// converted property getter: - (int)databaseVersion;	// 0x334c3429
- (void)dealloc;	// 0x334c3399
// converted property getter: - (id)fullMetadata;	// 0x334c3449
// converted property getter: - (id)mapData;	// 0x334c34c9
// converted property getter: - (unsigned long long)primaryKeyGeneration;	// 0x334c349d
- (BOOL)readBinaryStoreFromData:(id)data originalPath:(id)path error:(id *)error;	// 0x334c3579
- (BOOL)readFromFile:(id)file error:(id *)error;	// 0x334c3bd1
- (BOOL)readMetadataFromFile:(id)file error:(id *)error;	// 0x334c4505
// converted property setter: - (void)setDatabaseVersion:(int)version;	// 0x334c3439
// converted property setter: - (void)setFullMetadata:(id)metadata;	// 0x334c3459
// converted property setter: - (void)setMapData:(id)data;	// 0x334c34d9
// converted property setter: - (void)setPrimaryKeyGeneration:(unsigned long long)generation;	// 0x334c34b5
- (BOOL)writeMetadataToFile:(id)file error:(id *)error;	// 0x334c3dd1
- (BOOL)writeToFile:(id)file error:(id *)error;	// 0x334c5311
@end

