/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIKit-Structs.h"
#import "UIControl.h"

@class UITableCell;

__attribute__((visibility("hidden")))
@interface _UITableCellGrabber : UIControl {
@private
	UITableCell *_cell;	// 72 = 0x48
	CGPoint _downPoint;	// 76 = 0x4c
}
- (id)initWithCell:(id)cell;	// 0x301f25ad
- (void)_controlMouseDown:(GSEventRef)down;	// 0x301f2971
- (void)_controlMouseDragged:(GSEventRef)dragged;	// 0x301f2979
- (void)_controlMouseUp:(GSEventRef)up;	// 0x301f2975
- (BOOL)beginTrackingAt:(CGPoint)at withEvent:(GSEventRef)event;	// 0x301f273d
- (BOOL)beginTrackingWithTouch:(id)touch withEvent:(id)event;	// 0x301f2825
- (BOOL)cancelMouseTracking;	// 0x301f297d
- (BOOL)cancelTouchTracking;	// 0x301f29cd
- (void)cancelTrackingWithEvent:(id)event;	// 0x301f295d
- (BOOL)continueTrackingAt:(CGPoint)at previous:(CGPoint)previous withEvent:(GSEventRef)event;	// 0x301f2799
- (BOOL)continueTrackingWithTouch:(id)touch withEvent:(id)event;	// 0x301f2895
- (void)drawRect:(CGRect)rect;	// 0x301f26a5
- (void)endTrackingAt:(CGPoint)at previous:(CGPoint)previous withEvent:(GSEventRef)event;	// 0x301f27e9
- (void)endTrackingWithTouch:(id)touch withEvent:(id)event;	// 0x301f2921
- (BOOL)shouldTrack;	// 0x301f2739
@end

