/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import "DOMHTMLElement.h"

@class NSString, DOMNodeList, DOMHTMLFormElement, DOMValidityState;

@interface DOMHTMLKeygenElement : DOMHTMLElement {
}
@property(assign) BOOL autofocus;	// G=0x35fee6d9; S=0x35fee7e5; 
@property(copy) NSString *challenge;	// G=0x35fee8f9; S=0x35feea1d; 
@property(assign) BOOL disabled;	// G=0x35feebd1; S=0x35feecdd; 
@property(readonly, assign) DOMHTMLFormElement *form;	// G=0x35feedf1; 
@property(copy) NSString *keytype;	// G=0x35feeef5; S=0x35fef019; 
@property(readonly, assign) DOMNodeList *labels;	// G=0x35fef979; 
@property(copy) NSString *name;	// G=0x35fef1cd; S=0x35fef2e9; 
@property(readonly, assign) NSString *type;	// G=0x35fef491; 
@property(readonly, assign) NSString *validationMessage;	// G=0x35fef7bd; 
@property(readonly, assign) DOMValidityState *validity;	// G=0x35fef6b1; 
@property(readonly, assign) BOOL willValidate;	// G=0x35fef5ad; 
// declared property getter: - (BOOL)autofocus;	// 0x35fee6d9
// declared property getter: - (id)challenge;	// 0x35fee8f9
- (BOOL)checkValidity;	// 0x35fefae1
// declared property getter: - (BOOL)disabled;	// 0x35feebd1
// declared property getter: - (id)form;	// 0x35feedf1
// declared property getter: - (id)keytype;	// 0x35feeef5
// declared property getter: - (id)labels;	// 0x35fef979
// declared property getter: - (id)name;	// 0x35fef1cd
// declared property setter: - (void)setAutofocus:(BOOL)autofocus;	// 0x35fee7e5
// declared property setter: - (void)setChallenge:(id)challenge;	// 0x35feea1d
- (void)setCustomValidity:(id)validity;	// 0x35fefbe5
// declared property setter: - (void)setDisabled:(BOOL)disabled;	// 0x35feecdd
// declared property setter: - (void)setKeytype:(id)keytype;	// 0x35fef019
// declared property setter: - (void)setName:(id)name;	// 0x35fef2e9
// declared property getter: - (id)type;	// 0x35fef491
// declared property getter: - (id)validationMessage;	// 0x35fef7bd
// declared property getter: - (id)validity;	// 0x35fef6b1
// declared property getter: - (BOOL)willValidate;	// 0x35fef5ad
@end

