/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

#import <NSObject.h> // Unknown library
#import "iWorkImport-Structs.h"

@class GQZArchive, GQSDocument;

__attribute__((visibility("hidden")))
@interface GQPProcessor : NSObject {
@private
	xmlTextReader *mReader;	// 4 = 0x4
	xmlParserInputBuffer *mParserInputBuffer;	// 8 = 0x8
	GQZArchive *mArchive;	// 12 = 0xc
	stack<std::tr1::shared_ptr<StateSpec>,std::deque<std::tr1::shared_ptr<StateSpec>, std::allocator<std::tr1::shared_ptr<StateSpec> > > > *mStateStack;	// 16 = 0x10
	stack<std::pair<const Action*, int>,std::deque<std::pair<const Action*, int>, std::allocator<std::pair<const Action*, int> > > > *mActionStack;	// 20 = 0x14
	GQSDocument *mDocumentState;	// 24 = 0x18
	QLPreviewRequestRef mOutputPreviewRequest;	// 28 = 0x1c
	CFBundleRef mBundle;	// 32 = 0x20
	CGSize mThumbnailSize;	// 36 = 0x24
	BOOL mWrongFormat;	// 44 = 0x2c
	unsigned char mIsProgressive;	// 45 = 0x2d
}
@property(assign) CFBundleRef bundle;	// G=0x359a9cad; S=0x359a956d; converted property
@property(assign) CGSize thumbnailSize;	// G=0x359a95ad; S=0x359a95c5; converted property
@property(assign, getter=isWrongFormat) BOOL wrongFormat;	// G=0x359a95e9; S=0x359a95f9; converted property
+ (void)initialize;	// 0x359a9b79
- (id)initWithPath:(id)path indexFileName:(id)name previewRequest:(QLPreviewRequestRef)request;	// 0x359a965d
- (id)initWithZipArchive:(id)zipArchive indexFileName:(id)name previewRequest:(QLPreviewRequestRef)request;	// 0x359a9d9d
- (stack<std::pair<const Action*, int>,std::deque<std::pair<const Action*, int>, std::allocator<std::pair<const Action*, int> > > > *)actionStack;	// 0x359a958d
- (id)archive;	// 0x359a955d
// converted property getter: - (CFBundleRef)bundle;	// 0x359a9cad
- (void)dealloc;	// 0x359a9cd5
- (id)documentState;	// 0x359a959d
- (BOOL)go;	// 0x359a9ba9
// converted property getter: - (BOOL)isWrongFormat;	// 0x359a95e9
- (void)pushInitialState;	// 0x359a9559
// converted property setter: - (void)setBundle:(CFBundleRef)bundle;	// 0x359a956d
- (void)setProgressiveMode:(unsigned char)mode;	// 0x359a95d9
// converted property setter: - (void)setThumbnailSize:(CGSize)size;	// 0x359a95c5
// converted property setter: - (void)setWrongFormat:(BOOL)format;	// 0x359a95f9
- (stack<std::tr1::shared_ptr<StateSpec>,std::deque<std::tr1::shared_ptr<StateSpec>, std::allocator<std::tr1::shared_ptr<StateSpec> > > > *)stateStack;	// 0x359a957d
// converted property getter: - (CGSize)thumbnailSize;	// 0x359a95ad
@end

