/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRType.h"


@interface BRMediaCollectionType : BRType {
}
+ (id)composer;	// 0x303381d9
+ (id)compoundITunesAlbum;	// 0x30337f09
+ (id)compoundITunesArtist;	// 0x30337ff9
+ (id)genre;	// 0x303380e9
+ (id)iPhotoAlbum;	// 0x30337699
+ (id)iPhotoEvent;	// 0x30337789
+ (id)iPhotoFaces;	// 0x30337879
+ (id)iPhotoFolder;	// 0x30337969
+ (id)iPhotoSlideshow;	// 0x303375a9
+ (id)iTunesAlbum;	// 0x303373c9
+ (id)iTunesArtist;	// 0x303374b9
+ (id)iTunesFolderPlaylist;	// 0x30336d39
+ (id)iTunesGeniusMix;	// 0x30337009
+ (id)iTunesInternetRadioPlaylist;	// 0x30336e29
+ (id)iTunesMainGeniusPlaylist;	// 0x30336f19
+ (id)iTunesMainOnTheGoPlaylist;	// 0x303371e9
+ (id)iTunesPlaylist;	// 0x30336a69
+ (id)iTunesPurchasesPlaylist;	// 0x30336c49
+ (id)iTunesSavedGeniusPlaylist;	// 0x303370f9
+ (id)iTunesSavedOnTheGoPlaylist;	// 0x303372d9
+ (id)iTunesSmartPlaylist;	// 0x30336b59
+ (id)movieTrailer;	// 0x30337a59
+ (id)onTheGoCollectionTypes;	// 0x303383c9
+ (id)photoCollectionTypes;	// 0x303384f5
+ (id)playlistCollectionTypes;	// 0x303382c9
+ (id)podcastCollection;	// 0x30337b49
+ (id)podcastSubscriptionCollection;	// 0x30337c39
+ (id)unknown;	// 0x30336979
+ (id)video;	// 0x30337d29
+ (id)videoSlideshow;	// 0x30337e19
- (id)description;	// 0x303385a1
- (int)playlistTypeCompare:(id)compare;	// 0x303385e1
@end

