/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/UIKit.framework/UIKit
 */

#import "UIControl.h"
#import "UIKit-Structs.h"

@class UITableViewCell;

__attribute__((visibility("hidden")))
@interface UITableViewCellReorderControl : UIControl {
@private
	UITableViewCell *_cell;	// 68 = 0x44
	CGPoint _downPoint;	// 72 = 0x48
}
+ (CGSize)defaultSize;	// 0x300deb09
+ (id)grabberImage;	// 0x300deb51
- (id)initWithTableViewCell:(id)tableViewCell;	// 0x302b07bd
- (BOOL)beginTrackingWithTouch:(id)touch withEvent:(id)event;	// 0x302b0669
- (void)cancelTrackingWithEvent:(id)event;	// 0x302b0605
- (BOOL)continueTrackingWithTouch:(id)touch withEvent:(id)event;	// 0x302b0959
- (void)endTrackingWithTouch:(id)touch withEvent:(id)event;	// 0x302b0631
- (void)layoutSubviews;	// 0x302b0731
- (void)setFrame:(CGRect)frame;	// 0x302b06d5
- (BOOL)shouldTrack;	// 0x302b0601
@end

