/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

#import "DOMBlob.h"

@class NSString;

@interface DOMFile : DOMBlob {
}
@property(readonly, assign) NSString *name;	// G=0x3619f781; 
- (double)lastModifiedDate;	// 0x3619f891
// declared property getter: - (id)name;	// 0x3619f781
@end

