/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import "NSDirectoryTraversalOperation.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface NSDirectorySubpathsOperation : NSDirectoryTraversalOperation {
@private
	NSMutableArray *_subpaths;	// 40 = 0x28
}
@property(readonly, retain) NSMutableArray *subpaths;	// G=0x336b8155; converted property
+ (id)_errorWithErrno:(int)errno atPath:(id)path;	// 0x336b8021
+ (id)directorySubpathsOperationAtPath:(id)path;	// 0x336b802d
- (void)dealloc;	// 0x336b81c5
- (void)handlePathname:(id)pathname;	// 0x336b807d
// converted property getter: - (id)subpaths;	// 0x336b8155
@end

