/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/Frameworks/Foundation.framework/Foundation
 */

#import <NSObject.h> // Unknown library


@interface NSFileManager : NSObject {
}
@property(assign) id delegate;	// G=0x33673425; S=0x336b53c1; converted property
+ (id)defaultManager;	// 0x3364dbe1
- (id)URLForDirectory:(unsigned)directory inDomain:(unsigned)domain appropriateForURL:(id)url create:(BOOL)create error:(id *)error;	// 0x336b44e5
- (id)URLForPublishingUbiquitousItemAtURL:(id)url expirationDate:(id *)date error:(id *)error;	// 0x336b75b1
- (id)URLForUbiquityContainerIdentifier:(id)ubiquityContainerIdentifier;	// 0x336b72bd
- (id)URLsForDirectory:(unsigned)directory inDomains:(unsigned)domains;	// 0x33697ecd
- (id)_URLForReplacingItemAtURL:(id)url error:(id *)error;	// 0x336b4235
- (id)_attributesOfItemAtPath:(id)path filterResourceFork:(BOOL)fork error:(id *)error;	// 0x336b6675
- (id)_attributesOfItemAtURL:(id)url filterResourceFork:(BOOL)fork error:(id *)error;	// 0x336b66a5
- (id)_displayPathForPath:(id)path;	// 0x336b4861
- (id)_info;	// 0x33673449
- (void)_performRemoveFileAtPath:(id)path;	// 0x336fd4ed
- (void)_web_backgroundRemoveFileAtPath:(id)path;	// 0x336fd535
- (void)_web_backgroundRemoveLeftoverFiles:(id)files;	// 0x336fd629
- (id)_web_carbonPathForPath_nowarn:(id)path_nowarn;	// 0x336fda25
- (BOOL)_web_changeFileAttributes_nowarn:(id)nowarn atPath:(id)path;	// 0x336fdd45
- (BOOL)_web_changeFinderAttributes:(id)attributes forFileAtPath:(id)path;	// 0x336fd4a1
- (BOOL)_web_createDirectoryAtPathWithIntermediateDirectories:(id)intermediateDirectories attributes:(id)attributes;	// 0x33677655
- (BOOL)_web_createFileAtPath:(id)path contents:(id)contents attributes:(id)attributes;	// 0x336fd4a5
- (BOOL)_web_createFileAtPathWithIntermediateDirectories:(id)intermediateDirectories contents:(id)contents attributes:(id)attributes directoryAttributes:(id)attributes4;	// 0x336fd40d
- (BOOL)_web_createIntermediateDirectoriesForPath_nowarn:(id)path_nowarn attributes:(id)attributes;	// 0x336fda75
- (BOOL)_web_fileExistsAtPath_nowarn:(id)path_nowarn isDirectory:(BOOL *)directory traverseLink:(BOOL)link;	// 0x336fd8ed
- (void)_web_noteFileChangedAtPath_nowarn:(id)path_nowarn;	// 0x336fdd41
- (id)_web_pathWithUniqueFilenameForPath:(id)path;	// 0x336fd73d
- (BOOL)_web_removeFileOnlyAtPath:(id)path;	// 0x3367816d
- (id)_web_startupVolumeName_nowarn;	// 0x336fda29
- (id)_web_visibleItemsInDirectoryAtPath:(id)path;	// 0x336fd729
- (id)attributesOfFileSystemForPath:(id)path error:(id *)error;	// 0x3366f00d
- (id)attributesOfItemAtPath:(id)path error:(id *)error;	// 0x33680a89
- (BOOL)changeCurrentDirectoryPath:(id)path;	// 0x336b4ae5
- (BOOL)changeFileAttributes:(id)attributes atPath:(id)path;	// 0x336b4b41
- (id)componentsToDisplayForPath:(id)path;	// 0x336b5121
- (id)contentsAtPath:(id)path;	// 0x3368e3b5
- (BOOL)contentsEqualAtPath:(id)path andPath:(id)path2;	// 0x336b4d95
- (id)contentsOfDirectoryAtPath:(id)path error:(id *)error;	// 0x3367768d
- (id)contentsOfDirectoryAtURL:(id)url includingPropertiesForKeys:(id)keys options:(unsigned)options error:(id *)error;	// 0x336b3f15
- (BOOL)copyItemAtPath:(id)path toPath:(id)path2 error:(id *)error;	// 0x336b5601
- (BOOL)copyItemAtURL:(id)url toURL:(id)url2 error:(id *)error;	// 0x336b5721
- (BOOL)createDirectoryAtPath:(id)path attributes:(id)attributes;	// 0x336b4d21
- (BOOL)createDirectoryAtPath:(id)path withIntermediateDirectories:(BOOL)intermediateDirectories attributes:(id)attributes error:(id *)error;	// 0x336516f1
- (BOOL)createDirectoryAtURL:(id)url withIntermediateDirectories:(BOOL)intermediateDirectories attributes:(id)attributes error:(id *)error;	// 0x336b64e5
- (BOOL)createFileAtPath:(id)path contents:(id)contents attributes:(id)attributes;	// 0x3368dbe5
- (BOOL)createSymbolicLinkAtPath:(id)path pathContent:(id)content;	// 0x336b4d71
- (BOOL)createSymbolicLinkAtPath:(id)path withDestinationPath:(id)destinationPath error:(id *)error;	// 0x336b66d5
- (BOOL)createSymbolicLinkAtURL:(id)url withDestinationURL:(id)destinationURL error:(id *)error;	// 0x336b678d
- (id)currentDirectoryPath;	// 0x336b4a9d
- (void)dealloc;	// 0x3366f705
// converted property getter: - (id)delegate;	// 0x33673425
- (id)destinationOfSymbolicLinkAtPath:(id)path error:(id *)error;	// 0x3368fbf5
- (BOOL)directoryCanBeCreatedAtPath:(id)path;	// 0x336b4a39
- (id)directoryContentsAtPath:(id)path;	// 0x336b4cd5
- (id)directoryContentsAtPath:(id)path matchingExtension:(id)extension options:(int)options keepExtension:(BOOL)extension4;	// 0x336b4ca9
- (id)directoryContentsAtPath:(id)path matchingExtension:(id)extension options:(int)options keepExtension:(BOOL)extension4 error:(id *)error;	// 0x336776b9
- (id)displayNameAtPath:(id)path;	// 0x336b4c41
- (id)enumeratorAtPath:(id)path;	// 0x3368faa9
- (id)enumeratorAtURL:(id)url includingPropertiesForKeys:(id)keys options:(unsigned)options errorHandler:(id)handler;	// 0x33698079
- (BOOL)evictUbiquitousItemAtURL:(id)url error:(id *)error;	// 0x336b70a9
- (id)extendedAttributeForKey:(id)key atPath:(id)path error:(id *)error;	// 0x336b5159
- (id)extendedAttributesAtPath:(id)path error:(id *)error;	// 0x336b5135
- (id)fileAttributesAtPath:(id)path traverseLink:(BOOL)link;	// 0x336b4b25
- (BOOL)fileExistsAtPath:(id)path;	// 0x3364dc3d
- (BOOL)fileExistsAtPath:(id)path isDirectory:(BOOL *)directory;	// 0x336519dd
- (id)fileSystemAttributesAtPath:(id)path;	// 0x336b510d
- (const char *)fileSystemRepresentationWithPath:(id)path;	// 0x33651b8d
- (BOOL)filesystemItemCopyOperation:(id)operation shouldCopyItemAtPath:(id)path toPath:(id)path3;	// 0x336b53e9
- (BOOL)filesystemItemCopyOperation:(id)operation shouldProceedAfterError:(id)error copyingItemAtPath:(id)path toPath:(id)path4;	// 0x336b54f1
- (BOOL)filesystemItemLinkOperation:(id)operation shouldLinkItemAtPath:(id)path toPath:(id)path3;	// 0x336b5d51
- (BOOL)filesystemItemLinkOperation:(id)operation shouldProceedAfterError:(id)error linkingItemAtPath:(id)path toPath:(id)path4;	// 0x336b5e59
- (BOOL)filesystemItemMoveOperation:(id)operation shouldMoveItemAtPath:(id)path toPath:(id)path3;	// 0x336b589d
- (BOOL)filesystemItemMoveOperation:(id)operation shouldProceedAfterError:(id)error movingItemAtPath:(id)path toPath:(id)path4;	// 0x336b59a5
- (BOOL)filesystemItemRemoveOperation:(id)operation shouldProceedAfterError:(id)error removingItemAtPath:(id)path;	// 0x33673821
- (BOOL)filesystemItemRemoveOperation:(id)operation shouldRemoveItemAtPath:(id)path;	// 0x33673351
- (BOOL)getFileSystemRepresentation:(char *)representation maxLength:(unsigned)length withPath:(id)path;	// 0x3364de49
- (BOOL)isDeletableFileAtPath:(id)path;	// 0x336b4b75
- (BOOL)isExecutableFileAtPath:(id)path;	// 0x336b4b65
- (BOOL)isReadableFileAtPath:(id)path;	// 0x3367bda9
- (BOOL)isUbiquitousItemAtURL:(id)url;	// 0x336b6f0d
- (BOOL)isWritableFileAtPath:(id)path;	// 0x3366fac9
- (BOOL)linkItemAtPath:(id)path toPath:(id)path2 error:(id *)error;	// 0x336b5f69
- (BOOL)linkItemAtURL:(id)url toURL:(id)url2 error:(id *)error;	// 0x336b6089
- (id)mountedVolumeURLsIncludingResourceValuesForKeys:(id)keys options:(unsigned)options;	// 0x336b3f11
- (BOOL)moveItemAtPath:(id)path toPath:(id)path2 error:(id *)error;	// 0x336b5ab5
- (BOOL)moveItemAtURL:(id)url toURL:(id)url2 error:(id *)error;	// 0x336b5bd5
- (id)pathContentOfSymbolicLinkAtPath:(id)path;	// 0x336b4d5d
- (BOOL)removeExtendedAttributeForKey:(id)key atPath:(id)path error:(id *)error;	// 0x336b5251
- (BOOL)removeFileAtPath:(id)path handler:(id)handler;	// 0x336b4c91
- (BOOL)removeItemAtPath:(id)path error:(id *)error;	// 0x33671dd1
- (BOOL)removeItemAtURL:(id)url error:(id *)error;	// 0x336b6205
- (BOOL)replaceItemAtURL:(id)url withItemAtURL:(id)url2 backupItemName:(id)name options:(unsigned)options resultingItemURL:(id *)url5 error:(id *)error;	// 0x336b68ed
- (BOOL)setAttributes:(id)attributes ofItemAtPath:(id)path error:(id *)error;	// 0x33696441
// converted property setter: - (void)setDelegate:(id)delegate;	// 0x336b53c1
- (BOOL)setExtendedAttribute:(id)attribute forKey:(id)key atPath:(id)path error:(id *)error;	// 0x336b52dd
- (BOOL)setUbiquitous:(BOOL)ubiquitous itemAtURL:(id)url destinationURL:(id)url3 error:(id *)error;	// 0x336b6ced
- (BOOL)startDownloadingUbiquitousItemAtURL:(id)url error:(id *)error;	// 0x336b6a11
- (id)stringWithFileSystemRepresentation:(const char *)fileSystemRepresentation length:(unsigned)length;	// 0x33651579
- (id)subpathsAtPath:(id)path;	// 0x336b4cf9
- (id)subpathsOfDirectoryAtPath:(id)path error:(id *)error;	// 0x336b65a5
@end

