/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AggregateDictionary.framework/AggregateDictionary
 */

#import "AggregateDictionary-Structs.h"
#import <NSObject.h> // Unknown library

@class ADCrashLogStore, ADDataStore, ADKeyStore, NSString;

@interface AggregateDictionary : NSObject {
	dispatch_queue_s *_dataStoreQueue;	// 4 = 0x4
	ADKeyStore *_keyStore;	// 8 = 0x8
	ADDataStore *_dataStore;	// 12 = 0xc
	ADCrashLogStore *_crashLogStore;	// 16 = 0x10
	unsigned _messageCount;	// 20 = 0x14
	int _commitInterval;	// 24 = 0x18
	BOOL _logsMessages;	// 28 = 0x1c
}
@property(assign, nonatomic) int commitInterval;	// G=0x3014c135; S=0x3014c145; @synthesize=_commitInterval
@property(readonly, assign, nonatomic) NSString *dataStorePath;	// G=0x3014c561; 
@property(assign, nonatomic) BOOL logsMessages;	// G=0x3014c115; S=0x3014c125; @synthesize=_logsMessages
+ (void)startOnBackgroundThread;	// 0x3014d015
- (id)init;	// 0x3014c581
- (id)initWithStorePath:(id)storePath;	// 0x3014c65d
- (void)_addScalar:(long long)scalar toKey:(id)key useCurrentValue:(BOOL)value;	// 0x3014cbcd
- (BOOL)_crashLogCopyingEnabled;	// 0x3014cf01
- (void)_executeIfDistributionKeyIsWhitelisted:(id)whitelisted block:(id)block;	// 0x3014c599
- (void)_executeIfScalarKeyIsWhitelisted:(id)whitelisted block:(id)block;	// 0x3014c5d5
- (void)_initializeDistribution:(XXStruct_j7IYfC *)distribution forDouble:(double)aDouble;	// 0x3014c085
- (void)_keyModified:(id)modified byCommand:(SEL)command;	// 0x3014cf89
- (void)_pushDouble:(double)aDouble ontoDistribution:(XXStruct_j7IYfC *)distribution;	// 0x3014c0b1
- (void)_pushDouble:(double)aDouble ontoKey:(id)key useCurrentValue:(BOOL)value;	// 0x3014ca99
- (void)addValue:(long long)value forScalarKey:(id)scalarKey;	// 0x3014c34d
- (void)clearDistributionKey:(id)key;	// 0x3014c19d
- (void)clearScalarKey:(id)key;	// 0x3014c4ad
- (int)commit;	// 0x3014cf21
// declared property getter: - (int)commitInterval;	// 0x3014c135
// declared property getter: - (id)dataStorePath;	// 0x3014c561
- (void)dealloc;	// 0x3014ce85
// declared property getter: - (BOOL)logsMessages;	// 0x3014c115
- (void)pushValue:(double)value forDistributionKey:(id)distributionKey;	// 0x3014c1ed
// declared property setter: - (void)setCommitInterval:(int)interval;	// 0x3014c145
// declared property setter: - (void)setLogsMessages:(BOOL)messages;	// 0x3014c125
- (void)setValue:(double)value forDistributionKey:(id)distributionKey;	// 0x3014c29d
- (void)setValue:(long long)value forScalarKey:(id)scalarKey;	// 0x3014c3fd
- (void)significantTimeChanged;	// 0x3014c611
@end

