/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ATVUpdatable.h"
#import "AppleTV-Structs.h"
#import "ATVRelatedPlaybackViewController.h"

@class ATVFeedElement, BRControl, ATVFeedRelatedPlaybackElement, ATVFeedDocument, ATVVideoAsset, BRListView;
@protocol BRImageProxy;

__attribute__((visibility("hidden")))
@interface ATVFeedRelatedPlaybackViewController : ATVRelatedPlaybackViewController <ATVUpdatable> {
	ATVFeedElement *_playerElement;	// 4 = 0x4
	ATVFeedDocument *_feedDocument;	// 8 = 0x8
	ATVVideoAsset *_upNextVideo;	// 12 = 0xc
	id<BRImageProxy> _upNextVideoImageProxy;	// 16 = 0x10
	BRControl *_relatedPlayerView;	// 20 = 0x14
	BRListView *_optionsView;	// 24 = 0x18
}
@property(retain, nonatomic) ATVFeedDocument *feedDocument;	// G=0x20bb89; S=0x209801; @synthesize=_feedDocument
@property(retain, nonatomic) BRListView *optionsView;	// G=0x20bc2d; S=0x20bc3d; @synthesize=_optionsView
@property(readonly, assign, nonatomic) ATVFeedElement *playerElement;	// G=0x20bb79; @synthesize=_playerElement
@property(readonly, assign, nonatomic) ATVFeedRelatedPlaybackElement *relatedPlaybackElement;	// G=0x20977d; 
@property(retain, nonatomic) BRControl *relatedPlayerView;	// G=0x20bbf5; S=0x20bc05; @synthesize=_relatedPlayerView
@property(retain, nonatomic) ATVVideoAsset *upNextVideo;	// G=0x20bb99; S=0x20bba9; @synthesize=_upNextVideo
@property(retain, nonatomic) id<BRImageProxy> upNextVideoImageProxy;	// G=0x20bbd1; S=0x20bbe1; @synthesize=_upNextVideoImageProxy
- (id)initWithPlayer:(id)player playerElement:(id)element;	// 0x20970d
- (void).cxx_destruct;	// 0x20bc65
- (BOOL)_canDisplayUpNextMenuSection;	// 0x20b345
- (void)_cancelPreparation;	// 0x20afed
- (void)_cleanup;	// 0x20b8e5
- (BOOL)_containsOptions:(id)options;	// 0x20b3d1
- (BOOL)_handleUpNextMenuItemSelection:(id)selection;	// 0x20b1e1
- (void)_imageUpdated:(id)updated;	// 0x20b9f1
- (id)_makeRelatedPlaybackView;	// 0x20b785
- (void)_prepareRelatedPlayback;	// 0x209f69
- (void)_presentationDidBegin;	// 0x20affd
- (void)_remainingPlaybackTimeDidChange;	// 0x20b0e5
- (id)_upNextJSParamterFromVideoAsset:(id)videoAsset context:(OpaqueJSContext *)context;	// 0x20b64d
- (id)_upNextTimeString;	// 0x20b595
// declared property getter: - (id)feedDocument;	// 0x20bb89
- (float)list:(id)list heightForItemAtIndexPath:(id)indexPath;	// 0x209d59
- (id)list:(id)list menuItemForRowAtIndexPath:(id)indexPath;	// 0x209b55
- (long)list:(id)list numberOfRowsInSection:(long)section;	// 0x209a59
- (id)list:(id)list sectionHeaderForSection:(long)section;	// 0x2098e9
- (long)numberOfSectionsInList:(id)list;	// 0x209865
// declared property getter: - (id)optionsView;	// 0x20bc2d
// declared property getter: - (id)playerElement;	// 0x20bb79
// declared property getter: - (id)relatedPlaybackElement;	// 0x20977d
// declared property getter: - (id)relatedPlayerView;	// 0x20bbf5
// declared property setter: - (void)setFeedDocument:(id)document;	// 0x209801
// declared property setter: - (void)setOptionsView:(id)view;	// 0x20bc3d
// declared property setter: - (void)setRelatedPlayerView:(id)view;	// 0x20bc05
// declared property setter: - (void)setUpNextVideo:(id)video;	// 0x20bba9
// declared property setter: - (void)setUpNextVideoImageProxy:(id)proxy;	// 0x20bbe1
// declared property getter: - (id)upNextVideo;	// 0x20bb99
// declared property getter: - (id)upNextVideoImageProxy;	// 0x20bbd1
- (void)updateWithFeedElement:(id)feedElement;	// 0x209f2d
- (void)updateWithPropertyList:(id)propertyList;	// 0x209f65
@end

