/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

#import <NSObject.h> // Unknown library

@class NSString, ISURLCacheConfiguration, NSURLCache;

@interface ISURLCache : NSObject {
	NSURLCache *_cache;	// 4 = 0x4
	ISURLCacheConfiguration *_configuration;	// 8 = 0x8
}
@property(readonly, assign, nonatomic) unsigned currentDiskUsage;	// G=0x368991b1; 
@property(readonly, assign, nonatomic) unsigned currentMemoryUsage;	// G=0x368991d1; 
@property(readonly, assign, nonatomic) unsigned diskCapacity;	// G=0x368991f1; 
@property(readonly, assign, nonatomic) unsigned memoryCapacity;	// G=0x36899211; 
@property(readonly, assign) NSString *persistentIdentifier;	// G=0x36898f5d; 
+ (id)cacheDirectoryPath;	// 0x36898e6d
- (id)init;	// 0x36898d75
- (id)initWithCacheConfiguration:(id)cacheConfiguration;	// 0x36898d89
- (id)cachedResponseForRequest:(id)request;	// 0x36899191
// declared property getter: - (unsigned)currentDiskUsage;	// 0x368991b1
// declared property getter: - (unsigned)currentMemoryUsage;	// 0x368991d1
- (void)dealloc;	// 0x36898e09
// declared property getter: - (unsigned)diskCapacity;	// 0x368991f1
// declared property getter: - (unsigned)memoryCapacity;	// 0x36899211
// declared property getter: - (id)persistentIdentifier;	// 0x36898f5d
- (void)purgeMemoryCache;	// 0x36899231
- (void)reloadWithCacheConfiguration:(id)cacheConfiguration;	// 0x36898f7d
- (void)removeAllCachedResponses;	// 0x36899279
- (void)removeCachedResponseForRequest:(id)request;	// 0x36899299
- (void)saveMemoryCacheToDisk;	// 0x368992b9
- (void)storeCachedResponse:(id)response forRequest:(id)request;	// 0x36899301
@end

