/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/ImageCapture.framework/ImageCapture
 */

#import "ImageCapture-Structs.h"
#import </libobjc.A.h>


@interface ICPTPIPClient : NSObject {
	id _clientProperties;	// 4 = 0x4
}
@property(assign) CFFileDescriptorRef fdref;	// G=0x3129c8ad; S=0x3129c8cd; converted property
@property(assign) int pid;	// G=0x3129c829; S=0x3129c849; converted property
@property(assign) BOOL registered;	// G=0x3129c869; S=0x3129c88d; converted property
@property(assign) int remoteAddress;	// G=0x3129c92d; S=0x3129c94d; converted property
@property(assign) CFMessagePortRef remotePort;	// G=0x3129c8ed; S=0x3129c90d; converted property
@property(assign) int serverFD;	// G=0x3129c96d; S=0x3129c98d; converted property
- (id)init;	// 0x3129c7c5
// converted property getter: - (CFFileDescriptorRef)fdref;	// 0x3129c8ad
// converted property getter: - (int)pid;	// 0x3129c829
// converted property getter: - (BOOL)registered;	// 0x3129c869
// converted property getter: - (int)remoteAddress;	// 0x3129c92d
// converted property getter: - (CFMessagePortRef)remotePort;	// 0x3129c8ed
// converted property getter: - (int)serverFD;	// 0x3129c96d
// converted property setter: - (void)setFdref:(CFFileDescriptorRef)fdref;	// 0x3129c8cd
// converted property setter: - (void)setPid:(int)pid;	// 0x3129c849
// converted property setter: - (void)setRegistered:(BOOL)registered;	// 0x3129c88d
// converted property setter: - (void)setRemoteAddress:(int)address;	// 0x3129c94d
// converted property setter: - (void)setRemotePort:(CFMessagePortRef)port;	// 0x3129c90d
// converted property setter: - (void)setServerFD:(int)fd;	// 0x3129c98d
@end

