/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
 */

#import <NSObject.h> // Unknown library

@class SSXPCConnection;

@interface SSDownloadFileManifest : NSObject {
@private
	SSXPCConnection *_connection;	// 4 = 0x4
	int _manifestType;	// 8 = 0x8
}
@property(readonly, assign) int manifestType;	// G=0x34e7fc01; 
- (id)init;	// 0x34e7f855
- (id)initWithManifestType:(int)manifestType;	// 0x34e7f869
- (void)_removeItemsWithAssetPaths:(id)assetPaths completionBlock:(id)block;	// 0x34e7fe29
- (void)dealloc;	// 0x34e7f8f5
- (void)getPathsForFilesWithClass:(int)aClass completionBlock:(id)block;	// 0x34e7f941
// declared property getter: - (int)manifestType;	// 0x34e7fc01
- (void)rebuildManifestWithCompletionBlock:(id)completionBlock;	// 0x34e7fc11
- (void)removeItemWithAssetPath:(id)assetPath completionBlock:(id)block;	// 0x34e7fce5
- (void)removeItemsWithAssetPaths:(id)assetPaths completionBlock:(id)block;	// 0x34e7fdb1
@end

