/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

#import <NSObject.h> // Unknown library

@class NSString;

@interface WDCitationAuthor : NSObject {
	NSString *mFirst;	// 4 = 0x4
	NSString *mLast;	// 8 = 0x8
}
@property(retain, nonatomic) NSString *first;	// G=0x34aac3f9; S=0x34aac409; @synthesize=mFirst
@property(retain, nonatomic) NSString *last;	// G=0x34aac419; S=0x34aac429; @synthesize=mLast
- (id)initWithFirst:(id)first last:(id)last;	// 0x34aac381
- (void)dealloc;	// 0x34aac31d
// declared property getter: - (id)first;	// 0x34aac3f9
// declared property getter: - (id)last;	// 0x34aac419
// declared property setter: - (void)setFirst:(id)first;	// 0x34aac409
// declared property setter: - (void)setLast:(id)last;	// 0x34aac429
@end

